/* eslint-disable @typescript-eslint/no-explicit-any */

export type PartialCodOrderFinalizeInput = { shopId: string; shopDomain: string; checkoutIntentId: string; customerProfileId: string };
type Deps = { db?: any; graphql?: any; audit?: any; consumeStoreCredit?: any; getStoreCreditReservation?: any; resolvePolicy?: any; now?: () => Date };
type JsonRecord = Record<string, unknown>;

export class PartialCodOrderFinalizationError extends Error { status: 401 | 404 | 409 | 502 | 503; code: string; constructor(status: 401 | 404 | 409 | 502 | 503, code: string, message: string) { super(message); this.name = "PartialCodOrderFinalizationError"; this.status = status; this.code = code; } }

const ELIGIBLE_STATUSES = new Set(["PAYMENT_PENDING", "PAYMENT_SELECTED", "PAYMENT_METHOD_SELECTED", "ADDRESS_COMPLETED", "DELIVERY_VALIDATED", "COUPON_APPLIED", "ADVANCE_PAID"]);
function safeInt(value: unknown) { return Number.isSafeInteger(value) && Number(value) >= 0 ? Number(value) : null; }
function sameCurrency(a: unknown, b: unknown) { return String(a || "").toUpperCase() === String(b || "").toUpperCase(); }
function asRecord(value: unknown): JsonRecord | null { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : null; }
function paiseToAmount(paise: number) { return (Math.max(0, Math.round(Number(paise) || 0)) / 100).toFixed(2); }
function paiseToNumber(paise: number) { return Math.max(0, Math.round(Number(paise) || 0)) / 100; }
function lines(snapshot: unknown) { const s = asRecord(snapshot); const arr = Array.isArray(snapshot) ? snapshot : Array.isArray(s?.lineItems) ? s?.lineItems : Array.isArray(s?.items) ? s?.items : Array.isArray(s?.lines) ? s?.lines : []; const map = new Map<string, { variantId: string; quantity: number }>(); for (const item of arr as any[]) { const r = asRecord(item); if (!r) continue; const raw = String(r.variantId || r.shopifyVariantId || r.merchandiseId || r.variant_id || "").trim(); const n = raw.replace(/\D/g, ""); const variantId = raw.startsWith("gid://shopify/ProductVariant/") ? raw : n ? `gid://shopify/ProductVariant/${n}` : ""; const quantity = Math.max(0, Math.floor(Number(r.quantity || 0))); if (!variantId || quantity <= 0) continue; map.set(variantId, { variantId, quantity: (map.get(variantId)?.quantity || 0) + quantity }); } return [...map.values()]; }
function nameParts(fullName: string) { const p = fullName.trim().split(/\s+/).filter(Boolean); return p.length <= 1 ? { firstName: p[0] || fullName.trim(), lastName: undefined } : { firstName: p.slice(0, -1).join(" "), lastName: p.at(-1) }; }
function customerGid(id?: string | null) { if (!id) return undefined; if (id.startsWith("gid://shopify/Customer/")) return id; return /^\d+$/.test(id) ? `gid://shopify/Customer/${id}` : undefined; }
function success(input: { reused: boolean; intentId: string; link: any; order?: any; cod: any }) { const order = input.order || {}; return { ok: true, reused: input.reused, intentId: input.intentId, order: { id: order.id || input.link.shopifyOrderId || null, name: order.name || input.link.shopifyOrderName || null, statusUrl: order.statusUrl || null }, payment: { mode: "PARTIAL_COD", advancePaidPaise: input.cod.advanceAmountPaise, codBalanceAmountPaise: input.cod.codBalanceAmountPaise, storeCreditAppliedPaise: input.cod.storeCreditAppliedPaise || 0, currency: input.cod.currency } }; }
function userError(errors?: Array<{ message?: string | null }>) { return (errors || []).map(e => String(e.message || "").trim()).filter(Boolean).join(", ") || "Shopify draft order error"; }
async function audit(deps: Deps, event: string, entity: string, id: string | null, payload?: unknown) { const fallback = deps.audit || (await import("./core.ts")).auditCodAdvance; await fallback(event, entity, id, payload).catch(() => undefined); }

async function load(db: any, input: PartialCodOrderFinalizeInput, policy: any) {
  const checkout = await db.expressCheckoutIntent.findFirst({ where: { id: input.checkoutIntentId, shopId: input.shopId, customerProfileId: input.customerProfileId }, include: { orderLink: true, discounts: { orderBy: { createdAt: "desc" } } } });
  if (!checkout) throw new PartialCodOrderFinalizationError(404, "CHECKOUT_NOT_ELIGIBLE", "Checkout not found");
  if (checkout.selectedPaymentMethod !== "COD" || !ELIGIBLE_STATUSES.has(checkout.status)) throw new PartialCodOrderFinalizationError(409, "CHECKOUT_NOT_ELIGIBLE", "Checkout is not eligible");
  if (!policy.requiresAdvance || !policy.codAdvanceIntentId) throw new PartialCodOrderFinalizationError(409, "CHECKOUT_NOT_ELIGIBLE", "Partial COD is not required");
  const cod = await db.codAdvanceIntent.findFirst({ where: { id: policy.codAdvanceIntentId, shopId: input.shopId, expressCheckoutIntentId: input.checkoutIntentId, customerProfileId: input.customerProfileId } });
  if (!cod) throw new PartialCodOrderFinalizationError(404, "PARTIAL_COD_NOT_VERIFIED", "COD advance intent not found");
  const existingLink = checkout.orderLink || await db.expressCheckoutOrderLink.findFirst({ where: { shopId: input.shopId, intentId: input.checkoutIntentId } });
  if (cod.status === "ORDER_LINKED" && existingLink?.shopifyOrderId && cod.shopifyOrderId === existingLink.shopifyOrderId) return { checkout, cod, payment: null, existingLink, idempotent: true };
  if (cod.status !== "ADVANCE_PAID" || safeInt(cod.advanceAmountPaise) === null || cod.advanceAmountPaise <= 0 || safeInt(cod.codBalanceAmountPaise) === null || !cod.paidAt || !cod.verifiedAt || !cod.razorpayPaymentId || cod.consumedAt) throw new PartialCodOrderFinalizationError(409, cod.consumedAt ? "PARTIAL_COD_ALREADY_CONSUMED" : "PARTIAL_COD_NOT_VERIFIED", "COD advance is not verified");
  const payment = await db.expressCheckoutPayment.findFirst({ where: { shopId: input.shopId, intentId: input.checkoutIntentId, method: "COD", purpose: "COD_ADVANCE", status: "CONFIRMED", razorpayPaymentId: cod.razorpayPaymentId, razorpayOrderId: cod.providerReferenceId || undefined } });
  if (!payment || !payment.verifiedAt || payment.amountPaise !== cod.advanceAmountPaise || payment.providerAmountPaise !== cod.advanceAmountPaise || !sameCurrency(payment.currency, cod.currency) || !sameCurrency(payment.providerCurrency, cod.currency)) throw new PartialCodOrderFinalizationError(409, "PARTIAL_COD_PAYMENT_MISMATCH", "COD advance payment mismatch");
  for (const v of [checkout.totalAmountPaise, checkout.subtotalAmountPaise, checkout.discountAmountPaise, checkout.shippingAmountPaise, checkout.codFeeAmountPaise, cod.orderAmountPaise, cod.storeCreditAppliedPaise || 0, cod.customerCashLiabilityPaise, cod.advanceAmountPaise, cod.codBalanceAmountPaise]) if (safeInt(v) === null) throw new PartialCodOrderFinalizationError(409, "PARTIAL_COD_PRICING_CHANGED", "Unsafe pricing value");
  const invariantCash = checkout.totalAmountPaise - (cod.storeCreditAppliedPaise || 0);
  if (checkout.totalAmountPaise !== cod.orderAmountPaise || checkout.subtotalAmountPaise !== cod.merchandiseAmountPaise || checkout.discountAmountPaise !== cod.shopifyDiscountAmountPaise || checkout.shippingAmountPaise !== cod.shippingAmountPaise || checkout.codFeeAmountPaise !== cod.codFeeAmountPaise || invariantCash !== cod.customerCashLiabilityPaise || cod.customerCashLiabilityPaise - cod.advanceAmountPaise !== cod.codBalanceAmountPaise || cod.advanceAmountPaise > cod.customerCashLiabilityPaise || policy.pricingFingerprint !== undefined && cod.pricingFingerprint !== policy.pricingFingerprint || policy.settingsVersion !== undefined && cod.settingsVersion !== policy.settingsVersion || !sameCurrency(checkout.currency, cod.currency) || !sameCurrency(policy.currency, cod.currency)) throw new PartialCodOrderFinalizationError(409, "PARTIAL_COD_PRICING_CHANGED", "Partial COD pricing changed");
  if (existingLink?.shopifyOrderId && existingLink.shopifyOrderId !== cod.shopifyOrderId) throw new PartialCodOrderFinalizationError(409, "PARTIAL_COD_RECONCILIATION_REQUIRED", "Conflicting Shopify order link");
  return { checkout, cod, payment, existingLink, idempotent: false };
}

export async function finalizePartialCodExpressCheckoutOrder(input: PartialCodOrderFinalizeInput, deps: Deps = {}) {
  const db = deps.db || (await import("../db/prisma.ts")).prisma; const graphql = deps.graphql || (await import("../express-checkout/shopify-admin.ts")).shopifyAdminGraphql; const resolvePolicy = deps.resolvePolicy || (await import("./resolver.ts")).resolveExpressCheckoutCodPolicy;
  await audit(deps, "partial_cod.order.finalization_started", "ExpressCheckoutIntent", input.checkoutIntentId, { shopId: input.shopId });
  const policy = await resolvePolicy(input, db, { audit: deps.audit });
  const prepared = await db.$transaction(async (tx: any) => { if (typeof tx.$executeRaw === "function") await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`${input.shopId}:${input.checkoutIntentId}:partial_cod_order_finalize`}))`; return load(tx, input, policy); });
  if (prepared.idempotent) { await audit(deps, "partial_cod.shopify_order.reused", "CodAdvanceIntent", prepared.cod.id, { shopId: input.shopId, checkoutIntentId: input.checkoutIntentId }); return success({ reused: true, intentId: input.checkoutIntentId, link: prepared.existingLink, cod: prepared.cod }); }
  const { checkout, cod } = prepared;
  try {
    const customer = await db.customerProfile.findFirst({ where: { shopId: input.shopId, id: input.customerProfileId } });
    const address = await db.expressCheckoutAddressSnapshot.findFirst({ where: { shopId: input.shopId, intentId: input.checkoutIntentId, customerProfileId: input.customerProfileId }, orderBy: { createdAt: "desc" } });
    if (!address) throw new PartialCodOrderFinalizationError(409, "CHECKOUT_NOT_ELIGIBLE", "Address required");
    const lineItems = lines(checkout.cartSnapshot); if (!lineItems.length) throw new PartialCodOrderFinalizationError(409, "CHECKOUT_NOT_ELIGIBLE", "Cart lines required");
    const { firstName, lastName } = nameParts(address.name); const shippingAddress = { firstName, lastName, address1: address.address1, address2: address.address2, city: address.city, province: address.province, country: address.country, zip: address.zip, phone: address.phone };
    const storeCreditReservation = await (deps.getStoreCreditReservation || (await import("../express-checkout/store-credit.ts")).getActiveStoreCreditReservation)({ shopId: input.shopId, customerProfileId: input.customerProfileId, checkoutIntentId: input.checkoutIntentId });
    const storeCreditAmountPaise = Math.min(Number(storeCreditReservation?.reservedAmount || 0), cod.storeCreditAppliedPaise || 0);
    const appliedDiscount = checkout.discountAmountPaise > 0 ? { title: "Express checkout discount", value: paiseToNumber(checkout.discountAmountPaise), valueType: "FIXED_AMOUNT" } : undefined;
    const customAttributes = [
      { key: "megaska_express_intent_id", value: checkout.id }, { key: "megaska_customer_profile_id", value: input.customerProfileId }, { key: "megaska_payment_method", value: "PARTIAL_COD" }, { key: "loopdesk_payment_mode", value: "PARTIAL_COD" },
      { key: "loopdesk_cod_advance_paid", value: String(cod.advanceAmountPaise) }, { key: "loopdesk_cod_balance", value: String(cod.codBalanceAmountPaise) }, { key: "loopdesk_customer_cash_liability", value: String(cod.customerCashLiabilityPaise) }, { key: "loopdesk_store_credit_applied", value: String(cod.storeCreditAppliedPaise || 0) },
      { key: "loopdesk_cod_advance_verified", value: "true" }, { key: "loopdesk_cod_advance_payment_id", value: cod.razorpayPaymentId }, { key: "loopdesk_cod_advance_intent_id", value: cod.id }, { key: "loopdesk_checkout_intent_id", value: checkout.id }, { key: "megaska_discount_snapshot", value: JSON.stringify(checkout.discounts || []) },
      ...(storeCreditAmountPaise > 0 ? [{ key: "store_credit_applied", value: "true" }, { key: "store_credit_amount", value: String(storeCreditAmountPaise) }, { key: "wallet_reservation_id", value: storeCreditReservation?.id || "" }] : []),
    ];
    let draft = prepared.existingLink?.draftOrderId ? { id: prepared.existingLink.draftOrderId, name: prepared.existingLink.draftOrderName || null } : cod.shopifyDraftOrderId ? { id: cod.shopifyDraftOrderId, name: null } : null;
    if (draft) await audit(deps, "partial_cod.draft_order.reused", "CodAdvanceIntent", cod.id, { shopId: input.shopId, draftOrderId: draft.id });
    if (!draft) {
      const draftOrderInput: JsonRecord = { lineItems, email: address.email || customer?.email || undefined, phone: address.phone || customer?.phoneE164 || undefined, shippingAddress, billingAddress: shippingAddress, note: `Megaska Express Checkout intent ${checkout.id} | Partial COD advance: ${paiseToAmount(cod.advanceAmountPaise)} | Remaining COD: ${paiseToAmount(cod.codBalanceAmountPaise)}`, tags: ["Megaska Express Checkout", "Partial COD"], customAttributes, shippingLine: checkout.shippingAmountPaise > 0 ? { title: "Shipping", price: paiseToAmount(checkout.shippingAmountPaise) } : undefined, appliedDiscount };
      const gid = customerGid(customer?.shopifyCustomerId); if (gid) draftOrderInput.customerId = gid;
      const created = await graphql(input.shopDomain, `mutation DraftOrderCreate($input: DraftOrderInput!) { draftOrderCreate(input: $input) { draftOrder { id name } userErrors { field message } } }`, { input: draftOrderInput }, { shopId: input.shopId });
      const result = created.draftOrderCreate; if (result?.userErrors?.length || !result?.draftOrder?.id) throw new PartialCodOrderFinalizationError(502, "PARTIAL_COD_DRAFT_ORDER_FAILED", userError(result?.userErrors));
      draft = result.draftOrder; await db.codAdvanceIntent.updateMany({ where: { id: cod.id, shopId: input.shopId, status: "ADVANCE_PAID", shopifyDraftOrderId: null }, data: { shopifyDraftOrderId: draft.id } }); await audit(deps, "partial_cod.draft_order.created", "CodAdvanceIntent", cod.id, { shopId: input.shopId, draftOrderId: draft.id });
    }
    const completed = await graphql(input.shopDomain, `mutation DraftOrderComplete($id: ID!, $paymentPending: Boolean) { draftOrderComplete(id: $id, paymentPending: $paymentPending) { draftOrder { id name order { id name displayFinancialStatus displayFulfillmentStatus statusUrl } } userErrors { field message } } }`, { id: draft.id, paymentPending: true }, { shopId: input.shopId });
    const order = completed.draftOrderComplete?.draftOrder?.order; if (completed.draftOrderComplete?.userErrors?.length || !order?.id) throw new PartialCodOrderFinalizationError(502, "PARTIAL_COD_ORDER_COMPLETION_FAILED", userError(completed.draftOrderComplete?.userErrors));
    const persisted = await db.$transaction(async (tx: any) => { const existing = await tx.expressCheckoutOrderLink.findFirst({ where: { shopId: input.shopId, intentId: input.checkoutIntentId } }); const data = { draftOrderId: completed.draftOrderComplete.draftOrder.id || draft.id, draftOrderName: completed.draftOrderComplete.draftOrder.name || draft.name || null, shopifyOrderId: order.id, shopifyOrderName: order.name || null, financialStatus: order.displayFinancialStatus || "PENDING", fulfillmentStatus: order.displayFulfillmentStatus || null }; const link = existing?.id ? await tx.expressCheckoutOrderLink.update({ where: { id: existing.id }, data }) : await tx.expressCheckoutOrderLink.create({ data: { shopId: input.shopId, intentId: input.checkoutIntentId, ...data } }); await tx.expressCheckoutIntent.update({ where: { id: input.checkoutIntentId }, data: { status: "ORDER_COMPLETED" } }); const updated = await tx.codAdvanceIntent.updateMany({ where: { id: cod.id, shopId: input.shopId, expressCheckoutIntentId: input.checkoutIntentId, status: "ADVANCE_PAID", verifiedAt: { not: null }, paidAt: { not: null }, consumedAt: null }, data: { status: "ORDER_LINKED", shopifyDraftOrderId: data.draftOrderId, shopifyOrderId: order.id, shopifyOrderName: order.name || null, consumedAt: deps.now?.() || new Date() } }); if (updated.count !== 1) throw new PartialCodOrderFinalizationError(503, "PARTIAL_COD_RECONCILIATION_REQUIRED", "Could not link COD advance to order"); return link; });
    await audit(deps, "partial_cod.shopify_order.created", "CodAdvanceIntent", cod.id, { shopId: input.shopId, checkoutIntentId: input.checkoutIntentId, shopifyOrderName: order.name || null });
    if (storeCreditAmountPaise > 0) { await (deps.consumeStoreCredit || (await import("../express-checkout/store-credit.ts")).consumeStoreCreditReservationForOrder)({ shopId: input.shopId, customerProfileId: input.customerProfileId, checkoutIntentId: input.checkoutIntentId, shopifyOrderId: order.id, orderNumber: order.name || null }); await audit(deps, "partial_cod.store_credit.consumed", "CodAdvanceIntent", cod.id, { shopId: input.shopId, amountPaise: storeCreditAmountPaise }); }
    await audit(deps, "partial_cod.intent.order_linked", "CodAdvanceIntent", cod.id, { shopId: input.shopId, checkoutIntentId: input.checkoutIntentId }); await audit(deps, "partial_cod.order.finalization_completed", "ExpressCheckoutIntent", input.checkoutIntentId, { shopId: input.shopId });
    return success({ reused: false, intentId: input.checkoutIntentId, link: persisted, order, cod });
  } catch (error) {
    const status = error instanceof PartialCodOrderFinalizationError ? error.status : (error && typeof error === "object" && "status" in error ? Number((error as any).status) as 503 : 502); const code = error instanceof PartialCodOrderFinalizationError ? error.code : "PARTIAL_COD_RECONCILIATION_REQUIRED";
    await audit(deps, status === 503 ? "partial_cod.order.reconciliation_required" : "partial_cod.order.finalization_failed", "CodAdvanceIntent", cod.id, { shopId: input.shopId, checkoutIntentId: input.checkoutIntentId, code });
    throw error instanceof PartialCodOrderFinalizationError ? error : new PartialCodOrderFinalizationError(status as 502 | 503, code, error instanceof Error ? error.message : "Partial COD order finalization failed");
  }
}
