/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";
import assert from "node:assert/strict";
import { finalizePartialCodExpressCheckoutOrder, PartialCodOrderFinalizationError } from "./order-finalization.ts";

const now = new Date("2026-07-13T00:00:00Z");
function base() {
  const state: any = { audits: [], createdDrafts: 0, completedDrafts: 0, consumed: 0 };
  const checkout: any = { id: "ci_1", shopId: "shop_1", customerProfileId: "cust_1", status: "PAYMENT_PENDING", selectedPaymentMethod: "COD", cartSnapshot: { lineItems: [{ variantId: "111", quantity: 2 }] }, subtotalAmountPaise: 100000, discountAmountPaise: 10000, shippingAmountPaise: 5000, codFeeAmountPaise: 0, totalAmountPaise: 95000, currency: "INR", discounts: [{ code: "SAVE" }], orderLink: null };
  const cod: any = { id: "cod_1", shopId: "shop_1", customerProfileId: "cust_1", expressCheckoutIntentId: "ci_1", status: "ADVANCE_PAID", orderAmountPaise: 95000, merchandiseAmountPaise: 100000, shopifyDiscountAmountPaise: 10000, shippingAmountPaise: 5000, codFeeAmountPaise: 0, storeCreditAppliedPaise: 5000, customerCashLiabilityPaise: 90000, advanceAmountPaise: 12000, codBalanceAmountPaise: 78000, currency: "INR", pricingFingerprint: "fp", settingsVersion: 3, paidAt: now, verifiedAt: now, razorpayPaymentId: "pay_1", providerReferenceId: "order_1", consumedAt: null, shopifyDraftOrderId: null, shopifyOrderId: null, shopifyOrderName: null };
  const payment: any = { id: "p_1", status: "CONFIRMED", method: "COD", purpose: "COD_ADVANCE", amountPaise: 12000, providerAmountPaise: 12000, currency: "INR", providerCurrency: "INR", razorpayOrderId: "order_1", razorpayPaymentId: "pay_1", verifiedAt: now };
  let link: any = null;
  const delegates = {
    expressCheckoutIntent: { findFirst: async ({ where }: any) => where.id === checkout.id && where.shopId === checkout.shopId && where.customerProfileId === checkout.customerProfileId ? { ...checkout, orderLink: link } : null, update: async ({ data }: any) => Object.assign(checkout, data) },
    codAdvanceIntent: { findFirst: async ({ where }: any) => where.id === cod.id && where.shopId === cod.shopId && where.customerProfileId === cod.customerProfileId ? cod : null, updateMany: async ({ data }: any) => { Object.assign(cod, data); return { count: state.codUpdateCount ?? 1 }; } },
    expressCheckoutPayment: { findFirst: async ({ where }: any) => payment.status === where.status && payment.method === where.method && payment.purpose === where.purpose && payment.razorpayPaymentId === where.razorpayPaymentId && (!where.razorpayOrderId || payment.razorpayOrderId === where.razorpayOrderId) ? payment : null },
    expressCheckoutOrderLink: { findFirst: async () => link, create: async ({ data }: any) => (link = { id: "link_1", ...data }), update: async ({ data }: any) => Object.assign(link, data) },
    customerProfile: { findFirst: async () => ({ id: "cust_1", email: "c@example.com", phoneE164: "+919999999999", shopifyCustomerId: "123" }) },
    expressCheckoutAddressSnapshot: { findFirst: async () => ({ name: "Ada Lovelace", phone: "+919999999999", email: "c@example.com", address1: "One", city: "Kochi", province: "Kerala", country: "India", zip: "682001" }) },
  };
  const db: any = { ...delegates, $transaction: async (fn: any) => fn({ ...delegates, $executeRaw: async () => undefined }) };
  const deps: any = { db, now: () => now, resolvePolicy: async () => ({ requiresAdvance: true, codAdvanceIntentId: "cod_1", pricingFingerprint: "fp", settingsVersion: 3, currency: "INR" }), getStoreCreditReservation: async () => ({ id: "res_1", reservedAmount: 5000 }), consumeStoreCredit: async () => { state.consumed++; }, audit: async (e: string) => { state.audits.push(e); }, graphql: async (_shop: string, query: string, variables: any) => { if (query.includes("DraftOrderCreate")) { state.createdDrafts++; state.draftInput = variables.input; return { draftOrderCreate: { draftOrder: { id: "draft_1", name: "D1" }, userErrors: [] } }; } state.completedDrafts++; return { draftOrderComplete: { draftOrder: { id: variables.id, name: "D1", order: { id: "order_1", name: "#1001", displayFinancialStatus: "PENDING", displayFulfillmentStatus: null, statusUrl: "https://x/order" } }, userErrors: [] } }; } };
  return { state, checkout, cod, payment, deps, get link() { return link; }, setLink(v: any) { link = v; checkout.orderLink = v; } };
}

test("finalizes verified Partial COD and preserves full Shopify pricing concepts", async () => { const h = base(); const result = await finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "test.myshopify.com", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, h.deps); assert.equal(result.ok, true); assert.equal(result.payment.mode, "PARTIAL_COD"); assert.equal(result.payment.advancePaidPaise, 12000); assert.equal(result.payment.codBalanceAmountPaise, 78000); assert.equal(h.state.createdDrafts, 1); assert.equal(h.state.completedDrafts, 1); assert.equal(h.state.consumed, 1); assert.equal(h.state.draftInput.appliedDiscount.value, 100); assert.equal(h.state.draftInput.customAttributes.some((a: any) => a.key === "loopdesk_cod_balance" && a.value === "78000"), true); assert.equal(h.cod.status, "ORDER_LINKED"); assert.equal(h.cod.consumedAt, now); assert.equal(h.payment.status, "CONFIRMED"); });

test("rejects wrong shop/customer/prepaid/normal COD and missing verified payment state", async () => { const cases: Array<[string, (h: ReturnType<typeof base>) => void, string]> = [["wrong shop", () => undefined, "CHECKOUT_NOT_ELIGIBLE"], ["wrong customer", () => undefined, "CHECKOUT_NOT_ELIGIBLE"], ["prepaid", h => { h.checkout.selectedPaymentMethod = "PREPAID"; }, "CHECKOUT_NOT_ELIGIBLE"], ["normal cod", h => { h.deps.resolvePolicy = async () => ({ requiresAdvance: false }); }, "CHECKOUT_NOT_ELIGIBLE"], ["not paid", h => { h.cod.status = "PAYMENT_PENDING"; }, "PARTIAL_COD_NOT_VERIFIED"]]; for (const [name, patch, code] of cases) { const h = base(); patch(h); const input = { shopId: name === "wrong shop" ? "other" : "shop_1", shopDomain: "test.myshopify.com", checkoutIntentId: "ci_1", customerProfileId: name === "wrong customer" ? "other" : "cust_1" }; await assert.rejects(() => finalizePartialCodExpressCheckoutOrder(input, h.deps), (e: any) => e instanceof PartialCodOrderFinalizationError && e.code === code); } });

test("rejects payment and pricing mismatches with stable codes", async () => { for (const patch of [(h: any) => { h.payment.razorpayPaymentId = "other"; }, (h: any) => { h.payment.amountPaise = 1; }, (h: any) => { h.payment.providerAmountPaise = 1; }, (h: any) => { h.payment.currency = "USD"; }]) { const h = base(); patch(h); await assert.rejects(() => finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, h.deps), (e: any) => e.code === "PARTIAL_COD_PAYMENT_MISMATCH"); } for (const patch of [(h: any) => { h.cod.storeCreditAppliedPaise = 1; }, (h: any) => { h.cod.pricingFingerprint = "other"; }, (h: any) => { h.cod.settingsVersion = 2; }, (h: any) => { h.cod.codBalanceAmountPaise = 1; }, (h: any) => { h.cod.advanceAmountPaise = 999999; }]) { const h = base(); patch(h); await assert.rejects(() => finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, h.deps), (e: any) => e.code === "PARTIAL_COD_PRICING_CHANGED" || e.code === "PARTIAL_COD_PAYMENT_MISMATCH"); } });

test("idempotent replay returns existing matching order and existing draft resumes", async () => { const linked = base(); linked.cod.status = "ORDER_LINKED"; linked.cod.shopifyOrderId = "order_1"; linked.setLink({ id: "link_1", shopifyOrderId: "order_1", shopifyOrderName: "#1001", financialStatus: "PENDING" }); const reused = await finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, linked.deps); assert.equal(reused.reused, true); assert.equal(linked.state.createdDrafts, 0); const draft = base(); draft.cod.shopifyDraftOrderId = "draft_1"; await finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, draft.deps); assert.equal(draft.state.createdDrafts, 0); assert.equal(draft.state.completedDrafts, 1); });

test("failure recovery preserves paid advance and draft id before retry", async () => { const createFail = base(); createFail.deps.graphql = async () => ({ draftOrderCreate: { draftOrder: null, userErrors: [{ message: "no" }] } }); await assert.rejects(() => finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, createFail.deps), (e: any) => e.code === "PARTIAL_COD_DRAFT_ORDER_FAILED"); assert.equal(createFail.cod.status, "ADVANCE_PAID"); const completeFail = base(); completeFail.deps.graphql = async (_s: string, query: string, variables: any) => query.includes("DraftOrderCreate") ? { draftOrderCreate: { draftOrder: { id: "draft_1", name: "D1" }, userErrors: [] } } : { draftOrderComplete: { draftOrder: { id: variables.id, name: "D1", order: null }, userErrors: [{ message: "no" }] } }; await assert.rejects(() => finalizePartialCodExpressCheckoutOrder({ shopId: "shop_1", shopDomain: "x", checkoutIntentId: "ci_1", customerProfileId: "cust_1" }, completeFail.deps), (e: any) => e.code === "PARTIAL_COD_ORDER_COMPLETION_FAILED"); assert.equal(completeFail.cod.status, "ADVANCE_PAID"); assert.equal(completeFail.cod.shopifyDraftOrderId, "draft_1"); });
