/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "../../db/prisma.ts";
import { getRequestWindowExpiresAt, isWithinRequestWindow, parseTrustedDeliveryDate } from "../../exchange/deadlines.ts";
import { findActiveRequest, orderNumberVariants } from "../../exchange/request-interlocks.ts";
import { CustomerDashboardActionError } from "./errors.ts";
import type { CustomerDashboardActionContext } from "./context.ts";
import type { CustomerOwnedOrderSnapshot } from "./ownership.ts";
import type { IssueActionPayload } from "./contract.ts";
import { ISSUE_REASON_OPTIONS } from "./issue-reasons.ts";
import { loadExchangeOrderLines, type ExchangeOrderLine } from "./exchange-domain.ts";

export type IssueValidation = { lines: ExchangeOrderLine[]; selected: Array<{ payload: IssueActionPayload["lineItems"][number]; line: ExchangeOrderLine }>; deadlineAt: string | null; deliveredAt: Date };
type Deps={ findRequests:(a:unknown)=>Promise<any[]>; createRequest:(a:unknown)=>Promise<any>; };
const def:Deps={findRequests:(a)=>prisma.orderActionRequest.findMany(a as never),createRequest:(a)=>prisma.orderActionRequest.create(a as never)};
let deps=def; export function setIssueDomainDependenciesForTest(o:Partial<Deps>){deps={...def,...o};} export function resetIssueDomainDependenciesForTest(){deps=def;}
export const ISSUE_ATTACHMENTS_SUPPORTED=false;
export function issueFormOptions(){return ISSUE_REASON_OPTIONS.map(o=>({code:o.value,label:o.label,requiresDescription:o.requiresDescription}));}
export async function validateIssueRequest(input:{context:CustomerDashboardActionContext;order:CustomerOwnedOrderSnapshot;payload?:IssueActionPayload}):Promise<IssueValidation>{const delivered=parseTrustedDeliveryDate(input.order.deliveredAt); const deadline=getRequestWindowExpiresAt(delivered); if(!delivered) throw new CustomerDashboardActionError({code:"ACTION_NOT_AVAILABLE",message:"Issue can be reported only after delivery.",status:409}); if(!isWithinRequestWindow(delivered,input.context.now)) throw new CustomerDashboardActionError({code:"ACTION_NOT_AVAILABLE",message:"Issue reporting is allowed within 2 days of delivery.",status:409}); const active=findActiveRequest(await deps.findRequests({where:{shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,requestType:{in:["CANCELLATION","EXCHANGE","ISSUE"]},orderNumber:{in:orderNumberVariants(input.order.orderNumber)}},select:{id:true,requestType:true,status:true},orderBy:{requestedAt:"desc"}})); if(active) throw new CustomerDashboardActionError({code:active.requestType==="ISSUE"?"REQUEST_ALREADY_EXISTS":"REQUEST_CONFLICT",message:active.requestType==="ISSUE"?"An active issue request already exists for this order.":"Another request is already in progress for this order.",status:409}); const lines=await loadExchangeOrderLines({context:input.context,order:input.order}); if(!lines.length) throw new CustomerDashboardActionError({code:"ACTION_NOT_AVAILABLE",message:"No delivered line items are available for issue reporting.",status:409}); if(!input.payload) return {lines,selected:[],deadlineAt:deadline?.toISOString()||null,deliveredAt:delivered}; if((input.payload.attachments||[]).length) throw new CustomerDashboardActionError({code:"INVALID_INPUT",message:"Evidence upload is not supported yet. Submit without attachments.",status:400,fieldErrors:{attachments:"Evidence upload is not supported yet."}}); const byId=new Map(lines.map(l=>[l.id,l])); const selected=[] as IssueValidation["selected"]; for(const item of input.payload.lineItems){const line=byId.get(item.lineItemId); if(!line) throw new CustomerDashboardActionError({code:"INVALID_INPUT",message:"Please check the selected items.",status:400,fieldErrors:{lineItems:"Selected item is not part of this order."}}); if(item.quantity>line.quantity) throw new CustomerDashboardActionError({code:"INVALID_INPUT",message:"Please check the selected quantity.",status:400,fieldErrors:{[`${item.lineItemId}.quantity`]:"Quantity exceeds delivered quantity."}}); selected.push({payload:item,line});} return {lines,selected,deadlineAt:deadline?.toISOString()||null,deliveredAt:delivered};}
export async function createIssueRequest(input:{context:CustomerDashboardActionContext;order:CustomerOwnedOrderSnapshot;payload:IssueActionPayload;validation:IssueValidation}){return deps.createRequest({data:{shopId:input.context.shopId,requestType:"ISSUE",customerProfileId:input.context.customerProfileId,shopifyOrderId:input.order.shopifyOrderId,orderNumber:input.order.orderNumber,status:"OPEN",reason:input.payload.issueType,customerNote:input.payload.description,orderAmountSnapshot:String(input.order.totalPaise||0),deliveryDateSnapshot:input.validation.deliveredAt,eligibilityDecision:"ELIGIBLE",eligibilityReason:"Eligible for issue review",megaskaOrderId:input.order.id,items:{create:input.validation.selected.map(s=>({shopifyLineItemId:s.line.id,productTitle:s.line.title,variantTitle:s.line.variantTitle,sku:s.line.sku,currentSize:s.line.variantTitle,requestedSize:"N/A",quantity:s.payload.quantity,isClearance:false,isExcludedCategory:false,eligibilitySnapshot:{issueCategory:input.payload.issueType,descriptionCaptured:true,declarations:{declaredUnused:true,declaredUnwashed:true,declaredTagsIntact:true},evidence:{imageEvidenceUrls:[],videoEvidenceUrls:[],attachmentsSupported:false},lineItemId:s.line.id}}))}},include:{items:true}});}
