# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "91b6af8eff2be76428980364cad07a57"
name = "LoopD2C"
application_url = "https://app.loopd2c.com"
embedded = true

[app_proxy]
url = "https://app.loopd2c.com/apps/loopd2c"
subpath = "loopd2c"
prefix = "apps"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/api/webhooks/orders/create"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://app.loopd2c.com/api/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_draft_orders,read_all_orders,read_app_proxy,read_customers,read_discounts,read_draft_orders,read_orders,read_products,unauthenticated_read_checkouts,unauthenticated_read_metaobjects,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_app_proxy,write_customers,write_discounts,write_draft_orders,write_metaobject_definitions,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app.loopd2c.com/api/auth/callback"
]
