import { createHash, randomBytes } from "node:crypto";
import { prisma } from "../db/prisma.ts";
import { normalizeReviewBody, normalizeReviewTitle } from "./review-content.ts";
import { recalculateProductReviewAggregate } from "./review-foundation.ts";
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const valid=(v:unknown)=>typeof v==="string"&&/^[A-Za-z0-9_-]{43,200}$/.test(v);
export function generateReviewEditToken(){const token=randomBytes(32).toString("base64url");return {token,tokenHash:hash(token)};}
export async function issueReviewEditToken(input:{shopId:string;reviewId:string;now?:Date;db?: typeof prisma}){const db=input.db??prisma,now=input.now??new Date();const review=await db.productReview.findFirst({where:{id:input.reviewId,shopId:input.shopId},select:{id:true}});if(!review)return null;const settings=await db.reviewSettings.findUnique({where:{shopId:input.shopId}});const {token,tokenHash}=generateReviewEditToken();await db.productReviewEditToken.updateMany({where:{shopId:input.shopId,productReviewId:review.id,revokedAt:null},data:{revokedAt:now}});await db.productReviewEditToken.create({data:{shopId:input.shopId,productReviewId:review.id,tokenHash,expiresAt:new Date(now.getTime()+(settings?.reviewEditWindowDays??30)*86400000)}});return token;}
export async function getReviewEditContext(input:{token:unknown;shopId:string;now?:Date;db?: typeof prisma}){const db=input.db??prisma,now=input.now??new Date();if(!valid(input.token))return {ok:false as const,errorCode:"EDIT_TOKEN_INVALID"};const row=await db.productReviewEditToken.findUnique({where:{tokenHash:hash(input.token as string)},include:{productReview:true}});if(!row||row.shopId!==input.shopId||row.revokedAt||row.expiresAt<=now)return {ok:false as const,errorCode:"EDIT_TOKEN_INVALID"};const r=row.productReview;return {ok:true as const,review:{rating:r.rating,title:r.title,body:r.body,version:r.editVersion,productTitle:r.productTitleSnapshot}};}
export async function submitReviewEdit(input:{token:unknown;shopId:string;rating:unknown;title:unknown;body:unknown;version:unknown;now?:Date;db?: typeof prisma}){const db=input.db??prisma,now=input.now??new Date(),context=await getReviewEditContext({token:input.token,shopId:input.shopId,now,db});if(!context.ok)return context;if(!Number.isInteger(input.rating)||(input.rating as number)<1||(input.rating as number)>5||!Number.isInteger(input.version))return {ok:false as const,errorCode:"EDIT_VALIDATION_FAILED"};const title=normalizeReviewTitle(input.title),body=normalizeReviewBody(input.body);if(title.error||body.error)return {ok:false as const,errorCode:"EDIT_VALIDATION_FAILED"};return db.$transaction(async(tx)=>{const token=await tx.productReviewEditToken.findUnique({where:{tokenHash:hash(input.token as string)}});const current=await tx.productReview.findFirst({where:{id:token.productReviewId,shopId:input.shopId}});if(!current||current.editVersion!==input.version)return {ok:false as const,errorCode:"EDIT_CONFLICT"};await tx.productReviewRevision.create({data:{shopId:input.shopId,productReviewId:current.id,previousRating:current.rating,previousTitle:current.title,previousBody:current.body,nextRating:input.rating,nextTitle:title.value,nextBody:body.value}});const status=current.status==="PUBLISHED"?"PENDING_MODERATION":current.status==="REJECTED"?"PENDING_MODERATION":current.status;await tx.productReview.update({where:{id:current.id},data:{rating:input.rating,title:title.value,body:body.value,status,publishedAt:status==="PUBLISHED"?current.publishedAt:null,editedAt:now,lastEditedAt:now,editCount:{increment:1},editVersion:{increment:1}}});await tx.productReviewEditToken.update({where:{id:token.id},data:{revokedAt:now}});if(current.status==="PUBLISHED")await recalculateProductReviewAggregate(input.shopId,current.shopifyProductId,tx);return {ok:true as const,status};});}
