import { prisma } from "../db/prisma.ts";
import { createHash } from "node:crypto";
import { getReviewEditContext } from "./review-editing.ts";
import { getReviewSettings } from "./review-settings.ts";
import { createReviewMediaStorageKey, createReviewMediaUploadTarget, reviewMediaPublicUrl } from "./review-media-storage.ts";
import { validateReviewMediaPolicy } from "./review-media-policy.ts";
export type ReviewMediaUploadError = "REVIEW_MEDIA_TOKEN_INVALID"|"REVIEW_MEDIA_UPLOAD_UNAVAILABLE"|"REVIEW_MEDIA_NOT_FOUND"|"REVIEW_MEDIA_ALREADY_FINALIZED"|"REVIEW_MEDIA_UPLOAD_INCOMPLETE"|"REVIEW_MEDIA_LIMIT_EXCEEDED"|"REVIEW_MEDIA_TYPE_UNSUPPORTED"|"REVIEW_MEDIA_TYPE_DISABLED"|"REVIEW_MEDIA_DISABLED"|"REVIEW_MEDIA_TOO_LARGE";
export async function createReviewMediaUpload(input:{shopId:string;token:unknown;fileName:unknown;mimeType:unknown;sizeBytes:unknown;db?:typeof prisma}) { const db=input.db??prisma; const context=await getReviewEditContext({shopId:input.shopId,token:input.token,db});if(!context.ok)return {ok:false as const,errorCode:"REVIEW_MEDIA_TOKEN_INVALID" as const}; const tokenRow=await db.productReviewEditToken.findFirst({where:{shopId:input.shopId,tokenHash:createHash("sha256").update(input.token as string).digest("hex")}});if(!tokenRow)return {ok:false as const,errorCode:"REVIEW_MEDIA_TOKEN_INVALID" as const};const existing=await db.productReviewMedia.findMany({where:{shopId:input.shopId,productReviewId:tokenRow.productReviewId,deletedAt:null},select:{mediaType:true}});const settings=await getReviewSettings(input.shopId,db);const policy=validateReviewMediaPolicy(settings,{fileName:input.fileName,mimeType:input.mimeType,sizeBytes:input.sizeBytes,existingItems:existing.length,existingPhotos:existing.filter(x=>x.mediaType==="IMAGE").length,existingVideos:existing.filter(x=>x.mediaType==="VIDEO").length});if(!policy.ok)return policy;const key=createReviewMediaStorageKey(input.shopId,tokenRow.productReviewId,input.fileName as string),target=createReviewMediaUploadTarget(key,input.mimeType as string);if(!target)return {ok:false as const,errorCode:"REVIEW_MEDIA_UPLOAD_UNAVAILABLE" as const};const media=await db.productReviewMedia.create({data:{shopId:input.shopId,productReviewId:tokenRow.productReviewId,mediaType:policy.type,storageProvider:"configured-direct-upload",storageKey:key,mimeType:input.mimeType as string,sizeBytes:input.sizeBytes as number,sortOrder:existing.length,status:"UPLOADING"}});return {ok:true as const,mediaId:media.id,upload:target}; }
export async function finalizeReviewMediaUpload(input:{shopId:string;token:unknown;mediaId:unknown;db?:typeof prisma}) { const db=input.db??prisma; const context=await getReviewEditContext({shopId:input.shopId,token:input.token,db});if(!context.ok)return {ok:false as const,errorCode:"REVIEW_MEDIA_TOKEN_INVALID" as const};if(typeof input.mediaId!=="string")return {ok:false as const,errorCode:"REVIEW_MEDIA_NOT_FOUND" as const};const media=await db.productReviewMedia.findFirst({where:{id:input.mediaId,shopId:input.shopId,deletedAt:null}});if(!media)return {ok:false as const,errorCode:"REVIEW_MEDIA_NOT_FOUND" as const};if(media.status!=="UPLOADING")return {ok:false as const,errorCode:"REVIEW_MEDIA_ALREADY_FINALIZED" as const};const url=reviewMediaPublicUrl(media.storageKey);if(!url)return {ok:false as const,errorCode:"REVIEW_MEDIA_UPLOAD_INCOMPLETE" as const};await db.productReviewMedia.update({where:{id:media.id},data:{status:"READY",approved:true,publicUrl:url}});return {ok:true as const}; }
