import { createHash, randomBytes } from "node:crypto";
import { prisma } from "../db/prisma.ts";
export const REVIEW_TOKEN_BYTES = 32, REVIEW_TOKEN_TTL_DAYS = 30;
const maxTokenLength = 200;
export function reviewTokenTtlDays(value = process.env.REVIEW_TOKEN_TTL_DAYS): number { const n = Number(value); return Number.isInteger(n) && n >= 1 && n <= 90 ? n : REVIEW_TOKEN_TTL_DAYS; }
export function hashReviewToken(token: string): string { return createHash("sha256").update(token).digest("hex"); }
export function generateReviewToken(now = new Date()): { plaintextToken: string; tokenHash: string; expiresAt: Date } { const plaintextToken = randomBytes(REVIEW_TOKEN_BYTES).toString("base64url"); return { plaintextToken, tokenHash: hashReviewToken(plaintextToken), expiresAt: new Date(now.getTime() + reviewTokenTtlDays() * 86400000) }; }
export function normalizeReviewToken(value: unknown): string | null { if (typeof value !== "string" || value.length < 43 || value.length > maxTokenLength || !/^[A-Za-z0-9_-]+$/.test(value)) return null; return value; }
export async function findReviewRequestByToken(token: unknown, options: { now?: Date; db?: typeof prisma } = {}) { const normalized = normalizeReviewToken(token); if (!normalized) return { ok: false as const, errorCode: "REVIEW_TOKEN_INVALID" }; const now = options.now ?? new Date(); const row = await (options.db ?? prisma).reviewRequest.findUnique({ where: { tokenHash: hashReviewToken(normalized) }, select: { id: true, shopId: true, status: true, tokenExpiresAt: true, completedAt: true, canceledAt: true } }); if (!row) return { ok: false as const, errorCode: "REVIEW_TOKEN_INVALID" }; if (!row.tokenExpiresAt || row.tokenExpiresAt <= now) return { ok: false as const, errorCode: "REVIEW_TOKEN_EXPIRED" }; if (row.completedAt || row.canceledAt || !["SENT", "REMINDER_SENT"].includes(row.status)) return { ok: false as const, errorCode: "REVIEW_TOKEN_REQUEST_INACTIVE" }; return { ok: true as const, reviewRequest: { id: row.id, shopId: row.shopId, status: row.status, tokenExpiresAt: row.tokenExpiresAt } }; }
