import { prisma } from "../db/prisma.ts";
import { isReviewSort, type ReviewSort } from "./review-sort.ts";

export type { ReviewSort } from "./review-sort.ts";
export type PublicProductReview = { id:string; rating:number; title:string|null; body:string|null; customerDisplayName:string; verifiedPurchase:boolean; productTitleSnapshot:string; variantTitleSnapshot:string|null; createdAt:Date; publishedAt:Date|null; merchantReply?:{body:string;authorLabel:string;createdAt:Date;updatedAt:Date}|null };
export type ProductReviewSummary = { averageRating:number; reviewCount:number; rating1Count:number; rating2Count:number; rating3Count:number; rating4Count:number; rating5Count:number };
type Db={productReview:{findMany(args:unknown):Promise<PublicProductReview[]>;count(args:unknown):Promise<number>};productReviewAggregate:{findUnique(args:unknown):Promise<{averageRating:unknown;publishedCount:number;rating1Count:number;rating2Count:number;rating3Count:number;rating4Count:number;rating5Count:number}|null>}};
const select={id:true,rating:true,title:true,body:true,customerDisplayName:true,verifiedPurchase:true,productTitleSnapshot:true,variantTitleSnapshot:true,createdAt:true,publishedAt:true,merchantReply:{select:{body:true,authorLabel:true,createdAt:true,updatedAt:true}}};
const zeroSummary=():ProductReviewSummary=>({averageRating:0,reviewCount:0,rating1Count:0,rating2Count:0,rating3Count:0,rating4Count:0,rating5Count:0});
export function normalizeShopifyProductId(value:unknown):string|null { if(typeof value!=="string"&&typeof value!=="number")return null; const raw=String(value).trim(); if(/^\d+$/.test(raw)&&Number(raw)>0)return raw; const match=/^gid:\/\/shopify\/Product\/(\d+)$/.exec(raw); return match&&Number(match[1])>0?match[1]:null; }
export function normalizeStorefrontPage(value:unknown, fallback=1){return typeof value==="number"&&Number.isInteger(value)&&value>=1?value:fallback}
export function normalizeStorefrontPageSize(value:unknown, fallback=10){return typeof value==="number"&&Number.isInteger(value)&&value>=1&&value<=25?value:fallback}
export { isReviewSort };
export async function getPublishedProductReviews({shopId,shopifyProductId,page=1,pageSize=10,sort="NEWEST",db=prisma as unknown as Db}:{shopId:string;shopifyProductId:string;page?:number;pageSize?:number;sort?:ReviewSort;db?:Db}) { const current=Math.max(1,Math.floor(page)),take=Math.min(25,Math.max(1,Math.floor(pageSize))); const where={shopId,shopifyProductId,status:"PUBLISHED" as const,deletedAt:null}; const orderBy=sort==="HIGHEST_RATING"?[{rating:"desc"},{publishedAt:"desc"},{id:"desc"}]:sort==="LOWEST_RATING"?[{rating:"asc"},{publishedAt:"desc"},{id:"desc"}]:[{publishedAt:"desc"},{createdAt:"desc"},{id:"desc"}]; const [items,totalCount,aggregate]=await Promise.all([db.productReview.findMany({where,select,orderBy,skip:(current-1)*take,take}),db.productReview.count({where}),db.productReviewAggregate.findUnique({where:{shopId_shopifyProductId:{shopId,shopifyProductId}}})]); const summary=aggregate?{averageRating:Number(aggregate.averageRating),reviewCount:aggregate.publishedCount,rating1Count:aggregate.rating1Count,rating2Count:aggregate.rating2Count,rating3Count:aggregate.rating3Count,rating4Count:aggregate.rating4Count,rating5Count:aggregate.rating5Count}:zeroSummary(); const totalPages=Math.ceil(totalCount/take); return {items,summary,page:current,pageSize:take,totalCount,totalPages,hasNextPage:current<totalPages,hasPreviousPage:current>1}; }
