import { prisma } from "../db/prisma.ts";
import { recalculateProductReviewAggregate } from "./review-foundation.ts";
import { normalizeReviewBody, normalizeReviewTitle } from "./review-content.ts";
import { validateReviewEditToken, type ReviewEditTokenErrorCode } from "./review-edit-token.ts";

/* eslint-disable @typescript-eslint/no-explicit-any -- domain services support narrow transaction fakes. */
type Db = any;
export type ReviewEditErrorCode = ReviewEditTokenErrorCode | "REVIEW_EDIT_VALIDATION_FAILED" | "REVIEW_INVALID_STATUS" | "REVIEW_EDIT_CONFLICT";
export type EditableReviewResult = {ok:true;review:{rating:number;title:string|null;body:string|null;productTitleSnapshot:string;variantTitleSnapshot:string|null;productImageUrlSnapshot:string|null;customerDisplayName:string;verifiedPurchase:boolean;currentStatus:string;createdAt:Date;lastEditedAt:Date|null;editDeadline:Date;editCount:number;updatedAt:Date}}|{ok:false;errorCode:ReviewEditErrorCode};
export async function getEditableReviewByToken({shopId,token,now=new Date(),db=prisma}:{shopId:string;token:unknown;now?:Date;db?:Db}):Promise<EditableReviewResult>{const found=await validateReviewEditToken({shopId,token,now,db});if(!found.ok)return found;const r=found.review;const request=await db.reviewRequest.findUnique({where:{id:r.reviewRequestId},select:{productImageUrlSnapshot:true}});await db.productReviewEditToken.update({where:{id:found.tokenRecord.id},data:{usedAt:now,useCount:{increment:1}}});return {ok:true,review:{rating:r.rating,title:r.title,body:r.body,productTitleSnapshot:r.productTitleSnapshot,variantTitleSnapshot:r.variantTitleSnapshot,productImageUrlSnapshot:request?.productImageUrlSnapshot??null,customerDisplayName:r.customerDisplayName,verifiedPurchase:r.verifiedPurchase,currentStatus:r.status,createdAt:r.createdAt,lastEditedAt:r.lastEditedAt,editDeadline:found.editDeadline,editCount:r.editCount,updatedAt:r.updatedAt}};}
export async function editCustomerReview({shopId,editToken,rating,title,body,expectedUpdatedAt,now=new Date(),db=prisma}:{shopId:string;editToken:unknown;rating:unknown;title?:unknown;body?:unknown;expectedUpdatedAt?:unknown;now?:Date;db?:Db}) {const found=await validateReviewEditToken({shopId,token:editToken,now,db});if(!found.ok)return found;const min=found.settings.minimumRating,max=found.settings.maximumRating;if(typeof rating!=="number"||!Number.isInteger(rating)||rating<min||rating>max)return {ok:false as const,errorCode:"REVIEW_EDIT_VALIDATION_FAILED" as const,fieldErrors:{rating:`Choose a rating from ${min} to ${max}.`}};const normalizedTitle=normalizeReviewTitle(title),normalizedBody=normalizeReviewBody(body);if(normalizedTitle.error||normalizedBody.error)return {ok:false as const,errorCode:"REVIEW_EDIT_VALIDATION_FAILED" as const,fieldErrors:{...(normalizedTitle.error?{title:normalizedTitle.error}:{}),...(normalizedBody.error?{body:normalizedBody.error}:{})}};return db.$transaction(async(tx:Db)=>{const r=await tx.productReview.findFirst({where:{id:found.review.id,shopId},select:{id:true,shopId:true,shopifyProductId:true,status:true,rating:true,title:true,body:true,publishedAt:true,rejectionReason:true,createdAt:true,updatedAt:true}});if(!r)return {ok:false as const,errorCode:"REVIEW_NOT_FOUND" as const};if(typeof expectedUpdatedAt!=="string"||new Date(expectedUpdatedAt).getTime()!==r.updatedAt.getTime())return {ok:false as const,errorCode:"REVIEW_EDIT_CONFLICT" as const};if(!["PUBLISHED","PENDING_MODERATION","REJECTED"].includes(r.status))return {ok:false as const,errorCode:"REVIEW_INVALID_STATUS" as const};const next=r.status==="PUBLISHED"&& !found.settings.requireRemoderationAfterEdit ? "PUBLISHED" : "PENDING_MODERATION";const update=await tx.productReview.update({where:{id:r.id},data:{rating,title:normalizedTitle.value,body:normalizedBody.value,status:next,publishedAt:next==="PUBLISHED"?r.publishedAt:null,rejectionReason:r.status==="REJECTED"?null:r.rejectionReason,lastEditedAt:now,editedAt:now,lastEditedBy:"CUSTOMER_EDIT_TOKEN",editCount:{increment:1}},select:{rating:true,title:true,body:true,status:true,lastEditedAt:true,updatedAt:true}});await tx.productReviewRevision.create({data:{shopId,reviewId:r.id,previousRating:r.rating,previousTitle:r.title,previousBody:r.body,newRating:rating,newTitle:normalizedTitle.value,newBody:normalizedBody.value,previousStatus:r.status,newStatus:next,editSource:"CUSTOMER_EDIT_TOKEN"}});if(r.status==="PUBLISHED"&&next!=="PUBLISHED")await recalculateProductReviewAggregate(shopId,r.shopifyProductId,tx);return {ok:true as const,review:{...update,editDeadline:found.editDeadline}};});}
