import { prisma } from "../db/prisma";
import { comparison, type AnalyticsRange } from "./review-analytics-date-range";
import type { SnapshotMetric } from "./review-analytics-definitions";
const range=(field:"submittedAt"|"publishedAt"|"rejectedAt",r:AnalyticsRange)=>({[field]:{gte:r.start,lte:r.end}});
const previous=(field:"submittedAt"|"publishedAt"|"rejectedAt",r:AnalyticsRange)=>({[field]:{gte:r.comparisonStart,lte:r.comparisonEnd}});
const count=async(shopId:string,where:object)=>prisma.productReview.count({where:{shopId,deletedAt:null,...where}});
export async function overview(shopId:string,r:AnalyticsRange){
 const [submitted,submittedPrev,published,publishedPrev,rejected,rejectedPrev,current,pending,avg,media,failed,failedPrev,replied]=await Promise.all([
 count(shopId,range("submittedAt",r)),count(shopId,previous("submittedAt",r)),count(shopId,range("publishedAt",r)),count(shopId,previous("publishedAt",r)),count(shopId,range("rejectedAt",r)),count(shopId,previous("rejectedAt",r)),count(shopId,{status:"PUBLISHED"}),count(shopId,{status:"PENDING_MODERATION"}),prisma.productReview.aggregate({where:{shopId,status:"PUBLISHED",deletedAt:null},_avg:{rating:true}}),prisma.productReview.count({where:{shopId,deletedAt:null,submittedAt:{gte:r.start,lte:r.end},media:{some:{deletedAt:null}}}}),prisma.productReviewRequestDeliveryAttempt.count({where:{shopId,status:"FAILED_PERMANENT",attemptType:"INITIAL",completedAt:{gte:r.start,lte:r.end}}}),prisma.productReviewRequestDeliveryAttempt.count({where:{shopId,status:"FAILED_PERMANENT",attemptType:"INITIAL",completedAt:{gte:r.comparisonStart,lte:r.comparisonEnd}}}),prisma.productReviewMerchantReply.count({where:{shopId,productReview:{status:"PUBLISHED",deletedAt:null}}})]);
 const outcome=published+rejected, outcomePrev=publishedPrev+rejectedPrev; const asOf=new Date().toISOString();
 return {range:serialize(r),metrics:{reviewsSubmitted:comparison(submitted,submittedPrev),currentPublishedAverageRating:snapshot(avg._avg.rating??0,asOf),requestConversionRate:comparison(0,0),pendingModeration:snapshot(pending,asOf),publicationRate:comparison(outcome?published/outcome:0,outcomePrev?publishedPrev/outcomePrev:0),mediaReviewRate:comparison(submitted?media/submitted:0,0),merchantReplyCoverage:snapshot(current?replied/current:0,asOf),failedNotifications:comparison(failed,failedPrev)},reviewVolumeSeries:[{bucketStart:r.start.toISOString(),submitted,published,rejected}],snapshots:{currentlyPublished:current}};
}
function snapshot(value:number,asOf:string):SnapshotMetric{return {value:Number(value),asOf}}
export async function ratings(shopId:string,r:AnalyticsRange){const [submitted,current,groups]=await Promise.all([prisma.productReview.aggregate({where:{shopId,deletedAt:null,...range("submittedAt",r)},_avg:{rating:true}}),prisma.productReview.aggregate({where:{shopId,status:"PUBLISHED",deletedAt:null},_avg:{rating:true}}),prisma.productReview.groupBy({by:["rating"],where:{shopId,deletedAt:null,...range("submittedAt",r)},_count:{_all:true}})]);const total=groups.reduce((n,g)=>n+g._count._all,0);return {range:serialize(r),submittedAverageRating:submitted._avg.rating??0,currentPublishedAverageRating:current._avg.rating??0,distribution:[1,2,3,4,5].map(rating=>{const value=groups.find(g=>g.rating===rating)?._count._all??0;return {rating,count:value,percentage:total?value/total:0}}),classifications:{positive:"4–5 stars",neutral:"3 stars",critical:"1–2 stars"}}}
export async function funnel(shopId:string,r:AnalyticsRange){const [scheduled,sent,delivered,clicked,submitted]=await Promise.all([prisma.reviewRequest.count({where:{shopId,scheduledAt:{gte:r.start,lte:r.end}}}),prisma.reviewRequest.count({where:{shopId,sentAt:{gte:r.start,lte:r.end}}}),prisma.reviewRequest.count({where:{shopId,deliveredAt:{gte:r.start,lte:r.end}}}),prisma.reviewRequest.count({where:{shopId,clickedAt:{gte:r.start,lte:r.end}}}),prisma.reviewRequest.count({where:{shopId,submittedAt:{gte:r.start,lte:r.end}}})]);return {range:serialize(r),deliveryTracking:"Provider-confirmed delivery is partial when providers do not report it.",stages:[['Scheduled',scheduled],['Sent',sent],['Delivered',delivered],['Clicked',clicked],['Submitted',submitted]].map(([label,count])=>({label,count:Number(count)})),sentToSubmittedConversion:sent?submitted/sent:0}}
export function serialize(r:AnalyticsRange){return {start:r.start.toISOString(),end:r.end.toISOString(),comparisonStart:r.comparisonStart.toISOString(),comparisonEnd:r.comparisonEnd.toISOString(),timezone:r.timezone,label:r.label}}
