import { prisma } from "../db/prisma.ts";
import { getShopifyOrderForReviewSync, type ShopifyReviewSourceLine, type ShopifyReviewSourceOrder } from "../shopify/order-review-source.ts";
import { createOrGetReviewRequest } from "./review-foundation.ts";
import { evaluateReviewRequestsForOrder } from "./review-eligibility.ts";
import { decideReviewCandidateLine, normalizeHttpsImageUrl, normalizeReviewText, normalizeVariantTitle, type ReviewCandidateLineDecision } from "./review-candidate-policy.ts";

type Request = { id: string; shopId: string; customerProfileId: string; megaskaOrderId: string; shopifyOrderId: string; shopifyLineItemId: string; shopifyProductId: string; shopifyVariantId: string | null; shopifyOrderName: string | null; productTitleSnapshot: string; variantTitleSnapshot: string | null; productHandleSnapshot: string | null; productImageUrlSnapshot: string | null; orderCreatedAt: Date | null; deliveredAtSnapshot: Date | null; status: string };
type LocalOrder = { id: string; shopId: string; customerProfileId: string; shopifyOrderId: string | null; shopifyOrderName: string; orderPlacedAt: Date | null; deliveredAt: Date | null; customerProfile: { id: string; shopId: string; shopifyCustomerId: string | null } };
export type ReviewCandidateSyncResult = { status: "SYNCED" | "ORDER_NOT_DELIVERED" | "MISSING_SHOPIFY_ORDER_ID"; shopId: string; megaskaOrderId: string; shopifyOrderId: string | null; sourceLineCount: number; reviewableLineCount: number; createdCount: number; enrichedCount: number; unchangedCount: number; skippedCount: number; integrityWarningCount: number; skipped: Array<{ shopifyLineItemId: string | null; reason: ReviewCandidateLineDecision["reason"] }>; eligibilityResult: Awaited<ReturnType<typeof evaluateReviewRequestsForOrder>> | null };
export class ReviewCandidateSyncError extends Error { readonly code: "REVIEW_SOURCE_CUSTOMER_MISMATCH" | "REVIEW_SOURCE_ORDER_NOT_FOUND" | "REVIEW_SOURCE_INVALID_ORDER"; constructor(code: "REVIEW_SOURCE_CUSTOMER_MISMATCH" | "REVIEW_SOURCE_ORDER_NOT_FOUND" | "REVIEW_SOURCE_INVALID_ORDER", message: string) { super(message); this.name = "ReviewCandidateSyncError"; this.code = code; } }
type CandidateDb = { megaskaOrder: { findFirst(args: unknown): Promise<LocalOrder | null>; findMany(args: unknown): Promise<Array<Pick<LocalOrder, "id" | "shopId" | "deliveredAt">>> }; reviewRequest: { findMany(args: unknown): Promise<Request[]>; findUnique(args: unknown): Promise<Request | null>; update(args: unknown): Promise<Request> } };
const advanced = new Set(["SENT", "REMINDER_SENT", "COMPLETED", "EXPIRED", "CANCELED"]);
const date = (value: string | null) => value && !Number.isNaN(Date.parse(value)) ? new Date(value) : null;
const titleFor = (line: ShopifyReviewSourceLine) => normalizeReviewText(line.productTitle) ?? normalizeReviewText(line.title);
const incomplete = (value: string | null | undefined) => !normalizeReviewText(value) || normalizeReviewText(value)?.toLowerCase() === "unknown product";
export async function enrichExistingReviewRequestSnapshots(input: { reviewRequest: Request; sourceLine: ShopifyReviewSourceLine; sourceOrder: ShopifyReviewSourceOrder; canonicalDeliveredAt: Date }, db: CandidateDb = prisma as unknown as CandidateDb) { const request = input.reviewRequest; const title = titleFor(input.sourceLine); if (request.shopifyProductId !== input.sourceLine.shopifyProductId || request.shopifyLineItemId !== input.sourceLine.shopifyLineItemId || request.shopifyOrderId !== input.sourceOrder.shopifyOrderId) return { enriched: false, integrityWarning: true }; const data: Record<string, string | Date | null> = {}; const fill = (key: string, current: string | null, next: string | null) => { if (incomplete(current) && next) data[key] = next; };
  fill("shopifyOrderName", request.shopifyOrderName, normalizeReviewText(input.sourceOrder.shopifyOrderName)); if (!request.shopifyVariantId && input.sourceLine.shopifyVariantId) data.shopifyVariantId = input.sourceLine.shopifyVariantId; fill("variantTitleSnapshot", request.variantTitleSnapshot, normalizeVariantTitle(input.sourceLine.variantTitle)); fill("productHandleSnapshot", request.productHandleSnapshot, normalizeReviewText(input.sourceLine.productHandle)); fill("productImageUrlSnapshot", request.productImageUrlSnapshot, normalizeHttpsImageUrl(input.sourceLine.productImageUrl)); if (!request.orderCreatedAt && date(input.sourceOrder.createdAt)) data.orderCreatedAt = date(input.sourceOrder.createdAt); if (!advanced.has(request.status) && (!request.deliveredAtSnapshot || request.deliveredAtSnapshot.getTime() !== input.canonicalDeliveredAt.getTime())) data.deliveredAtSnapshot = input.canonicalDeliveredAt; if (!Object.keys(data).length) return { enriched: false, integrityWarning: false }; await db.reviewRequest.update({ where: { id: request.id }, data }); return { enriched: true, integrityWarning: false }; }
export async function syncReviewCandidatesForOrder(input: { shopId: string; megaskaOrderId: string; now?: Date; shopDomain?: string }, db: CandidateDb = prisma as unknown as CandidateDb): Promise<ReviewCandidateSyncResult> { const order = await db.megaskaOrder.findFirst({ where: { id: input.megaskaOrderId, shopId: input.shopId }, include: { customerProfile: true } }); if (!order) throw new ReviewCandidateSyncError("REVIEW_SOURCE_INVALID_ORDER", "Order ownership could not be resolved."); const base: Omit<ReviewCandidateSyncResult, "status"> = { shopId: input.shopId, megaskaOrderId: order.id, shopifyOrderId: order.shopifyOrderId, sourceLineCount: 0, reviewableLineCount: 0, createdCount: 0, enrichedCount: 0, unchangedCount: 0, skippedCount: 0, integrityWarningCount: 0, skipped: [] as ReviewCandidateSyncResult["skipped"], eligibilityResult: null };
  if (!order.deliveredAt) return { ...base, status: "ORDER_NOT_DELIVERED" }; if (!order.shopifyOrderId) return { ...base, status: "MISSING_SHOPIFY_ORDER_ID" }; const source = await getShopifyOrderForReviewSync({ shopDomain: input.shopDomain ?? "", shopifyOrderId: order.shopifyOrderId }); if (!source) throw new ReviewCandidateSyncError("REVIEW_SOURCE_ORDER_NOT_FOUND", "Shopify order was not found."); if (source.shopifyOrderId !== order.shopifyOrderId) throw new ReviewCandidateSyncError("REVIEW_SOURCE_INVALID_ORDER", "Shopify order identity does not match persisted order."); if (order.customerProfile.shopifyCustomerId && source.customerId && order.customerProfile.shopifyCustomerId !== source.customerId) throw new ReviewCandidateSyncError("REVIEW_SOURCE_CUSTOMER_MISMATCH", "Shopify order customer does not match persisted customer.");
  const existing = await db.reviewRequest.findMany({ where: { shopId: input.shopId, megaskaOrderId: order.id } }); const byLine = new Map(existing.map((request) => [request.shopifyLineItemId, request])); base.sourceLineCount = source.lineItems.length;
  for (const line of source.lineItems) { const decision = source.cancelledAt ? { reviewable: false, reason: "CANCELED_OR_REMOVED" as const } : decideReviewCandidateLine(line); if (!decision.reviewable) { base.skippedCount++; base.skipped.push({ shopifyLineItemId: normalizeReviewText(line.shopifyLineItemId), reason: decision.reason }); continue; } base.reviewableLineCount++; const existingRequest = byLine.get(line.shopifyLineItemId); if (existingRequest) { const result = await enrichExistingReviewRequestSnapshots({ reviewRequest: existingRequest, sourceLine: line, sourceOrder: source, canonicalDeliveredAt: order.deliveredAt }, db); if (result.enriched) base.enrichedCount++; else base.unchangedCount++; if (result.integrityWarning) base.integrityWarningCount++; continue; } const productTitle = titleFor(line); if (!productTitle) { base.skippedCount++; base.skipped.push({ shopifyLineItemId: line.shopifyLineItemId, reason: "INVALID_DATA" }); continue; } try { await createOrGetReviewRequest({ shopId: input.shopId, customerProfileId: order.customerProfileId, megaskaOrderId: order.id, shopifyOrderId: order.shopifyOrderId, shopifyOrderName: source.shopifyOrderName, shopifyLineItemId: line.shopifyLineItemId, shopifyProductId: line.shopifyProductId!, shopifyVariantId: line.shopifyVariantId ?? undefined, productTitleSnapshot: productTitle, variantTitleSnapshot: normalizeVariantTitle(line.variantTitle) ?? undefined, productHandleSnapshot: normalizeReviewText(line.productHandle) ?? undefined, productImageUrlSnapshot: normalizeHttpsImageUrl(line.productImageUrl) ?? undefined, orderCreatedAt: date(source.createdAt), deliveredAtSnapshot: order.deliveredAt }, db); base.createdCount++; } catch (error) { if (!(error instanceof Error) || !/unique/i.test(error.message)) throw error; const raced = await db.reviewRequest.findUnique({ where: { shopId_shopifyOrderId_shopifyLineItemId: { shopId: input.shopId, shopifyOrderId: order.shopifyOrderId, shopifyLineItemId: line.shopifyLineItemId } } }); if (raced) { base.unchangedCount++; } else throw error; } }
  base.eligibilityResult = await evaluateReviewRequestsForOrder({ shopId: input.shopId, megaskaOrderId: order.id, now: input.now }, db as never); return { ...base, status: "SYNCED" }; }
export async function listDeliveredOrdersNeedingReviewCandidateSync(input: { shopId?: string; deliveredBefore?: Date; limit?: number; cursor?: string }, db: CandidateDb = prisma as unknown as CandidateDb) { const limit = Math.min(Math.max(input.limit ?? 25, 1), 100); return db.megaskaOrder.findMany({ take: limit, ...(input.cursor ? { cursor: { id: input.cursor }, skip: 1 } : {}), where: { deliveredAt: { not: null, ...(input.deliveredBefore ? { lte: input.deliveredBefore } : {}) }, ...(input.shopId ? { shopId: input.shopId } : {}) }, orderBy: [{ deliveredAt: "asc" }, { id: "asc" }] }); }
export async function syncDeliveredOrderReviewCandidatesBatch(input: { shopId?: string; limit?: number; cursor?: string; now?: Date; shopDomain?: string }, db: CandidateDb = prisma as unknown as CandidateDb) { const orders = await listDeliveredOrdersNeedingReviewCandidateSync(input, db); const outcomes: Array<{ megaskaOrderId: string; ok: boolean; errorCode?: string; result?: ReviewCandidateSyncResult }> = []; let created = 0, enriched = 0, skipped = 0; for (const order of orders) try { const result = await syncReviewCandidatesForOrder({ shopId: order.shopId, megaskaOrderId: order.id, now: input.now, shopDomain: input.shopDomain }, db); created += result.createdCount; enriched += result.enrichedCount; skipped += result.skippedCount; outcomes.push({ megaskaOrderId: order.id, ok: true, result }); } catch (error) { outcomes.push({ megaskaOrderId: order.id, ok: false, errorCode: error instanceof ReviewCandidateSyncError ? error.code : "REVIEW_SOURCE_GRAPHQL_FAILED" }); } return { scanned: orders.length, succeeded: outcomes.filter((outcome) => outcome.ok).length, failed: outcomes.filter((outcome) => !outcome.ok).length, created, enriched, skipped, nextCursor: orders.length === (input.limit ?? 25) ? orders.at(-1)?.id ?? null : null, orders: outcomes }; }
