import type { ShopifyReviewSourceLine } from "../shopify/order-review-source.ts";
export type ReviewCandidateLineDecision = { reviewable: boolean; reason: "REVIEWABLE" | "MISSING_LINE_ITEM_ID" | "MISSING_PRODUCT_ID" | "NON_MERCHANDISE_LINE" | "ZERO_QUANTITY" | "CANCELED_OR_REMOVED" | "GIFT_CARD" | "TIP" | "SHIPPING" | "CUSTOM_ITEM" | "PRODUCT_DELETED" | "INVALID_DATA" };
const no = (reason: ReviewCandidateLineDecision["reason"]): ReviewCandidateLineDecision => ({ reviewable: false, reason });
export function decideReviewCandidateLine(line: ShopifyReviewSourceLine): ReviewCandidateLineDecision { const title = line.title?.trim().toLowerCase() ?? ""; if (!line.shopifyLineItemId?.trim()) return no("MISSING_LINE_ITEM_ID"); if (!Number.isFinite(line.quantity) || line.quantity <= 0) return no("ZERO_QUANTITY"); if (line.currentQuantity !== null && line.currentQuantity <= 0) return no("CANCELED_OR_REMOVED");
  // refundableQuantity is not refunded quantity and must not disqualify verified delivered purchases.
  if (line.isGiftCard) return no("GIFT_CARD"); if (/\b(tip|gratuity)\b/.test(title)) return no("TIP"); if (/\b(shipping|delivery)\b/.test(title) && !line.shopifyProductId) return no("SHIPPING"); if (!line.shopifyProductId?.trim()) return no("MISSING_PRODUCT_ID"); return { reviewable: true, reason: "REVIEWABLE" }; }
export const normalizeReviewText = (value: string | null | undefined) => value?.trim() || null;
export const normalizeVariantTitle = (value: string | null | undefined) => { const text = normalizeReviewText(value); return text?.toLowerCase() === "default title" ? null : text; };
export const normalizeHttpsImageUrl = (value: string | null | undefined) => { const text = normalizeReviewText(value); if (!text) return null; try { return new URL(text).protocol === "https:" ? text : null; } catch { return null; } };
