/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";
import assert from "node:assert/strict";
import { getPublishedProductReviews, normalizeShopifyProductId } from "./review-storefront-query.ts";

type Row = {id:string;shopId:string;shopifyProductId:string;status:string;publishedAt:Date|null;hiddenAt:Date|null;deletedAt:Date|null;rating:number;[key:string]:unknown};
const review=(overrides:Partial<Row>):Row=>({id:"review",shopId:"shop-a",shopifyProductId:"123",status:"PUBLISHED",publishedAt:new Date("2026-07-19"),hiddenAt:null,deletedAt:null,rating:5,title:null,body:null,customerDisplayName:"A",verifiedPurchase:true,productTitleSnapshot:"P",variantTitleSnapshot:null,createdAt:new Date("2026-07-18"),media:[],...overrides});
function matches(row:Row,where:any){return Object.entries(where).every(([key,value]:any)=>{if(value&&typeof value==="object"){if("in" in value)return value.in.includes(row[key]);if("not" in value)return row[key]!==value.not}return row[key]===value})}
function database(rows:Row[]){return {productReview:{count:async({where}:any)=>rows.filter(row=>matches(row,where)).length,findMany:async({where,select,skip=0,take}:any)=>{const found=rows.filter(row=>matches(row,where)).slice(skip,take===undefined?undefined:skip+take);return select&&Object.keys(select).length===1&&select.rating?found.map(({rating})=>({rating})):found}}} as any}

test("normalizes numeric and Product GID IDs",()=>{assert.equal(normalizeShopifyProductId("123"),"123");assert.equal(normalizeShopifyProductId("gid://shopify/Product/123"),"123");assert.equal(normalizeShopifyProductId("gid://shopify/Variant/123"),null)});
test("numeric storefront request finds a stored product GID",async()=>{const data=await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"123",db:database([review({shopifyProductId:"gid://shopify/Product/123"})])});assert.deepEqual(data.items.map(x=>x.id),["review"])});
test("GID storefront request finds a stored numeric product ID",async()=>{const data=await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"gid://shopify/Product/123",db:database([review({})])});assert.deepEqual(data.items.map(x=>x.id),["review"])});
test("public visibility filters expose only fully published reviews for the requested shop",async()=>{const rows=[review({id:"visible"}),review({id:"pending",status:"PENDING_MODERATION",publishedAt:null}),review({id:"hidden",hiddenAt:new Date()}),review({id:"deleted",deletedAt:new Date()}),review({id:"unpublished-date",publishedAt:null}),review({id:"other-shop",shopId:"shop-b"})];const data=await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"123",db:database(rows)});assert.deepEqual(data.items.map(x=>x.id),["visible"]);assert.equal(data.summary.reviewCount,1)});
test("a newly published review is visible on the next uncached query",async()=>{const row=review({status:"PENDING_MODERATION",publishedAt:null});const db=database([row]);assert.equal((await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"123",db})).totalCount,0);row.status="PUBLISHED";row.publishedAt=new Date();assert.equal((await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"123",db})).totalCount,1)});
test("pagination is bounded",async()=>{const data=await getPublishedProductReviews({shopId:"shop-a",shopifyProductId:"123",page:2,pageSize:99,db:database([])});assert.equal(data.pageSize,25);assert.equal(data.hasPreviousPage,true)});
