import { EXCHANGE_REQUEST_WINDOW_LOCK_REASON, ISSUE_REQUEST_WINDOW_LOCK_REASON, getRequestWindowExpiresAt, isWithinRequestWindow, parseTrustedDeliveryDate } from "../exchange/deadlines.ts";
import type { DashboardModulesDto, DashboardOrderActionDto, DashboardOrderActionsDto, DashboardOrderActionState } from "./contract.ts";
import type { DashboardOrderRequestSnapshot } from "./requests.ts";

export type DashboardOrderActionPolicyInput={now:Date;fulfillmentStatus:string|null;fulfilledAt:Date|string|null;deliveredAt:Date|string|null;trackingDeliveredAt:Date|string|null;requests:DashboardOrderRequestSnapshot;modules:Pick<DashboardModulesDto,"cancellation"|"exchange"|"issueReporting">};
const DELIVERY_REQUIRED_LOCK_REASON="Delivery must be confirmed before requesting an exchange or reporting an issue.";
function normalizeFulfillmentStatus(v:string|null){return String(v||"").trim().toUpperCase().replace(/[\s-]+/g,"_");}
function shipped(input:DashboardOrderActionPolicyInput){return Boolean(parseTrustedDeliveryDate(input.fulfilledAt)||parseTrustedDeliveryDate(input.deliveredAt)||parseTrustedDeliveryDate(input.trackingDeliveredAt)||["FULFILLED","SHIPPED","IN_TRANSIT","OUT_FOR_DELIVERY","PARTIAL","PARTIALLY_FULFILLED","DELIVERED"].includes(normalizeFulfillmentStatus(input.fulfillmentStatus)));}
function trustedDeliveredAt(input:DashboardOrderActionPolicyInput){return parseTrustedDeliveryDate(input.deliveredAt)||parseTrustedDeliveryDate(input.trackingDeliveredAt);}
function state(status:string|undefined|null, active:boolean):DashboardOrderActionState{const s=String(status||"").toUpperCase(); if(active)return s==="OPEN"?"OPEN":"IN_PROGRESS"; if(s==="CLOSED")return"COMPLETED"; if(s==="REJECTED")return"REJECTED"; if(s==="CANCELLED")return"CANCELLED"; return"COMPLETED";}
function action(type:DashboardOrderActionDto["type"],label:string,over:Partial<DashboardOrderActionDto>):DashboardOrderActionDto{return{type,label,available:false,state:"LOCKED",description:null,lockReason:null,deadlineAt:null,requestId:null,...over};}
function disabled(type:DashboardOrderActionDto["type"],label:string){return action(type,label,{state:"NOT_APPLICABLE"});}
export function buildDashboardOrderActions(input:DashboardOrderActionPolicyInput):DashboardOrderActionsDto{const d=trustedDeliveredAt(input); const deadline=getRequestWindowExpiresAt(d); const deadlineAt=deadline?.toISOString()||null; const conflict=input.requests.activeConflict;
 const cancellation=(()=>{if(!input.modules.cancellation)return disabled("CANCELLATION","Cancel order"); const r=input.requests.cancellation; if(r)return action("CANCELLATION","Cancel order",{state:state(r.status,r.blocking),requestId:r.id,lockReason:r.blocking?"Cancellation request is active.":null}); if(conflict)return action("CANCELLATION","Cancel order",{lockReason:conflict.lockReason}); if(shipped(input))return action("CANCELLATION","Cancel order",{lockReason:"Cancellation not possible — order already shipped."}); return action("CANCELLATION","Cancel order",{available:true,state:"AVAILABLE",description:"Request cancellation before shipment."});})();
 const exchange=(()=>{if(!input.modules.exchange)return disabled("EXCHANGE","Exchange items"); const r=input.requests.exchange; if(r)return action("EXCHANGE","Exchange items",{state:state(r.status,r.active),requestId:r.id,deadlineAt}); if(!d)return action("EXCHANGE","Exchange items",{lockReason:DELIVERY_REQUIRED_LOCK_REASON,deadlineAt}); if(!isWithinRequestWindow(d,input.now))return action("EXCHANGE","Exchange items",{lockReason:EXCHANGE_REQUEST_WINDOW_LOCK_REASON,deadlineAt}); if(conflict)return action("EXCHANGE","Exchange items",{lockReason:conflict.lockReason,deadlineAt}); return action("EXCHANGE","Exchange items",{available:true,state:"AVAILABLE",description:"Request an exchange within the return window.",deadlineAt});})();
 const issue=(()=>{if(!input.modules.issueReporting)return disabled("ISSUE","Report issue"); const r=input.requests.issue; if(r)return action("ISSUE","Report issue",{state:state(r.status,r.blocking),requestId:r.id,deadlineAt}); if(!d)return action("ISSUE","Report issue",{lockReason:DELIVERY_REQUIRED_LOCK_REASON,deadlineAt}); if(!isWithinRequestWindow(d,input.now))return action("ISSUE","Report issue",{lockReason:ISSUE_REQUEST_WINDOW_LOCK_REASON,deadlineAt}); if(conflict)return action("ISSUE","Report issue",{lockReason:conflict.lockReason,deadlineAt}); return action("ISSUE","Report issue",{available:true,state:"AVAILABLE",description:"Report an issue within the support window.",deadlineAt});})();
 const refundStatus=(()=>{const r=input.requests.cancellation; const code=r?.refundOutcome.refundStatusCode; const req=r?.refundOutcome.requirementLabel; if(!r||(!code&&!req))return action("REFUND_STATUS","Refund status",{state:"NOT_APPLICABLE"}); return action("REFUND_STATUS","Refund status",{available:true,state:String(code||req).toUpperCase().includes("PAID")||String(req).toUpperCase().includes("COMPLETED")?"COMPLETED":"IN_PROGRESS",requestId:r.id,description:r.refundOutcome.customerExplanation});})();
 return{cancellation,exchange,issue,refundStatus};}
