import assert from "node:assert/strict";
import test from "node:test";
import { loadDashboardCommerceSnapshot, moneyToPaise, resetDashboardCommerceDependenciesForTest, setDashboardCommerceDependenciesForTest } from "./commerce.ts";
const context={shopId:"shop-1",shopDomain:"s.myshopify.com",customerProfileId:"cust-1",sessionId:"sess",now:new Date()};
const customer={customerProfileId:"cust-1",shopId:"shop-1",shopDomain:"s.myshopify.com",firstName:null,lastName:null,phoneE164:"+919999999999",phoneVerifiedAt:null,email:"a@example.com",shopifyCustomerId:"123",address:{line1:null,line2:null,city:null,stateProvince:null,postalCode:null,countryRegion:null}};
const order={id:"gid://shopify/Order/1",shopifyOrderId:"gid://shopify/Order/1",numericOrderId:"1",name:"#1001",createdAt:"2026",processedAt:null,deliveredAt:"2026-01-03",closedAt:"2026-01-02",cancelledAt:null,cancelReason:null,totalAmount:"123.45",subtotalAmount:"100.00",shippingAmount:"10",taxAmount:"13.45",currencyCode:"INR",financialStatus:"PAID",fulfillmentStatus:"FULFILLED",statusPageUrl:null,email:"a@example.com",phone:null,customerId:"gid://shopify/Customer/123",shippingAddress:null,billingAddress:null,fulfillments:[{id:"f1",status:"FULFILLED",createdAt:"2026-01-02",deliveredAt:"2026-01-03",trackingInfo:[{company:"BlueDart",number:"AWB",url:"https://t"}]}],lineItems:[{id:"li1",shopifyLineItemId:"li1",productId:"p1",variantId:"v1",title:"Tee",productTitle:"Tee",variantTitle:"M",sku:"SKU",quantity:2,fulfillableQuantity:null,refundableQuantity:null,currentSize:null,image:"img",unitPrice:"50.00",discountedTotal:"100.00",currencyCode:"INR",productType:null,vendor:null,tags:[]}],displayTitle:null,displayImage:null,itemsCount:1,firstLineItemId:null,firstLineItemTitle:null,firstLineItemVariantTitle:null,firstLineItemSku:null};
function setup(data){setDashboardCommerceDependenciesForTest({isShopifyAdminConfigured:()=>true,getMegaskaCustomerDashboardData:async()=>data,logger:{warn(){}}});}
test.afterEach(()=>resetDashboardCommerceDependenciesForTest());
test("Shopify Admin not configured",async()=>{setDashboardCommerceDependenciesForTest({isShopifyAdminConfigured:()=>false});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.available,false);});
test("Successful snapshot normalization",async()=>{setup({email:"shop@example.com",phone:null,defaultAddress:null,totalOrderCount:1,recentOrders:[order],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.available,true);assert.equal(s.recentOrders[0].totalPaise,12345);});
test("Shopify adapter failure returns unavailable snapshot",async()=>{setDashboardCommerceDependenciesForTest({isShopifyAdminConfigured:()=>true,getMegaskaCustomerDashboardData:async()=>{throw new Error("x")},logger:{warn(){}}});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.errorCode,"SHOPIFY_COMMERCE_UNAVAILABLE");});
test("Default address normalization",async()=>{setup({email:null,phone:null,defaultAddress:{firstName:"A",lastName:"R",address1:"L1",address2:"L2",city:"C",province:"KA",zip:"1",country:"IN",phone:"9"},totalOrderCount:0,recentOrders:[],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.defaultAddress.line1,"L1");});
test("Multiple order items preserved",async()=>{setup({email:null,phone:null,defaultAddress:null,totalOrderCount:1,recentOrders:[{...order,lineItems:[...order.lineItems,{...order.lineItems[0],id:"li2"}]}],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.recentOrders[0].items.length,2);});
test("Fulfillment tracking info preserved",async()=>{setup({email:null,phone:null,defaultAddress:null,totalOrderCount:1,recentOrders:[order],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.recentOrders[0].fulfillments[0].trackingInfo[0].number,"AWB");});
test("Currency and paise conversion",()=>{assert.equal(moneyToPaise("1.05"),105);assert.throws(()=>moneyToPaise("1.005"));});
test("Missing optional Shopify fields handled safely",async()=>{setup({email:null,phone:null,defaultAddress:null,totalOrderCount:0,recentOrders:[{...order,totalAmount:null,lineItems:[],fulfillments:null}],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal(s.recentOrders[0].totalPaise,0);});
test("No raw Shopify response object is returned",async()=>{setup({email:null,phone:null,defaultAddress:null,totalOrderCount:1,recentOrders:[{...order,raw:{secret:true}}],matchSource:"customer_id"});const s=await loadDashboardCommerceSnapshot({context,customer});assert.equal("raw" in s.recentOrders[0],false);});
