import assert from "node:assert/strict";
import test from "node:test";
import { buildDashboardCustomerDto, resolveDashboardCustomerIdentity, resetDashboardCustomerDependenciesForTest, setDashboardCustomerDependenciesForTest } from "./customer.ts";
import { CustomerDashboardError } from "./errors.ts";
const context={shopId:"shop-1",shopDomain:"s.myshopify.com",customerProfileId:"cust-1",sessionId:"sess",now:new Date()};
const base={id:"cust-1",shopId:"shop-1",firstName:"Asha",lastName:"Rao",phoneE164:"+919999999999",phoneVerifiedAt:new Date("2026-01-01"),email:"a@example.com",shopifyCustomerId:null,addressLine1:"L1"};
function setup(o={}){const updates=[];setDashboardCustomerDependenciesForTest({customerProfile:{findFirst:async()=>base,update:async(a)=>{updates.push(a);return a;}},isShopifyAdminConfigured:()=>false,findShopifyCustomerIdByIdentity:async()=>null,logger:{info(){},warn(){}},...o});return{updates};}
test.afterEach(()=>resetDashboardCustomerDependenciesForTest());
test("Profile found for correct shop",async()=>{setup();const r=await resolveDashboardCustomerIdentity(context);assert.equal(r.customerProfileId,"cust-1");assert.equal(r.shopId,"shop-1");});
test("Missing profile",async()=>{setup({customerProfile:{findFirst:async()=>null,update:async()=>null}});await assert.rejects(resolveDashboardCustomerIdentity(context),e=>e instanceof CustomerDashboardError&&e.code==="CUSTOMER_NOT_FOUND");});
test("Cross-shop profile rejected",async()=>{setup({customerProfile:{findFirst:async()=>({...base,shopId:"shop-2"}),update:async()=>null}});await assert.rejects(resolveDashboardCustomerIdentity(context),e=>e instanceof CustomerDashboardError&&e.code==="CUSTOMER_NOT_FOUND");});
test("Existing Shopify customer ID preserved",async()=>{const {updates}=setup({customerProfile:{findFirst:async()=>({...base,shopifyCustomerId:"111"}),update:async(a)=>{updates.push(a);}}});const r=await resolveDashboardCustomerIdentity(context);assert.equal(r.shopifyCustomerId,"111");assert.equal(updates.length,0);});
test("Email match preferred",async()=>{setup({isShopifyAdminConfigured:()=>true,findShopifyCustomerIdByIdentity:async(i)=>i.email?"email-id":"phone-id"});const r=await resolveDashboardCustomerIdentity(context);assert.equal(r.shopifyCustomerId,"email-id");});
test("Phone match used when no email match",async()=>{setup({isShopifyAdminConfigured:()=>true,findShopifyCustomerIdByIdentity:async(i)=>i.phoneE164?"phone-id":null});const r=await resolveDashboardCustomerIdentity(context);assert.equal(r.shopifyCustomerId,"phone-id");});
test("Newly resolved Shopify ID persisted",async()=>{const {updates}=setup({isShopifyAdminConfigured:()=>true,findShopifyCustomerIdByIdentity:async()=>"new-id"});await resolveDashboardCustomerIdentity(context);assert.deepEqual(updates[0],{where:{id:"cust-1"},data:{shopifyCustomerId:"new-id"}});});
test("Shopify lookup failure degrades safely",async()=>{setup({isShopifyAdminConfigured:()=>true,findShopifyCustomerIdByIdentity:async()=>{throw new Error("boom")}});const r=await resolveDashboardCustomerIdentity(context);assert.equal(r.email,"a@example.com");});
test("Customer DTO display name and initials",()=>{const dto=buildDashboardCustomerDto({...base,customerProfileId:"cust-1",shopDomain:"s",shopId:"shop-1",address:{line1:null,line2:null,city:null,stateProvince:null,postalCode:null,countryRegion:null},shopifyCustomerId:null}," commerce@example.com ");assert.equal(dto.displayName,"Asha Rao");assert.equal(dto.initials,"AR");assert.equal(dto.email,"commerce@example.com");});
test("No browser-supplied customer identity is used",async()=>{let query;setup({customerProfile:{findFirst:async(a)=>{query=a;return base;},update:async()=>null}});await resolveDashboardCustomerIdentity({...context,customerProfileId:"trusted"});assert.equal(query.where.id,"trusted");assert.equal(query.where.browserCustomerId,undefined);});
