import assert from "node:assert/strict";
import test from "node:test";
import { buildDashboardExchangeProgress, loadDashboardOrderRequests, resetDashboardRequestDependenciesForTest, setDashboardRequestDependenciesForTest } from "./requests.ts";
const context={shopId:"shop-1",shopDomain:"s",customerProfileId:"cust-1",sessionId:"sess",now:new Date()};
test.afterEach(()=>resetDashboardRequestDependenciesForTest());
test("Empty order-number input performs no queries",async()=>{let calls=0;setDashboardRequestDependenciesForTest({orderActionRequest:{findMany:async()=>{calls++;return[]}},refundRequest:{findMany:async()=>{calls++;return[]}}});const r=await loadDashboardOrderRequests({context,orderNumbers:[]});assert.equal(calls,0);assert.equal(r.openRequestCount,0);});
test("Batch queries trim/dedupe and scope by shop/customer/order",async()=>{const queries=[];setDashboardRequestDependenciesForTest({orderActionRequest:{findMany:async(a)=>{queries.push(a);return[]}},refundRequest:{findMany:async()=>[]}});await loadDashboardOrderRequests({context,orderNumbers:[" 1001 ","#1001"]});assert.equal(queries.length,3);for(const q of queries){assert.equal(q.where.shopId,"shop-1");assert.equal(q.where.customerProfileId,"cust-1");assert.deepEqual(q.where.orderNumber.in,["#1001"]);}});
test("Latest requests, refunds, mappings, conflicts and open count",async()=>{
 const d=(s)=>new Date(s); let refundCalls=0;
 const cancellations=[{id:"old",orderNumber:"#1",status:"REJECTED",requestedAt:d("2026-01-01"),updatedAt:null,orderAmountSnapshot:"100"},{id:"can",orderNumber:"#1",status:"APPROVED",requestedAt:d("2026-01-02"),updatedAt:null,orderAmountSnapshot:"100"},{id:"can2",orderNumber:"#2",status:"CLOSED",requestedAt:d("2026-01-02"),updatedAt:null,orderAmountSnapshot:"0"}].sort((a,b)=>b.requestedAt.getTime()-a.requestedAt.getTime());
 const exchanges=[{id:"ex",orderNumber:"#1",status:"PICKUP_SCHEDULED",requestedAt:d("2026-01-03"),updatedAt:null,payments:[{status:"PAID",paidAt:d("2026-01-03"),amount:9900,currency:"INR"}],shipments:[{id:"rs",direction:"REVERSE_PICKUP",status:"SCHEDULED",carrier:"D",awb:"R",trackingUrl:null,pickupAt:null,shippedAt:null,deliveredAt:null,updatedAt:d("2026-01-03")},{id:"fs",direction:"FORWARD_REPLACEMENT",status:"NOT_STARTED",carrier:null,awb:"F",trackingUrl:null,pickupAt:null,shippedAt:null,deliveredAt:null,updatedAt:d("2026-01-03")}]}];
 const issues=[{id:"iss",orderNumber:"#2",status:"OPEN",requestedAt:d("2026-01-03"),updatedAt:null},{id:"closed",orderNumber:"#3",status:"CLOSED",requestedAt:d("2026-01-03"),updatedAt:null}];
 setDashboardRequestDependenciesForTest({orderActionRequest:{findMany:async(a)=>a.where.requestType==="CANCELLATION"?cancellations:a.where.requestType==="EXCHANGE"?exchanges:issues},refundRequest:{findMany:async(a)=>{refundCalls++;assert.equal(a.where.shopId,"shop-1");assert.equal(a.where.orderActionRequest.shopId,"shop-1");return[{id:"ref",status:"PAID",method:"PREPAID",amount:100,currency:"INR",orderActionRequestId:"can",walletTransactionId:null,createdAt:d("2026-01-02"),updatedAt:d("2026-01-03")}];}}});
 const r=await loadDashboardOrderRequests({context,orderNumbers:["1","2","3"]});
 assert.equal(refundCalls,1);assert.equal(r.byOrderNumber.get("#1")?.cancellation?.id,"can");assert.equal(r.byOrderNumber.get("#1")?.cancellation?.refundOutcome.refundStatusCode,"PAID");assert.equal(r.byOrderNumber.get("#1")?.exchange?.payment?.amountPaise,9900);assert.equal(r.byOrderNumber.get("#1")?.exchange?.reverseShipment?.awb,"R");assert.equal(r.byOrderNumber.get("#1")?.exchange?.replacementShipment?.awb,"F");assert.equal(r.byOrderNumber.get("#1")?.exchange?.progress.length,7);assert.equal(r.byOrderNumber.get("#2")?.issue?.id,"iss");assert.equal(r.byOrderNumber.get("#1")?.activeConflict?.requestType,"CANCELLATION");assert.equal(r.openRequestCount,4);
});
test("Exchange progress contains all seven ordered steps",()=>{assert.deepEqual(buildDashboardExchangeProgress({id:"e",status:"CLOSED",requestedAt:new Date()}).map(s=>s.key),["REQUESTED","FEE_PAID","PICKUP_SCHEDULED","PICKED_UP","ITEM_RECEIVED","REPLACEMENT_SHIPPED","COMPLETED"]);});
