import { prisma } from "../db/prisma.ts";
import { deriveCancellationOutcome, isCancellationStatusBlocking } from "../exchange/cancellation.ts";
import { ACTIVE_EXCHANGE_STATUSES } from "../exchange/lifecycle.ts";
import { isIssueStatusBlocking } from "../exchange/issue.ts";
import { findActiveRequest, formatRequestLockReason, normalizeOrderNumber } from "../exchange/request-interlocks.ts";
import { buildCustomerRequestTimeline } from "./request-timeline.ts";
import type { DashboardExchangeRequestDto, DashboardOrderRequestsDto, DashboardProgressStepDto, DashboardShipmentDto, DashboardOrderRequestTimelineDto } from "./contract.ts";
import type { CustomerDashboardContext } from "./context.ts";

export type DashboardRefundSettlementSnapshot={refundRequestId:string;requestId:string|null;method:string;status:string;amountPaise:number;currency:string;createdAt:Date|null;updatedAt:Date|null;paidAt:Date|null;settlement:{type:"STORE_CREDIT";transactionId:string;transactionType:"COD_REFUND_CREDIT";amountPaise:number;currency:string;issuedAt:Date}|{type:"ORIGINAL_PAYMENT_METHOD";completedAt:Date|null}|null};
export type DashboardCancellationRequestSnapshot={id:string;status:string;requestedAt:Date;updatedAt:Date|null;orderAmountSnapshotPaise:number|null;refundOutcome:{requirementLabel:string|null;customerExplanation:string|null;refundStatusCode:string|null};blocking:boolean;refunds?:DashboardRefundSettlementSnapshot[]};
export type DashboardExchangePaymentSnapshot={status:string;amountPaise:number;currency:string;paidAt:Date|null};
export type DashboardExchangeShipmentSnapshot={id:string;direction:"REVERSE_PICKUP"|"REPLACEMENT";carrier:string|null;awb:string|null;trackingUrl:string|null;statusCode:string;statusLabel:string;lastUpdatedAt:Date|null;pickupAt?:Date|null;shippedAt?:Date|null;deliveredAt?:Date|null};
export type DashboardExchangeProgressStepSnapshot={key:string;label:string;state:"COMPLETED"|"PENDING"};
export type DashboardExchangeRequestSnapshot={id:string;status:string;requestedAt:Date;updatedAt:Date|null;blocking:boolean;active:boolean;payment:DashboardExchangePaymentSnapshot|null;reverseShipment:DashboardExchangeShipmentSnapshot|null;replacementShipment:DashboardExchangeShipmentSnapshot|null;progress:DashboardExchangeProgressStepSnapshot[];refunds?:DashboardRefundSettlementSnapshot[]};
export type DashboardIssueRequestSnapshot={id:string;status:string;requestedAt:Date;updatedAt:Date|null;blocking:boolean;refunds?:DashboardRefundSettlementSnapshot[]};
export type DashboardActiveRequestConflict={requestType:"CANCELLATION"|"EXCHANGE"|"ISSUE";status:string;lockReason:string};
export type DashboardOrderRequestSnapshot={cancellation:DashboardCancellationRequestSnapshot|null;exchange:DashboardExchangeRequestSnapshot|null;issue:DashboardIssueRequestSnapshot|null;cancellations:DashboardCancellationRequestSnapshot[];exchanges:DashboardExchangeRequestSnapshot[];issues:DashboardIssueRequestSnapshot[];timeline:DashboardOrderRequestTimelineDto;activeConflict:DashboardActiveRequestConflict|null};
export type DashboardOrderRequestSnapshotMap=Map<string,DashboardOrderRequestSnapshot>;
export type DashboardOrderRequestAggregation={byOrderNumber:DashboardOrderRequestSnapshotMap;openRequestCount:number};
export type DashboardExchangeProgressInput={id:string;status:string;requestedAt:Date;payment?:{status:string}|null;reverseShipment?:{statusCode:string;awb?:string|null}|null;replacementShipment?:{statusCode:string;awb?:string|null}|null};

type RequestRow={id:string;orderNumber:string;status:string;requestedAt:Date;updatedAt?:Date|null;orderAmountSnapshot?:string|null;payments?:PaymentRow[];shipments?:ShipmentRow[]};
type PaymentRow={status:string;paidAt:Date|null;amount:number;currency:string};
type ShipmentRow={id?:string;direction:string;carrier:string|null;awb:string|null;trackingUrl:string|null;status:string;pickupAt:Date|null;shippedAt:Date|null;deliveredAt:Date|null;updatedAt:Date|null};
type RefundRow={id:string;status:string;method:string;amount:number;currency:string;orderActionRequestId:string|null;walletTransactionId?:string|null;paidAt?:Date|string|null;createdAt?:Date|string|null;updatedAt?:Date|string|null};
type WalletTransactionRow={id:string;shopId:string;customerProfileId:string;direction:string;transactionType:string;amount:number;currency:string;sourceType:string;sourceId:string|null;createdAt:Date|string|null};
type ActiveRequestType="CANCELLATION"|"EXCHANGE"|"ISSUE";
type Deps={orderActionRequest:{findMany:(args:unknown)=>Promise<RequestRow[]>};refundRequest:{findMany:(args:unknown)=>Promise<RefundRow[]>};walletTransaction:{findMany:(args:unknown)=>Promise<WalletTransactionRow[]>}};
const defaultDeps:Deps={orderActionRequest:{findMany:(a)=>prisma.orderActionRequest.findMany(a as never)},refundRequest:{findMany:(a)=>(prisma as any).refundRequest.findMany(a) as Promise<RefundRow[]>},walletTransaction:{findMany:(a)=>(prisma as any).walletTransaction.findMany(a) as Promise<WalletTransactionRow[]>}};
let deps=defaultDeps;
export function setDashboardRequestDependenciesForTest(overrides:Partial<Deps>){deps={...defaultDeps,...overrides} as Deps;}
export function resetDashboardRequestDependenciesForTest(){deps=defaultDeps;}

function uniqueOrderNumbers(values:string[]){return Array.from(new Set(values.map(normalizeOrderNumber).filter(Boolean)));}
function label(code:string){return String(code||"").trim().toUpperCase().replace(/_/g," ");}
function latestByOrder<T extends {orderNumber:string}>(rows:T[]){const m=new Map<string,T>();for(const r of rows){const k=normalizeOrderNumber(r.orderNumber); if(k&&!m.has(k)) m.set(k,r);} return m;}
function shipment(s:ShipmentRow|undefined, direction:"REVERSE_PICKUP"|"REPLACEMENT"):DashboardExchangeShipmentSnapshot|null{return s?{id:String(s.id||`${direction}-${s.awb||s.status}`),direction,carrier:s.carrier??null,awb:s.awb??null,trackingUrl:s.trackingUrl??null,statusCode:String(s.status||"UNKNOWN"),statusLabel:label(s.status),lastUpdatedAt:s.updatedAt??null,pickupAt:s.pickupAt??null,shippedAt:s.shippedAt??null,deliveredAt:s.deliveredAt??null}:null;}
function asDate(v:Date|string|null|undefined):Date|null{if(!v)return null; const d=v instanceof Date?v:new Date(v); return Number.isNaN(d.getTime())?null:d;}
function normalizeRefunds(refunds:RefundRow[],transactions:WalletTransactionRow[],context:CustomerDashboardContext):Map<string,DashboardRefundSettlementSnapshot[]>{const txById=new Map(transactions.map((t)=>[t.id,t])); const by=new Map<string,DashboardRefundSettlementSnapshot[]>(); for(const r of refunds){const method=String(r.method||"").toUpperCase(); const status=String(r.status||"").toUpperCase(); let settlement:DashboardRefundSettlementSnapshot["settlement"]=null; const tx=r.walletTransactionId?txById.get(r.walletTransactionId):undefined; const txAt=asDate(tx?.createdAt); if(method==="COD"&&tx&&tx.shopId===context.shopId&&tx.customerProfileId===context.customerProfileId&&tx.direction==="CREDIT"&&tx.transactionType==="COD_REFUND_CREDIT"&&tx.sourceType==="REFUND_REQUEST"&&tx.sourceId===r.id&&Number.isInteger(tx.amount)&&tx.amount>0&&Boolean(tx.currency)&&txAt) settlement={type:"STORE_CREDIT",transactionId:tx.id,transactionType:"COD_REFUND_CREDIT",amountPaise:tx.amount,currency:tx.currency,issuedAt:txAt}; else if(method!=="COD"&&["PAID","COMPLETED","SETTLED"].includes(status)) settlement={type:"ORIGINAL_PAYMENT_METHOD",completedAt:asDate(r.paidAt)||asDate(r.updatedAt)}; const snap={refundRequestId:r.id,requestId:r.orderActionRequestId,method,status,amountPaise:r.amount,currency:r.currency,createdAt:asDate(r.createdAt),updatedAt:asDate(r.updatedAt),paidAt:asDate(r.paidAt),settlement}; const k=String(r.orderActionRequestId||""); by.set(k,[...(by.get(k)||[]),snap]);} return by;}

export function buildDashboardExchangeProgress(request:DashboardExchangeProgressInput):DashboardExchangeProgressStepSnapshot[]{
 const status=String(request.status||"").trim().toUpperCase(); const p=request.payment; const r=request.reverseShipment; const f=request.replacementShipment;
 const done:Record<string,boolean>={REQUESTED:Boolean(request.requestedAt),FEE_PAID:p?.status==="PAID"||["PAYMENT_RECEIVED","APPROVED","PICKUP_PENDING","PICKUP_SCHEDULED","PICKUP_COMPLETED","ITEM_RECEIVED","REPLACEMENT_PROCESSING","REPLACEMENT_SHIPPED","CLOSED"].includes(status),PICKUP_SCHEDULED:["SCHEDULED","IN_TRANSIT","DELIVERED"].includes(String(r?.statusCode||""))||["PICKUP_SCHEDULED","PICKUP_COMPLETED","ITEM_RECEIVED","REPLACEMENT_PROCESSING","REPLACEMENT_SHIPPED","CLOSED"].includes(status),PICKED_UP:["IN_TRANSIT","DELIVERED"].includes(String(r?.statusCode||""))||["PICKUP_COMPLETED","ITEM_RECEIVED","REPLACEMENT_PROCESSING","REPLACEMENT_SHIPPED","CLOSED"].includes(status),ITEM_RECEIVED:r?.statusCode==="DELIVERED"||["ITEM_RECEIVED","REPLACEMENT_PROCESSING","REPLACEMENT_SHIPPED","CLOSED"].includes(status),REPLACEMENT_SHIPPED:Boolean(f?.awb)||["REPLACEMENT_SHIPPED","CLOSED"].includes(status),COMPLETED:status==="CLOSED"};
 return [["REQUESTED","Requested"],["FEE_PAID","Fee Paid"],["PICKUP_SCHEDULED","Pickup Scheduled"],["PICKED_UP","Picked Up"],["ITEM_RECEIVED","Item Received"],["REPLACEMENT_SHIPPED","Replacement Shipped"],["COMPLETED","Completed"]].map(([key,l])=>({key,label:l,state:done[key]?"COMPLETED":"PENDING"}));
}

export async function loadDashboardOrderRequests(input:{context:CustomerDashboardContext;orderNumbers:string[]}):Promise<DashboardOrderRequestAggregation>{
 const orderNumbers=uniqueOrderNumbers(input.orderNumbers); const byOrderNumber:DashboardOrderRequestSnapshotMap=new Map(orderNumbers.map(n=>[n,{cancellation:null,exchange:null,issue:null,cancellations:[],exchanges:[],issues:[],timeline:[],activeConflict:null}])); if(!orderNumbers.length)return{byOrderNumber,openRequestCount:0}; const base={shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,orderNumber:{in:orderNumbers}};
 const [cans,exs,issues]=await Promise.all([
  deps.orderActionRequest.findMany({where:{...base,requestType:"CANCELLATION"},orderBy:{requestedAt:"desc"},select:{id:true,orderNumber:true,status:true,requestedAt:true,updatedAt:true,orderAmountSnapshot:true}}),
  deps.orderActionRequest.findMany({where:{...base,requestType:"EXCHANGE"},orderBy:{requestedAt:"desc"},select:{id:true,orderNumber:true,status:true,requestedAt:true,updatedAt:true,payments:{where:{purpose:"REVERSE_PICKUP_FEE"},orderBy:{createdAt:"desc"},select:{status:true,paidAt:true,amount:true,currency:true}},shipments:{select:{id:true,direction:true,carrier:true,awb:true,trackingUrl:true,status:true,pickupAt:true,shippedAt:true,deliveredAt:true,updatedAt:true}}}}),
  deps.orderActionRequest.findMany({where:{...base,requestType:"ISSUE"},orderBy:{requestedAt:"desc"},select:{id:true,orderNumber:true,status:true,requestedAt:true,updatedAt:true}})
 ]);
 const requestIds=[...cans,...exs,...issues].map((r)=>r.id);
 const refunds=requestIds.length?await deps.refundRequest.findMany({where:{shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,orderActionRequestId:{in:requestIds},orderActionRequest:{shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,orderNumber:{in:orderNumbers}}},orderBy:{updatedAt:"desc"},select:{id:true,status:true,method:true,amount:true,currency:true,orderActionRequestId:true,walletTransactionId:true,paidAt:true,createdAt:true,updatedAt:true}}):[];
 const walletTransactionIds=Array.from(new Set(refunds.map((r)=>r.walletTransactionId).filter(Boolean) as string[]));
 const walletTransactions=walletTransactionIds.length?await deps.walletTransaction.findMany({where:{shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,id:{in:walletTransactionIds},sourceType:"REFUND_REQUEST"},select:{id:true,shopId:true,customerProfileId:true,direction:true,transactionType:true,amount:true,currency:true,sourceType:true,sourceId:true,createdAt:true}}):[];
 const refundSnapshotsBy=normalizeRefunds(refunds,walletTransactions,input.context);
 const refundsBy=new Map<string,RefundRow[]>(); for(const r of refunds){const k=String(r.orderActionRequestId||""); refundsBy.set(k,[...(refundsBy.get(k)||[]),r]);}
 for(const r of cans){const orderNumber=normalizeOrderNumber(r.orderNumber); const snap=byOrderNumber.get(orderNumber); if(!snap)continue; const outcome=deriveCancellationOutcome({cancellationStatus:r.status,orderAmountSnapshot:r.orderAmountSnapshot,refundRequests:refundsBy.get(r.id)||[]}); snap.cancellations.push({id:r.id,status:r.status,requestedAt:r.requestedAt,updatedAt:r.updatedAt??null,orderAmountSnapshotPaise:r.orderAmountSnapshot==null?null:Number(r.orderAmountSnapshot),refundOutcome:{requirementLabel:outcome.refundRequirementLabel,customerExplanation:outcome.customerExplanation,refundStatusCode:outcome.refundRequest?.status??null},blocking:isCancellationStatusBlocking(r.status),refunds:refundSnapshotsBy.get(r.id)||[]});}
 for(const r of exs){const orderNumber=normalizeOrderNumber(r.orderNumber); const snap=byOrderNumber.get(orderNumber); if(!snap)continue; const rev=shipment(r.shipments?.find((s)=>s.direction==="REVERSE_PICKUP"),"REVERSE_PICKUP"); const repl=shipment(r.shipments?.find((s)=>s.direction==="FORWARD_REPLACEMENT"||s.direction==="REPLACEMENT"),"REPLACEMENT"); const payment=r.payments?.[0]?{status:r.payments[0].status,paidAt:r.payments[0].paidAt??null,amountPaise:r.payments[0].amount,currency:r.payments[0].currency}:null; const active=ACTIVE_EXCHANGE_STATUSES.includes(String(r.status).toUpperCase() as (typeof ACTIVE_EXCHANGE_STATUSES)[number]); snap.exchanges.push({id:r.id,status:r.status,requestedAt:r.requestedAt,updatedAt:r.updatedAt??null,blocking:active,active,payment,reverseShipment:rev,replacementShipment:repl,progress:buildDashboardExchangeProgress({id:r.id,status:r.status,requestedAt:r.requestedAt,payment,reverseShipment:rev,replacementShipment:repl}),refunds:refundSnapshotsBy.get(r.id)||[]});}
 for(const r of issues){const orderNumber=normalizeOrderNumber(r.orderNumber); const snap=byOrderNumber.get(orderNumber); if(!snap)continue; snap.issues.push({id:r.id,status:r.status,requestedAt:r.requestedAt,updatedAt:r.updatedAt??null,blocking:isIssueStatusBlocking(r.status),refunds:refundSnapshotsBy.get(r.id)||[]});}
 for(const snap of byOrderNumber.values()){snap.cancellation=snap.cancellations[0]||null; snap.exchange=snap.exchanges[0]||null; snap.issue=snap.issues[0]||null; snap.timeline=buildCustomerRequestTimeline(snap);}
 let openRequestCount=0; for(const snap of byOrderNumber.values()){if(snap.cancellation?.blocking)openRequestCount++; if(snap.exchange?.active)openRequestCount++; if(snap.issue?.blocking)openRequestCount++; const active=findActiveRequest([snap.cancellation&&{requestType:"CANCELLATION",status:snap.cancellation.status},snap.exchange&&{requestType:"EXCHANGE",status:snap.exchange.status},snap.issue&&{requestType:"ISSUE",status:snap.issue.status}].filter(Boolean) as Array<{requestType:ActiveRequestType;status:string}>); snap.activeConflict=active?{requestType:active.requestType,status:active.status,lockReason:formatRequestLockReason(active)||"Request is active."}:null;}
 return{byOrderNumber,openRequestCount};
}

const iso=(d:Date|null|undefined)=>d?d.toISOString():null;
export function buildDashboardOrderRequestsDto(snapshot:DashboardOrderRequestSnapshot):DashboardOrderRequestsDto{return{cancellation:snapshot.cancellation?{id:snapshot.cancellation.id,type:"CANCELLATION",statusCode:String(snapshot.cancellation.status).toUpperCase(),statusLabel:label(snapshot.cancellation.status),requestedAt:snapshot.cancellation.requestedAt.toISOString(),updatedAt:iso(snapshot.cancellation.updatedAt),customerMessage:snapshot.cancellation.refundOutcome.customerExplanation}:null,exchange:snapshot.exchange?{id:snapshot.exchange.id,statusCode:String(snapshot.exchange.status).toUpperCase(),statusLabel:label(snapshot.exchange.status),requestedAt:snapshot.exchange.requestedAt.toISOString(),payment:snapshot.exchange.payment?{status:snapshot.exchange.payment.status,amountPaise:snapshot.exchange.payment.amountPaise,currency:snapshot.exchange.payment.currency,paidAt:iso(snapshot.exchange.payment.paidAt)}:null,reverseShipment:snapshot.exchange.reverseShipment as unknown as DashboardShipmentDto|null,replacementShipment:snapshot.exchange.replacementShipment as unknown as DashboardShipmentDto|null,progress:snapshot.exchange.progress as DashboardProgressStepDto[]} as DashboardExchangeRequestDto:null,issue:snapshot.issue?{id:snapshot.issue.id,type:"ISSUE",statusCode:String(snapshot.issue.status).toUpperCase(),statusLabel:label(snapshot.issue.status),requestedAt:snapshot.issue.requestedAt.toISOString(),updatedAt:iso(snapshot.issue.updatedAt),customerMessage:null}:null};}
