export type CustomerDashboardSettings = {
  enabled: boolean;
  branding: { accountLabel: string; heading: string; logoUrl: string | null; primaryColor: string | null; backgroundColor: string | null; surfaceColor: string | null; textColor: string | null; borderRadiusPx: number; };
  links: { supportUrl: string | null; continueShoppingUrl: string | null; dashboardUrl: string; logoutRedirectUrl: string; };
  sections: { showProfile: boolean; showSummary: boolean; showOrders: boolean; showWallet: boolean; showWalletTransactions: boolean; showSavedAddress: boolean; showTracking: boolean; showRequestStatuses: boolean; };
  orders: { initialOrderLimit: number; showOrderImages: boolean; showFinancialStatus: boolean; showFulfillmentStatus: boolean; };
  copy: { loginRequiredTitle: string; loginRequiredMessage: string; emptyOrdersMessage: string; temporaryErrorMessage: string; supportLabel: string; continueShoppingLabel: string; logoutLabel: string; };
  version: number;
};
export type CustomerDashboardSettingsInput = Omit<CustomerDashboardSettings, "version"> & { version?: number };
export type CustomerDashboardThemeOverrides = { heading?: string; accountLabel?: string; supportUrl?: string | null; continueShoppingUrl?: string | null; sections?: Partial<CustomerDashboardSettings["sections"]>; orders?: Partial<Pick<CustomerDashboardSettings["orders"], "initialOrderLimit">>; };
export type CustomerDashboardPresentationConfig = Omit<CustomerDashboardSettings, "version">;
export const CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY = "customer_dashboard_settings";
export const DEFAULT_CUSTOMER_DASHBOARD_SETTINGS: CustomerDashboardSettings = Object.freeze({ enabled: true, branding: { accountLabel: "My Account", heading: "My Account", logoUrl: null, primaryColor: null, backgroundColor: null, surfaceColor: null, textColor: null, borderRadiusPx: 16 }, links: { supportUrl: "/pages/contact", continueShoppingUrl: "/collections/all", dashboardUrl: "/apps/megaska/account", logoutRedirectUrl: "/" }, sections: { showProfile: true, showSummary: true, showOrders: true, showWallet: true, showWalletTransactions: true, showSavedAddress: true, showTracking: true, showRequestStatuses: true }, orders: { initialOrderLimit: 10, showOrderImages: true, showFinancialStatus: true, showFulfillmentStatus: true }, copy: { loginRequiredTitle: "Sign in to view your account", loginRequiredMessage: "Please verify your mobile number to continue.", emptyOrdersMessage: "You have not placed any orders yet.", temporaryErrorMessage: "We could not load your account right now.", supportLabel: "Need help?", continueShoppingLabel: "Continue shopping", logoutLabel: "Logout" }, version: 1 });
const MAX: Record<string, number> = { accountLabel: 60, heading: 100, message: 300, label: 60 };
export class CustomerDashboardSettingsValidationError extends Error { issues: string[]; constructor(issues: string[]) { super(issues.join("; ")); this.name = "CustomerDashboardSettingsValidationError"; this.issues = issues; } }
function obj(v: unknown): Record<string, unknown> { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {}; }
function cloneDefaults(): CustomerDashboardSettings { return JSON.parse(JSON.stringify(DEFAULT_CUSTOMER_DASHBOARD_SETTINGS)); }
function cleanText(v: unknown, fallback: string, max: number, issues?: string[], path?: string) { if (typeof v !== "string") return fallback; const s = v.trim(); if (!s) return fallback; if (/[[\]<>]|<\/?\w|javascript:/i.test(s) || /[\u0000-\u001f\u007f]/.test(s)) { issues?.push(`${path} contains unsafe text`); return fallback; } if (s.length > max) { issues?.push(`${path} is too long`); return fallback; } return s; }
function color(v: unknown, fallback: string | null, issues?: string[], path?: string) { if (v == null || v === "") return null; if (typeof v !== "string" || !/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v.trim())) { issues?.push(`${path} must be a hex color`); return fallback; } return v.trim(); }
function intRange(v: unknown, fallback: number, min: number, max: number, issues?: string[], path?: string) { if (typeof v !== "number" || !Number.isInteger(v) || v < min || v > max) { if (v !== undefined) issues?.push(`${path} must be an integer between ${min} and ${max}`); return fallback; } return v; }
function bool(v: unknown, fallback: boolean) { return typeof v === "boolean" ? v : fallback; }
export function validateDashboardUrl(v: unknown, fallback: string | null, opts: { allowHttps: boolean; required?: boolean }, issues?: string[], path = "url") { if (v == null || v === "") return opts.required ? (fallback || "/") : fallback; if (typeof v !== "string") { issues?.push(`${path} must be a URL path or HTTPS URL`); return fallback; } const s = v.trim(); if (s.startsWith("//") || /^(javascript|data):/i.test(s)) { issues?.push(`${path} is unsafe`); return fallback; } if (s.startsWith("/")) return s; try { const u = new URL(s); if (opts.allowHttps && u.protocol === "https:") return u.href; } catch {} issues?.push(`${path} must be a same-origin path${opts.allowHttps ? " or HTTPS URL" : ""}`); return fallback; }
export function normalizeCustomerDashboardSettings(value: unknown): CustomerDashboardSettings { return normalizeInternal(value).settings; }
export function validateCustomerDashboardSettingsInput(value: unknown): CustomerDashboardSettings { const r = normalizeInternal(value, true); if (r.issues.length) throw new CustomerDashboardSettingsValidationError(r.issues); return r.settings; }
function normalizeInternal(value: unknown, strict = false) { const d = cloneDefaults(), v = obj(value), issues: string[] = []; const b = obj(v.branding), l = obj(v.links), s = obj(v.sections), o = obj(v.orders), c = obj(v.copy); d.enabled = bool(v.enabled, d.enabled); d.branding = { accountLabel: cleanText(b.accountLabel, d.branding.accountLabel, MAX.accountLabel, strict ? issues : undefined, "branding.accountLabel"), heading: cleanText(b.heading, d.branding.heading, MAX.heading, strict ? issues : undefined, "branding.heading"), logoUrl: validateDashboardUrl(b.logoUrl, null, { allowHttps: true }, strict ? issues : undefined, "branding.logoUrl"), primaryColor: color(b.primaryColor, null, strict ? issues : undefined, "branding.primaryColor"), backgroundColor: color(b.backgroundColor, null, strict ? issues : undefined, "branding.backgroundColor"), surfaceColor: color(b.surfaceColor, null, strict ? issues : undefined, "branding.surfaceColor"), textColor: color(b.textColor, null, strict ? issues : undefined, "branding.textColor"), borderRadiusPx: intRange(b.borderRadiusPx, d.branding.borderRadiusPx, 0, 40, strict ? issues : undefined, "branding.borderRadiusPx") };
  d.links = { supportUrl: validateDashboardUrl(l.supportUrl, d.links.supportUrl, { allowHttps: true }, strict ? issues : undefined, "links.supportUrl"), continueShoppingUrl: validateDashboardUrl(l.continueShoppingUrl, d.links.continueShoppingUrl, { allowHttps: false }, strict ? issues : undefined, "links.continueShoppingUrl"), dashboardUrl: validateDashboardUrl(l.dashboardUrl, d.links.dashboardUrl, { allowHttps: false, required: true }, strict ? issues : undefined, "links.dashboardUrl") || d.links.dashboardUrl, logoutRedirectUrl: validateDashboardUrl(l.logoutRedirectUrl, d.links.logoutRedirectUrl, { allowHttps: false, required: true }, strict ? issues : undefined, "links.logoutRedirectUrl") || d.links.logoutRedirectUrl };
  for (const k of Object.keys(d.sections) as Array<keyof typeof d.sections>) d.sections[k] = bool(s[k], d.sections[k]);
  d.orders = { initialOrderLimit: intRange(o.initialOrderLimit, d.orders.initialOrderLimit, 1, 50, strict ? issues : undefined, "orders.initialOrderLimit"), showOrderImages: bool(o.showOrderImages, d.orders.showOrderImages), showFinancialStatus: bool(o.showFinancialStatus, d.orders.showFinancialStatus), showFulfillmentStatus: bool(o.showFulfillmentStatus, d.orders.showFulfillmentStatus) };
  d.copy = { loginRequiredTitle: cleanText(c.loginRequiredTitle, d.copy.loginRequiredTitle, MAX.heading, strict ? issues : undefined, "copy.loginRequiredTitle"), loginRequiredMessage: cleanText(c.loginRequiredMessage, d.copy.loginRequiredMessage, MAX.message, strict ? issues : undefined, "copy.loginRequiredMessage"), emptyOrdersMessage: cleanText(c.emptyOrdersMessage, d.copy.emptyOrdersMessage, MAX.message, strict ? issues : undefined, "copy.emptyOrdersMessage"), temporaryErrorMessage: cleanText(c.temporaryErrorMessage, d.copy.temporaryErrorMessage, MAX.message, strict ? issues : undefined, "copy.temporaryErrorMessage"), supportLabel: cleanText(c.supportLabel, d.copy.supportLabel, MAX.label, strict ? issues : undefined, "copy.supportLabel"), continueShoppingLabel: cleanText(c.continueShoppingLabel, d.copy.continueShoppingLabel, MAX.label, strict ? issues : undefined, "copy.continueShoppingLabel"), logoutLabel: cleanText(c.logoutLabel, d.copy.logoutLabel, MAX.label, strict ? issues : undefined, "copy.logoutLabel") };
  d.version = intRange(v.version, d.version, 1, 999999, undefined, "version"); return { settings: d, issues }; }
export function mergeCustomerDashboardPresentationConfig(input: { saved: CustomerDashboardSettings; themeOverrides?: Partial<CustomerDashboardThemeOverrides> }): CustomerDashboardPresentationConfig { const saved = normalizeCustomerDashboardSettings(input.saved); const out = JSON.parse(JSON.stringify(saved)); delete out.version; const t = obj(input.themeOverrides); if (typeof t.heading === "string") out.branding.heading = cleanText(t.heading, out.branding.heading, MAX.heading); if (typeof t.accountLabel === "string") out.branding.accountLabel = cleanText(t.accountLabel, out.branding.accountLabel, MAX.accountLabel); out.links.supportUrl = validateDashboardUrl(t.supportUrl, out.links.supportUrl, { allowHttps: true }); out.links.continueShoppingUrl = validateDashboardUrl(t.continueShoppingUrl, out.links.continueShoppingUrl, { allowHttps: false }); const ts = obj(t.sections); for (const k of Object.keys(out.sections)) if (typeof ts[k] === "boolean") out.sections[k] = Boolean(out.sections[k] && ts[k]); const to = obj(t.orders); out.orders.initialOrderLimit = intRange(to.initialOrderLimit, out.orders.initialOrderLimit, 1, 50); return out; }
