/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "../db/prisma.ts";
import { CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY, CustomerDashboardSettingsValidationError, normalizeCustomerDashboardSettings, validateCustomerDashboardSettingsInput, type CustomerDashboardSettings, type CustomerDashboardSettingsInput } from "./settings-shared.ts";
export * from "./settings-shared.ts";
type Db = typeof prisma;
type Audit = (eventType: string, entityType: string, entityId: string | null, payload?: unknown) => Promise<unknown>;
async function defaultAudit(eventType: string, entityType: string, entityId: string | null, payload?: unknown) { await (prisma as any).auditEvent.create({ data: { actorType: "admin", actorId: null, eventType, entityType, entityId, payload } }); }
function groupsChanged(a: CustomerDashboardSettings, b: CustomerDashboardSettings) { return (["enabled", "branding", "links", "sections", "orders", "copy"] as const).filter((k) => JSON.stringify(a[k]) !== JSON.stringify(b[k])); }
export async function getCustomerDashboardSettingsForShop(shopId: string, deps: { db?: Db; audit?: Audit } = {}): Promise<CustomerDashboardSettings> { if (!shopId) return normalizeCustomerDashboardSettings(null); const db = deps.db || prisma; const row = await (db as any).shopModuleConfig.findUnique({ where: { shopId_moduleKey: { shopId, moduleKey: CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY } } }); const settings = normalizeCustomerDashboardSettings(row?.config); await (deps.audit || defaultAudit)?.("customer_dashboard.settings.viewed", "CustomerDashboardSettings", row?.id || null, { shopId, version: settings.version }).catch(() => undefined); return settings; }
export async function updateCustomerDashboardSettingsForShop(input: { shopId: string; settings: CustomerDashboardSettingsInput }, deps: { db?: Db; audit?: Audit } = {}): Promise<CustomerDashboardSettings> { if (!input.shopId) throw new CustomerDashboardSettingsValidationError(["shopId is required"]); const db = deps.db || prisma; const existing = await (db as any).shopModuleConfig.findUnique({ where: { shopId_moduleKey: { shopId: input.shopId, moduleKey: CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY } } }); const previous = normalizeCustomerDashboardSettings(existing?.config); const normalized = validateCustomerDashboardSettingsInput(input.settings); const next = { ...normalized, version: previous.version + 1 }; const row = await (db as any).shopModuleConfig.upsert({ where: { shopId_moduleKey: { shopId: input.shopId, moduleKey: CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY } }, create: { shopId: input.shopId, moduleKey: CUSTOMER_DASHBOARD_SETTINGS_MODULE_KEY, enabled: next.enabled, config: next }, update: { enabled: next.enabled, config: next } }); const changedFieldGroups = groupsChanged(previous, next); const audit = deps.audit || defaultAudit; await audit?.("customer_dashboard.settings.updated", "CustomerDashboardSettings", row.id || null, { shopId: input.shopId, version: next.version, changedFieldGroups }).catch(() => undefined); if (previous.enabled !== next.enabled) await audit?.(next.enabled ? "customer_dashboard.settings.enabled" : "customer_dashboard.settings.disabled", "CustomerDashboardSettings", row.id || null, { shopId: input.shopId, version: next.version }).catch(() => undefined); if (changedFieldGroups.includes("branding")) await audit?.("customer_dashboard.branding.updated", "CustomerDashboardSettings", row.id || null, { shopId: input.shopId, version: next.version }).catch(() => undefined); return normalizeCustomerDashboardSettings(next); }
