/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_CUSTOMER_DASHBOARD_SETTINGS, CustomerDashboardSettingsValidationError, mergeCustomerDashboardPresentationConfig, normalizeCustomerDashboardSettings, updateCustomerDashboardSettingsForShop } from "./settings.ts";
test("defaults and malformed nested values normalize safely", () => { assert.deepEqual(normalizeCustomerDashboardSettings(null), DEFAULT_CUSTOMER_DASHBOARD_SETTINGS); const s = normalizeCustomerDashboardSettings({ branding: "bad", orders: { initialOrderLimit: 999 }, sections: { showWallet: false }, unknown: { polluted: true } }); assert.equal(s.branding.accountLabel, "My Account"); assert.equal(s.orders.initialOrderLimit, 10); assert.equal(s.sections.showWallet, false); assert.equal((s as any).unknown, undefined); });
test("strict validation rejects unsafe URLs colors and limits", async () => { const input:any = normalizeCustomerDashboardSettings(null); input.links.supportUrl = "javascript:alert(1)"; await assert.rejects(() => updateCustomerDashboardSettingsForShop({ shopId: "s", settings: input }, { db: fakeDb(), audit: async()=>{} }), CustomerDashboardSettingsValidationError); input.links.supportUrl = "https://example.com/help"; input.branding.primaryColor = "red"; await assert.rejects(() => updateCustomerDashboardSettingsForShop({ shopId: "s", settings: input }, { db: fakeDb(), audit: async()=>{} }), /hex color/); input.branding.primaryColor = "#fff"; input.orders.initialOrderLimit = 51; await assert.rejects(() => updateCustomerDashboardSettingsForShop({ shopId: "s", settings: input }, { db: fakeDb(), audit: async()=>{} }), /1 and 50/); });
test("shop scoping and version increments", async () => { const db = fakeDb(); const a:any = normalizeCustomerDashboardSettings(null); a.branding.heading = "Shop A"; const one = await updateCustomerDashboardSettingsForShop({ shopId: "a", settings: a }, { db, audit: async()=>{} }); assert.equal(one.version, 2); const two = await updateCustomerDashboardSettingsForShop({ shopId: "a", settings: one }, { db, audit: async()=>{} }); assert.equal(two.version, 3); assert.equal(db.rows.get("b:customer_dashboard_settings"), undefined); });
test("theme overrides may hide not enable wallet", () => { const saved = normalizeCustomerDashboardSettings({ sections: { showWallet: false } }); const merged = mergeCustomerDashboardPresentationConfig({ saved, themeOverrides: { sections: { showWallet: true }, heading: "Custom" } }); assert.equal(merged.sections.showWallet, false); assert.equal(merged.branding.heading, "Custom"); });
function fakeDb(){ const rows = new Map(); return { rows, shopModuleConfig: { findUnique: async ({where}:any)=>rows.get(`${where.shopId_moduleKey.shopId}:${where.shopId_moduleKey.moduleKey}`)||null, upsert: async ({where,create,update}:any)=>{ const key=`${where.shopId_moduleKey.shopId}:${where.shopId_moduleKey.moduleKey}`; const row={ id:key, ...(rows.has(key)?update:create) }; rows.set(key,row); return row; } } } as any; }
