/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from "node:assert/strict";
import test from "node:test";
import { refreshShopifyCheckoutPricing } from "./shopify-checkout-pricing-refresh.ts";

const money = (amount: string, currencyCode = "INR") => ({ shopMoney: { amount, currencyCode }, presentmentMoney: { amount, currencyCode } });
function draft(overrides: Record<string, unknown> = {}) { return { id: "gid://shopify/DraftOrder/1", currencyCode: "INR", taxesIncluded: true, updatedAt: "2026-07-20T12:00:00Z", subtotalPriceSet: money("1000"), totalDiscountsSet: money("100"), totalShippingPriceSet: money("0"), totalTaxSet: money("137.29"), totalPriceSet: money("900"), taxLines: [{ title: "GST", rate: .18, priceSet: money("137.29") }], ...overrides }; }
function harness(options: any = {}) {
  const state: any = { draftId: options.draftId || null, calls: [], writes: [], addressZip: options.addressZip || "560001" };
  const intent = { id: "intent-1", shopId: "shop-1", customerProfileId: "customer-1", cartSnapshot: { lines: [{ variant_id: 11, quantity: 2 }] }, shippingAmountPaise: options.shipping ?? 0, currency: "INR", discounts: [] };
  const db = { $transaction: async (fn: any) => fn(db), expressCheckoutIntent: { findFirst: async ({ where }: any) => where.shopId === "shop-1" ? intent : null }, expressCheckoutAddressSnapshot: { findFirst: async ({ where }: any) => where.shopId === "shop-1" && where.customerProfileId === "customer-1" ? { name: "A Customer", address1: "Street", address2: null, city: "Bengaluru", province: "KA", country: "IN", zip: state.addressZip, phone: "redacted" } : null }, shop: { findFirst: async ({ where }: any) => where.id === "shop-1" ? { shopDomain: "test.myshopify.com" } : null }, shopifyCheckoutPricingSnapshot: { findFirst: async () => state.draftId ? { shopifyDraftOrderId: state.draftId } : null } };
  const graphql = async (_domain: string, query: string, variables: any) => { state.calls.push({ query, variables }); const result = options.response || draft(); if (options.changeShippingDuringRefresh !== undefined) intent.shippingAmountPaise = options.changeShippingDuringRefresh; return query.includes("DraftOrderUpdate") ? { draftOrderUpdate: options.userErrors ? { draftOrder: null, userErrors: options.userErrors } : { draftOrder: result, userErrors: [] } } : { draftOrderCreate: options.userErrors ? { draftOrder: null, userErrors: options.userErrors } : { draftOrder: result, userErrors: [] } }; };
  const snapshots = { recordAuthoritativePricingSnapshot: async (write: any) => { if (options.persistFails) throw new Error("db"); state.writes.push(write); state.draftId = write.snapshot.shopifyDraftOrderId; return { publicId: "snapshot-1" }; } };
  return { state, deps: { db, graphql: options.transportFails ? async () => { throw new Error("network"); } : graphql, snapshots, now: () => new Date("2026-07-20T12:01:00Z"), audit: () => {} } };
}

test("creates from trusted cart, address, and zero-value shipping then persists CURRENT input", async () => { const h = harness(); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "address_confirmed" }, h.deps); assert.equal(result.ok, true); assert.match(h.state.calls[0].query, /draftOrderCreate/); assert.deepEqual(h.state.calls[0].variables.input.lineItems, [{ variantId: "gid:\/\/shopify\/ProductVariant\/11", quantity: 2 }]); assert.equal(h.state.calls[0].variables.input.shippingLine.price, "0.00"); assert.equal(h.state.writes[0].snapshot.totalPayableMinor, 90000); assert.equal(h.state.writes[0].snapshot.totalTaxMinor, 13729); assert.match(h.state.writes[0].snapshot.addressFingerprint, /^[a-f0-9]{64}$/); });
test("reuses checkout-owned Draft Order with update and non-zero shipping", async () => { const h = harness({ draftId: "gid://shopify/DraftOrder/1", shipping: 5000, response: draft({ totalShippingPriceSet: money("50"), totalPriceSet: money("950") }) }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "shipping_confirmed" }, h.deps); assert.equal(result.ok && result.reusedDraftOrder, true); assert.match(h.state.calls[0].query, /draftOrderUpdate/); assert.equal(h.state.calls[0].variables.id, "gid://shopify/DraftOrder/1"); assert.equal(h.state.writes[0].snapshot.shippingMinor, 5000); });
test("maps exclusive India fixture and preserves multiple titles", async () => { const response = draft({ taxesIncluded: false, totalTaxSet: money("162"), totalPriceSet: money("1062"), taxLines: [{ title: "Tax A", rate: .09, priceSet: money("81") }, { title: "Tax B", rate: .09, priceSet: money("81") }] }); const h = harness({ response }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" }, h.deps); assert.ok(result.ok); assert.equal(result.taxSummary.totalPayable, 106200); assert.deepEqual(result.taxSummary.taxLines.map(x => x.title), ["Tax A", "Tax B"]); });
test("supports global USD, included GBP, zero tax, and JPY zero-decimal responses", async () => { for (const [currency, total, included] of [["USD", "108", false], ["GBP", "100", true], ["JPY", "1000", false]] as const) { const m = (amount: string) => money(amount, currency); const response = draft({ currencyCode: currency, taxesIncluded: included, subtotalPriceSet: m(currency === "JPY" ? "1000" : "100"), totalDiscountsSet: m("0"), totalShippingPriceSet: m("0"), totalTaxSet: m(currency === "USD" ? "8" : "0"), totalPriceSet: m(total), taxLines: [] }); const h = harness({ response }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" }, h.deps); assert.ok(result.ok); assert.equal(result.taxSummary.totalPayable, currency === "JPY" ? 1000 : Number(total) * 100); } });
test("rejects mixed currency and malformed money without snapshot writes", async () => { for (const response of [draft({ totalTaxSet: money("1", "USD") }), draft({ totalPriceSet: money("not-money") })]) { const h = harness({ response }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" }, h.deps); assert.deepEqual(result, { ok: false, code: "draft_order_pricing_invalid", retryable: false }); assert.equal(h.state.writes.length, 0); } });
test("transport and user errors preserve prior snapshot", async () => { for (const options of [{ transportFails: true }, { draftId: "gid://shopify/DraftOrder/1", userErrors: [{ field: ["input"], message: "invalid address containing PII" }] }]) { const h = harness(options); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" }, h.deps); assert.equal(result.ok, false); assert.equal(h.state.writes.length, 0); } });
test("tenant isolation refuses wrong shop before address, Draft Order, or Shopify access", async () => { const h = harness({ draftId: "gid://shopify/DraftOrder/1" }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-2", checkoutIntentId: "intent-1", reason: "manual_refresh" }, h.deps); assert.deepEqual(result, { ok: false, code: "checkout_intent_not_found", retryable: false }); assert.equal(h.state.calls.length, 0); });
test("changed trusted address changes fingerprint and persistence failure is typed", async () => { const h = harness(); await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "address_confirmed" }, h.deps); const first = h.state.writes[0].snapshot.addressFingerprint; h.state.addressZip = "560002"; await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "address_confirmed" }, h.deps); assert.notEqual(first, h.state.writes[1].snapshot.addressFingerprint); const failed = harness({ persistFails: true }); assert.deepEqual(await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" }, failed.deps), { ok: false, code: "pricing_snapshot_persist_failed", retryable: true }); });
test("serialized concurrent refresh creates once, then updates and upserts the same snapshot", async () => { const h = harness(); let tail = Promise.resolve(); h.deps.db.$transaction = (fn: any) => { const run = tail.then(() => fn(h.deps.db)); tail = run.then(() => undefined, () => undefined); return run; }; const input = { shopId: "shop-1", checkoutIntentId: "intent-1", reason: "manual_refresh" as const }; const results = await Promise.all([refreshShopifyCheckoutPricing(input, h.deps), refreshShopifyCheckoutPricing(input, h.deps)]); assert.ok(results.every(result => result.ok)); assert.equal(h.state.calls.filter((call: any) => call.query.includes("DraftOrderCreate")).length, 1); assert.equal(h.state.calls.filter((call: any) => call.query.includes("DraftOrderUpdate")).length, 1); assert.deepEqual(h.state.writes.map((write: any) => write.shopId + write.checkoutIntentId), ["shop-1intent-1", "shop-1intent-1"]); assert.equal(h.state.writes[0].snapshot.cartFingerprint, h.state.writes[1].snapshot.cartFingerprint); });
test("discards a Shopify response when trusted pricing inputs change during refresh", async () => { const h = harness({ shipping: 0, changeShippingDuringRefresh: 5000 }); const result = await refreshShopifyCheckoutPricing({ shopId: "shop-1", checkoutIntentId: "intent-1", reason: "shipping_confirmed" }, h.deps); assert.deepEqual(result, { ok: false, code: "pricing_inputs_changed", retryable: true }); assert.equal(h.state.writes.length, 0); });
