/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "../../../db/prisma.ts";
import { deriveCancellationOutcome, evaluateCancellationEligibility } from "../../../exchange/cancellation.ts";
import { findActiveRequest, formatRequestLockReason, orderNumberVariants } from "../../../exchange/request-interlocks.ts";
import type { CustomerDashboardActionResult, CancellationActionPayload } from "../contract.ts";
import type { CustomerDashboardActionContext } from "../context.ts";
import type { CustomerOwnedOrderSnapshot } from "../ownership.ts";
import { CustomerDashboardActionError } from "../errors.ts";

type Deps={findRequests:(a:unknown)=>Promise<any[]>;createRequest:(a:unknown)=>Promise<any>;findRefunds:(a:unknown)=>Promise<any[]>}; const def:Deps={findRequests:(a)=>prisma.orderActionRequest.findMany(a as never),createRequest:(a)=>prisma.orderActionRequest.create(a as never),findRefunds:(a)=>(prisma as any).refundRequest.findMany(a)}; let deps=def; export function setCancellationActionHandlerDependenciesForTest(o:Partial<Deps>){deps={...def,...o};} export function resetCancellationActionHandlerDependenciesForTest(){deps=def;}
export async function executeCancellationAction(input:{context:CustomerDashboardActionContext;order:CustomerOwnedOrderSnapshot;payload:CancellationActionPayload}):Promise<CustomerDashboardActionResult>{ const eligibility=evaluateCancellationEligibility({fulfillmentStatus:input.order.fulfillmentStatus,financialStatus:input.order.financialStatus,fulfilledAt:input.order.fulfilledAt instanceof Date?input.order.fulfilledAt.toISOString():input.order.fulfilledAt,deliveredAt:input.order.deliveredAt instanceof Date?input.order.deliveredAt.toISOString():input.order.deliveredAt,orderCancelled:false}); if(!eligibility.eligible) throw new CustomerDashboardActionError({code:"ACTION_NOT_AVAILABLE",message:eligibility.reason||"Cancellation is not available for this order.",status:409}); const active= findActiveRequest(await deps.findRequests({where:{shopId:input.context.shopId,customerProfileId:input.context.customerProfileId,requestType:{in:["CANCELLATION","EXCHANGE","ISSUE"]},orderNumber:{in:orderNumberVariants(input.order.orderNumber)}},select:{id:true,requestType:true,status:true},orderBy:{requestedAt:"desc"}})); if(active) throw new CustomerDashboardActionError({code:active.requestType==="CANCELLATION"?"REQUEST_ALREADY_EXISTS":"REQUEST_CONFLICT",message:active.requestType==="CANCELLATION"?"A cancellation request already exists for this order.":`Cannot request cancellation while ${formatRequestLockReason(active)?.toLowerCase()}`,status:409}); const created=await deps.createRequest({data:{requestType:"CANCELLATION",customerProfileId:input.context.customerProfileId,shopId:input.context.shopId,shopifyOrderId:input.order.shopifyOrderId,orderNumber:input.order.orderNumber,status:"OPEN",reason:input.payload.reasonCode,customerNote:input.payload.reasonText??null,orderAmountSnapshot:String(input.order.totalPaise||0),eligibilityDecision:"ELIGIBLE",eligibilityReason:eligibility.reason,megaskaOrderId:input.order.id},include:{items:true,payments:{orderBy:{createdAt:"desc"},take:1}}}); const refunds=await deps.findRefunds({where:{orderActionRequestId:created.id},orderBy:{updatedAt:"desc"}}); deriveCancellationOutcome({cancellationStatus:created.status,orderAmountSnapshot:created.orderAmountSnapshot,refundRequests:refunds}); return { ok:true, actionType:"CANCELLATION", requestId:created.id, statusCode:String(created.status).toUpperCase(), statusLabel:"Cancellation requested", customerMessage:"Your cancellation request has been submitted.", orderId:input.order.id, orderNumber:input.order.orderNumber, createdAt:(created.requestedAt??input.context.now).toISOString(), nextAction:{type:"REFRESH_DASHBOARD",url:null} }; }
