// Represents a customer's store-credit balance as a Shopify gift card, so it can
// be applied natively at Shopify Checkout (the modal-free architecture can't inject
// a custom tender at checkout). One persistent gift card per customer: the first
// grant creates it, later grants top it up (giftCardCredit). The full code is
// generated by us and stored encrypted (Shopify never returns it), so it can be
// shown in the app dashboard for repeat visitors.
//
// Phase 1: the service + its Shopify calls, dependency-injected and unit-tested.
// Nothing calls it in production yet - grant wiring, order reconciliation and the
// dashboard/drawer UI land in later PRs. The exact Admin gift-card mutation shapes
// must be validated against the store's Admin API version before real money flows.
import { encryptGiftCardCode, decryptGiftCardCode, generateGiftCardCode } from "./gift-card-crypto";

type Graphql = <T>(query: string, variables?: Record<string, unknown>, options?: { shopDomain?: string | null }) => Promise<T>;

// Minimal view of a WalletAccount row + its gift-card link.
export type GiftCardWalletAccount = {
  id: string;
  currency: string;
  shopifyGiftCardId: string | null;
  shopifyGiftCardLast4: string | null;
  giftCardCodeEnc: string | null;
};

export type GiftCardDeps = {
  graphql?: Graphql;
  // Resolve (or lazily create) the customer's WalletAccount and return its gift-card link.
  loadAccount?: (params: { shopId: string; customerProfileId: string; currency: string }) => Promise<GiftCardWalletAccount | null>;
  // Persist the gift-card link (id, last 4, encrypted code) back onto the WalletAccount.
  saveGiftCardRef?: (params: { accountId: string; shopifyGiftCardId: string; shopifyGiftCardLast4: string; giftCardCodeEnc: string }) => Promise<void>;
};

export type CreditResult =
  | { ok: true; created: boolean; giftCardId: string; last4: string }
  | { ok: false; reason: string };

export type ReadResult =
  | { ok: true; present: false }
  | { ok: true; present: true; giftCardId: string; last4: string; code: string | null; balancePaise: number }
  | { ok: false; reason: string };

const CREATE_MUTATION = `mutation LoopD2CGiftCardCreate($input: GiftCardCreateInput!) {
  giftCardCreate(input: $input) {
    giftCard { id lastCharacters balance { amount currencyCode } }
    userErrors { field message }
  }
}`;

const CREDIT_MUTATION = `mutation LoopD2CGiftCardCredit($id: ID!, $creditInput: GiftCardCreditInput!) {
  giftCardCredit(id: $id, creditInput: $creditInput) {
    giftCardCreditTransaction { amount { amount currencyCode } }
    userErrors { field message }
  }
}`;

const READ_QUERY = `query LoopD2CGiftCard($id: ID!) {
  giftCard(id: $id) { id lastCharacters balance { amount currencyCode } }
}`;

// Paise (integer minor units) <-> Shopify's Decimal major-unit string.
export function paiseToMajorString(paise: number): string {
  return (Math.max(0, Math.round(Number(paise) || 0)) / 100).toFixed(2);
}
export function majorStringToPaise(amount: string | number | null | undefined): number {
  return Math.max(0, Math.round(Number(amount || 0) * 100));
}

async function loadAccountDefault(params: { shopId: string; customerProfileId: string; currency: string }): Promise<GiftCardWalletAccount | null> {
  const { prisma } = await import("../db/prisma");
  const rows = await prisma.$queryRaw<Array<GiftCardWalletAccount>>`
    SELECT "id", "currency", "shopifyGiftCardId", "shopifyGiftCardLast4", "giftCardCodeEnc"
    FROM "WalletAccount"
    WHERE "shopId" = ${params.shopId} AND "customerProfileId" = ${params.customerProfileId} AND "currency" = ${params.currency}
    LIMIT 1
  `;
  return rows[0] || null;
}

async function saveGiftCardRefDefault(params: { accountId: string; shopifyGiftCardId: string; shopifyGiftCardLast4: string; giftCardCodeEnc: string }): Promise<void> {
  const { prisma } = await import("../db/prisma");
  await prisma.$executeRaw`
    UPDATE "WalletAccount"
    SET "shopifyGiftCardId" = ${params.shopifyGiftCardId},
        "shopifyGiftCardLast4" = ${params.shopifyGiftCardLast4},
        "giftCardCodeEnc" = ${params.giftCardCodeEnc},
        "updatedAt" = NOW()
    WHERE "id" = ${params.accountId}
  `;
}

// Credit a customer's store-credit gift card by `amountPaise`, creating the card
// on the first grant. Idempotency for grants is the caller's responsibility (the
// WalletTransaction ledger already dedupes by source), so this performs the raw
// create/top-up.
export async function creditCustomerGiftCard(
  params: { shopId: string; shopDomain: string; customerProfileId: string; amountPaise: number; currency?: string; note?: string },
  deps: GiftCardDeps = {},
): Promise<CreditResult> {
  const amountPaise = Math.max(0, Math.round(Number(params.amountPaise) || 0));
  if (amountPaise <= 0) return { ok: false, reason: "amount_must_be_positive" };
  const currency = String(params.currency || "INR").trim() || "INR";

  const graphql = deps.graphql ?? (await import("../shopify/admin")).shopifyAdminGraphql;
  const loadAccount = deps.loadAccount ?? loadAccountDefault;
  const saveGiftCardRef = deps.saveGiftCardRef ?? saveGiftCardRefDefault;

  const account = await loadAccount({ shopId: params.shopId, customerProfileId: params.customerProfileId, currency });
  if (!account) return { ok: false, reason: "wallet_account_not_found" };

  // Top up an existing card.
  if (account.shopifyGiftCardId) {
    const res = await graphql<{ giftCardCredit: { giftCardCreditTransaction?: unknown; userErrors: Array<{ message?: string }> } }>(
      CREDIT_MUTATION,
      { id: account.shopifyGiftCardId, creditInput: { creditAmount: { amount: paiseToMajorString(amountPaise), currencyCode: currency }, note: params.note || "LoopD2C store credit" } },
      { shopDomain: params.shopDomain },
    );
    const errs = res?.giftCardCredit?.userErrors ?? [];
    if (errs.length) return { ok: false, reason: errs.map((e) => e.message).filter(Boolean).join("; ") || "credit_failed" };
    return { ok: true, created: false, giftCardId: account.shopifyGiftCardId, last4: account.shopifyGiftCardLast4 || "" };
  }

  // First grant: create the card with our own code so we can show it later.
  const code = generateGiftCardCode();
  const created = await graphql<{ giftCardCreate: { giftCard?: { id: string; lastCharacters?: string } | null; userErrors: Array<{ message?: string }> } }>(
    CREATE_MUTATION,
    { input: { initialValue: paiseToMajorString(amountPaise), code, note: params.note || `LoopD2C store credit · ${params.customerProfileId}` } },
    { shopDomain: params.shopDomain },
  );
  const errs = created?.giftCardCreate?.userErrors ?? [];
  if (errs.length) return { ok: false, reason: errs.map((e) => e.message).filter(Boolean).join("; ") || "create_failed" };
  const card = created?.giftCardCreate?.giftCard;
  if (!card?.id) return { ok: false, reason: "create_returned_no_id" };

  const last4 = String(card.lastCharacters || code.replace(/-/g, "").slice(-4));
  const codeEnc = encryptGiftCardCode(code);
  if (!codeEnc) return { ok: false, reason: "encryption_key_unavailable" };
  await saveGiftCardRef({ accountId: account.id, shopifyGiftCardId: card.id, shopifyGiftCardLast4: last4, giftCardCodeEnc: codeEnc });
  return { ok: true, created: true, giftCardId: card.id, last4 };
}

// Read the customer's gift-card balance + (decrypted) code for the dashboard/drawer.
export async function readCustomerGiftCard(
  params: { shopId: string; shopDomain: string; customerProfileId: string; currency?: string },
  deps: GiftCardDeps = {},
): Promise<ReadResult> {
  const currency = String(params.currency || "INR").trim() || "INR";
  const graphql = deps.graphql ?? (await import("../shopify/admin")).shopifyAdminGraphql;
  const loadAccount = deps.loadAccount ?? loadAccountDefault;

  const account = await loadAccount({ shopId: params.shopId, customerProfileId: params.customerProfileId, currency });
  if (!account || !account.shopifyGiftCardId) return { ok: true, present: false };

  const res = await graphql<{ giftCard?: { id: string; lastCharacters?: string; balance?: { amount?: string } | null } | null }>(
    READ_QUERY,
    { id: account.shopifyGiftCardId },
    { shopDomain: params.shopDomain },
  );
  const card = res?.giftCard;
  if (!card?.id) return { ok: false, reason: "gift_card_not_found" };
  return {
    ok: true,
    present: true,
    giftCardId: card.id,
    last4: String(card.lastCharacters || account.shopifyGiftCardLast4 || ""),
    code: decryptGiftCardCode(account.giftCardCodeEnc),
    balancePaise: majorStringToPaise(card.balance?.amount),
  };
}
