api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "gst-invoice-action"
uid = "66286b4f-6594-47bb-93ff-cf62aa22f6ab"
type = "ui_extension"

# Only 1 target can be specified for each Admin action extension
[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.order-details.action.render"
