import { adminGraphql } from "./admin.ts";

export type ShopifyReviewSourceLine = { shopifyLineItemId: string; shopifyProductId: string | null; shopifyVariantId: string | null; title: string | null; productTitle: string | null; variantTitle: string | null; productHandle: string | null; productImageUrl: string | null; sku: string | null; quantity: number; currentQuantity: number | null; fulfillableQuantity: number | null; refundableQuantity: number | null; isGiftCard: boolean | null; requiresShipping: boolean | null; originalUnitPrice: string | null; discountedTotal: string | null; currencyCode: string | null; productType: string | null; vendor: string | null; tags: string[] };
export type ShopifyReviewSourceOrder = { shopifyOrderId: string; shopifyOrderName: string; createdAt: string | null; processedAt: string | null; cancelledAt: string | null; displayFinancialStatus: string | null; displayFulfillmentStatus: string | null; deliveredAt: string | null; customerId: string | null; lineItems: ShopifyReviewSourceLine[] };
type Graphql = <T>(query: string, variables?: Record<string, unknown>, options?: { shopDomain?: string | null }) => Promise<T>;
type Node = { id?: string; name?: string; createdAt?: string; processedAt?: string; cancelledAt?: string; displayFinancialStatus?: string; displayFulfillmentStatus?: string; customer?: { id?: string } | null; fulfillments?: Array<{ deliveredAt?: string | null }> | null; lineItems?: { nodes?: RawLine[]; pageInfo?: { hasNextPage: boolean; endCursor: string | null } } };
type RawLine = { id?: string; title?: string | null; quantity?: number | null; currentQuantity?: number | null; fulfillableQuantity?: number | null; refundableQuantity?: number | null; sku?: string | null; requiresShipping?: boolean | null; image?: { url?: string | null } | null; originalUnitPriceSet?: { shopMoney?: { amount?: string | null; currencyCode?: string | null } | null } | null; discountedTotalSet?: { shopMoney?: { amount?: string | null } | null } | null; product?: { id?: string | null; title?: string | null; handle?: string | null; isGiftCard?: boolean | null; productType?: string | null; vendor?: string | null; tags?: string[] | null; featuredImage?: { url?: string | null } | null } | null; variant?: { id?: string | null; title?: string | null; image?: { url?: string | null } | null } | null };
const query = `query ReviewSourceOrder($id: ID!, $after: String) { order(id: $id) { id name createdAt processedAt cancelledAt displayFinancialStatus displayFulfillmentStatus customer { id } fulfillments(first: 10) { deliveredAt } lineItems(first: 100, after: $after) { nodes { id title quantity currentQuantity fulfillableQuantity refundableQuantity sku requiresShipping image { url } originalUnitPriceSet { shopMoney { amount currencyCode } } discountedTotalSet { shopMoney { amount } } product { id title handle isGiftCard productType vendor tags featuredImage { url } } variant { id title image { url } } } pageInfo { hasNextPage endCursor } } } }`;
export class ReviewSourceError extends Error { readonly code: "REVIEW_SOURCE_ORDER_NOT_FOUND" | "REVIEW_SOURCE_GRAPHQL_FAILED" | "REVIEW_SOURCE_PAGINATION_LIMIT" | "REVIEW_SOURCE_INVALID_ORDER"; readonly retryable: boolean; constructor(code: "REVIEW_SOURCE_ORDER_NOT_FOUND" | "REVIEW_SOURCE_GRAPHQL_FAILED" | "REVIEW_SOURCE_PAGINATION_LIMIT" | "REVIEW_SOURCE_INVALID_ORDER", retryable: boolean, message: string) { super(message); this.name = "ReviewSourceError"; this.code = code; this.retryable = retryable; } }
const nullable = (value: string | null | undefined) => value?.trim() || null;
function mapLine(line: RawLine): ShopifyReviewSourceLine { const money = line.originalUnitPriceSet?.shopMoney; return { shopifyLineItemId: nullable(line.id) ?? "", shopifyProductId: nullable(line.product?.id), shopifyVariantId: nullable(line.variant?.id), title: nullable(line.title), productTitle: nullable(line.product?.title), variantTitle: nullable(line.variant?.title), productHandle: nullable(line.product?.handle), productImageUrl: nullable(line.image?.url) ?? nullable(line.variant?.image?.url) ?? nullable(line.product?.featuredImage?.url), sku: nullable(line.sku), quantity: Number(line.quantity ?? 0), currentQuantity: line.currentQuantity ?? null, fulfillableQuantity: line.fulfillableQuantity ?? null, refundableQuantity: line.refundableQuantity ?? null, isGiftCard: line.product?.isGiftCard ?? null, requiresShipping: line.requiresShipping ?? null, originalUnitPrice: nullable(money?.amount), discountedTotal: nullable(line.discountedTotalSet?.shopMoney?.amount), currencyCode: nullable(money?.currencyCode), productType: nullable(line.product?.productType), vendor: nullable(line.product?.vendor), tags: line.product?.tags?.filter((tag): tag is string => Boolean(tag?.trim())) ?? [] }; }

/** Reads a single authoritative order using tenant-scoped Admin credentials only. */
export async function getShopifyOrderForReviewSync(input: { shopDomain: string; shopifyOrderId: string; maxLineItems?: number; graphql?: Graphql }): Promise<ShopifyReviewSourceOrder | null> {
  if (!input.shopifyOrderId.trim()) throw new ReviewSourceError("REVIEW_SOURCE_INVALID_ORDER", false, "A Shopify order ID is required.");
  const graphql = input.graphql ?? adminGraphql as Graphql; const max = input.maxLineItems ?? 1000; let after: string | null = null; let order: Node | undefined; const lines: ShopifyReviewSourceLine[] = [];
  try { do { const data: { order: Node | null } = await graphql<{ order: Node | null }>(query, { id: input.shopifyOrderId, after }, { shopDomain: input.shopDomain }); order = data.order ?? undefined; if (!order) return null; const page = order.lineItems; lines.push(...(page?.nodes ?? []).map(mapLine)); if (lines.length > max) throw new ReviewSourceError("REVIEW_SOURCE_PAGINATION_LIMIT", false, "Shopify order exceeds the review line-item limit."); after = page?.pageInfo?.hasNextPage ? page.pageInfo.endCursor : null; } while (after); } catch (error) { if (error instanceof ReviewSourceError) throw error; throw new ReviewSourceError("REVIEW_SOURCE_GRAPHQL_FAILED", true, "Unable to load Shopify order for review synchronization."); }
  if (!order?.id || !order.name) throw new ReviewSourceError("REVIEW_SOURCE_INVALID_ORDER", false, "Shopify returned an invalid order.");
  return { shopifyOrderId: order.id, shopifyOrderName: order.name, createdAt: nullable(order.createdAt), processedAt: nullable(order.processedAt), cancelledAt: nullable(order.cancelledAt), displayFinancialStatus: nullable(order.displayFinancialStatus), displayFulfillmentStatus: nullable(order.displayFulfillmentStatus), deliveredAt: order.fulfillments?.map((fulfillment) => nullable(fulfillment.deliveredAt)).find(Boolean) ?? null, customerId: nullable(order.customer?.id), lineItems: lines };
}
