-- AlterEnum
ALTER TYPE "RefundSource" ADD VALUE 'RTO_EVENT';
ALTER TYPE "RefundSource" ADD VALUE 'ADMIN_EXCEPTION';
ALTER TYPE "RefundSource" ADD VALUE 'ORDER_ADJUSTMENT';

-- AlterEnum
ALTER TYPE "RefundMethod" ADD VALUE 'NO_REFUND';

-- AlterEnum
ALTER TYPE "RefundStatus" ADD VALUE 'PENDING';
ALTER TYPE "RefundStatus" ADD VALUE 'MANUAL_PENDING';
ALTER TYPE "RefundStatus" ADD VALUE 'NOT_REQUIRED';
