query Input {
  cart {
    cost {
      subtotalAmount {
        amount
      }
    }
    paymentIntent: attribute(key: "loopd2c_payment_intent") {
      value
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      promotionRuleId: attribute(key: "_loopdesk_promotion_rule_id") {
        value
      }
      promotionCompilationVersion: attribute(key: "_loopdesk_promotion_compilation_version") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
    configuration: metafield(namespace: "$app:loopdesk-promotions", key: "function-config") {
      value
    }
  }
  shop {
    prepaidOffer: metafield(namespace: "$app:loopd2c-express", key: "prepaid-offer") {
      value
    }
  }
}
