query CartLinesDiscountsGenerateRunInput {
  discountNode {
    metafield(namespace: "loopdesk", key: "discount_function_config") {
      value
    }
  }
  cart {
    lines {
      id
      quantity
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            productType
            tags
            inCollections(first: 100) {
              collectionId
              isMember
            }
          }
        }
      }
    }
  }
}
