import test from "node:test";
import assert from "node:assert/strict";

type PromotionEmbeddedContext = { shop?: string | string[]; shopify_shop?: string | string[]; host?: string | string[]; embedded?: string | string[] };
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] || "" : value || ""; }
function add(params: URLSearchParams, key: string, value: string | string[] | undefined) { const v = first(value); if (v) params.set(key, v); }
function buildPromotionAdminUrl(path: string, context: PromotionEmbeddedContext, extra: Record<string, string | undefined> = {}) { const params = new URLSearchParams(); add(params, "shop", context.shop); add(params, "shopify_shop", context.shopify_shop); add(params, "host", context.host); add(params, "embedded", context.embedded); Object.entries(extra).forEach(([key, value]) => { if (value) params.set(key, value); }); const query = params.toString(); return query ? `${path}?${query}` : path; }
function promotionEmbeddedContext(params: PromotionEmbeddedContext, canonicalShopDomain?: string): PromotionEmbeddedContext { return { shop: canonicalShopDomain || first(params.shop), shopify_shop: first(params.shopify_shop), host: first(params.host), embedded: first(params.embedded) }; }
function verifyPromotionActionTenant(claimedShopId: string, resolvedShopId: string) { return Boolean(resolvedShopId) && (!claimedShopId || claimedShopId === resolvedShopId); }

test("promotion admin URL helper preserves shop, host, and embedded", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }), "/admin/promotions?shop=canon.myshopify.com&host=admin-host&embedded=1"); });
test("status-filter links preserve embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }, { status: "ACTIVE" }), "/admin/promotions?shop=canon.myshopify.com&host=admin-host&embedded=1&status=ACTIVE"); });
test("new-draft link preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions/new", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }), "/admin/promotions/new?shop=canon.myshopify.com&host=admin-host&embedded=1"); });
test("edit link preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions/r1", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }), "/admin/promotions/r1?shop=canon.myshopify.com&host=admin-host&embedded=1"); });
test("save redirect preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions/r1", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }, { saved: "1" }), "/admin/promotions/r1?shop=canon.myshopify.com&host=admin-host&embedded=1&saved=1"); });
test("error redirect preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions/r1", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }, { error: "validation" }), "/admin/promotions/r1?shop=canon.myshopify.com&host=admin-host&embedded=1&error=validation"); });
test("status-change redirect preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions/r1", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }, { saved: "status" }), "/admin/promotions/r1?shop=canon.myshopify.com&host=admin-host&embedded=1&saved=status"); });
test("archive redirect preserves embedded context", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions", { shop: "canon.myshopify.com", host: "admin-host", embedded: "1" }, { status: "ARCHIVED" }), "/admin/promotions?shop=canon.myshopify.com&host=admin-host&embedded=1&status=ARCHIVED"); });
test("shopify_shop input can be resolved and canonicalized to shop", () => { const context = promotionEmbeddedContext({ shopify_shop: "input.myshopify.com", host: "admin-host", embedded: "1" }, "canon.myshopify.com"); assert.deepEqual(context, { shop: "canon.myshopify.com", shopify_shop: "input.myshopify.com", host: "admin-host", embedded: "1" }); });
test("no cross-tenant mutation is possible", () => { assert.equal(verifyPromotionActionTenant("shop-a", "shop-a"), true); assert.equal(verifyPromotionActionTenant("shop-b", "shop-a"), false); });
test("missing all context still returns safe unresolved-shop path", () => { assert.equal(buildPromotionAdminUrl("/admin/promotions", promotionEmbeddedContext({})), "/admin/promotions"); });
