import type { PromotionCompilationStatus, PromotionRuleStatus } from "./domain.ts";
import type { PromotionRuleRecord } from "./repository.server.ts";
class PromotionRuleNotFoundError extends Error { constructor() { super("Promotion rule was not found."); this.name = "PromotionRuleNotFoundError"; } }

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type PromotionAdminExecutionCode = "NOT_COMPILED" | "PENDING" | "COMPILING" | "READY" | "READY_WITH_FAILED_RECOMPILE" | "FAILED";
export type PromotionAdminTone = "neutral" | "info" | "success" | "warning" | "critical";
export type SafeCompilation = { id: string; promotionRuleId: string; version: number; status: PromotionCompilationStatus; reason: string; sourceHash?: string | null; compiledHash?: string | null; membershipCount: number; requestedAt?: Date | string | null; startedAt?: Date | string | null; completedAt?: Date | string | null; errorCode?: string | null; errorMessage?: string | null; diagnosticPayload?: Json };
export type CompilationSummary = { id: string; version: number; status: PromotionCompilationStatus; membershipCount: number; compiledAt?: Date | string | null; completedAt?: Date | string | null; sourceHashShort?: string | null; compiledHashShort?: string | null };
export type LatestCompilationAttempt = Omit<CompilationSummary, "compiledAt" | "sourceHashShort" | "compiledHashShort"> & { reason: string; requestedAt?: Date | string | null; startedAt?: Date | string | null; safeErrorCode?: string | null; safeErrorMessage?: string | null; diagnostics: PromotionCompilationDiagnostics };
export type PromotionCompilationDiagnostics = { schemaVersion?: string | number; sourceGroupCount?: number; pagesFetched?: number; productsSeen?: number; uniqueProducts?: number; sourceHashShort?: string | null; compiledHashShort?: string | null; safeFailureCode?: string | null };
export type PromotionExecutionReadModel = { code: PromotionAdminExecutionCode; label: string; tone: PromotionAdminTone; secondaryText?: string; currentCompilation: CompilationSummary | null; latestAttempt: LatestCompilationAttempt | null; history: LatestCompilationAttempt[] };

type Db = { promotionRule: { findFirst(args: object): Promise<(PromotionRuleRecord & { currentCompilation?: SafeCompilation | null }) | null> }; promotionCompilation: { findMany(args: object): Promise<SafeCompilation[]>; findFirst?(args: object): Promise<SafeCompilation | null> } };
async function defaultDb() { const mod = await import("../db/prisma.ts"); return mod.prisma as unknown as Db; }
const safeCodes = new Set(["RULE_NOT_COMPILABLE", "RULE_VALIDATION_FAILED", "SOURCE_CHANGED_DURING_COMPILATION", "CATALOGUE_RESOLUTION_FAILED", "EMPTY_TRIGGER_MEMBERSHIP", "PAYLOAD_GENERATION_FAILED", "VERSION_ALLOCATION_CONFLICT", "PERSISTENCE_FAILED", "DUPLICATE_ACTIVE_COMPILATION"]);
export const compilationStatusLabels: Record<PromotionAdminExecutionCode | "SUPERSEDED", string> = { NOT_COMPILED: "Not compiled", PENDING: "Queued", COMPILING: "Compiling", READY: "Compiled", READY_WITH_FAILED_RECOMPILE: "Compiled — latest retry failed", FAILED: "Compilation failed", SUPERSEDED: "Superseded for history" };
export const compilationStatusTones: Record<PromotionAdminExecutionCode | "SUPERSEDED", PromotionAdminTone> = { NOT_COMPILED: "neutral", PENDING: "info", COMPILING: "info", READY: "success", READY_WITH_FAILED_RECOMPILE: "warning", FAILED: "critical", SUPERSEDED: "neutral" };
export function safeCompilationFailureMessage(code?: string | null) { if (code === "SOURCE_CHANGED_DURING_COMPILATION") return "The promotion changed while compilation was running. Review the latest rule and compile again."; if (code === "EMPTY_TRIGGER_MEMBERSHIP") return "No qualifying products were found. Review the trigger collection or product type."; if (code === "CATALOGUE_RESOLUTION_FAILED") return "LoopDesk could not resolve qualifying Shopify products. Review the latest attempt and try again."; if (code === "RULE_NOT_COMPILABLE") return "Activate or pause the promotion before compiling it."; if (code === "RULE_VALIDATION_FAILED") return "The promotion is missing required rule details. Review the rule and try again."; if (code === "DUPLICATE_ACTIVE_COMPILATION") return "A compilation is already queued or running for this promotion."; return "Compilation could not be completed. Review the latest attempt or try again."; }
function shortHash(value?: string | null) { return value ? value.slice(0, 12) : null; }
function numberFrom(obj: Record<string, unknown>, keys: string[]) { for (const k of keys) if (typeof obj[k] === "number") return obj[k] as number; return undefined; }
function diagnostics(row: SafeCompilation): PromotionCompilationDiagnostics { const p = (row.diagnosticPayload && typeof row.diagnosticPayload === "object" && !Array.isArray(row.diagnosticPayload) ? row.diagnosticPayload : {}) as Record<string, unknown>; return { schemaVersion: (p.schemaVersion ?? p.schema_version) as string | number | undefined, sourceGroupCount: numberFrom(p, ["sourceGroupCount", "sourceGroups", "groupCount"]), pagesFetched: numberFrom(p, ["pagesFetched", "fetchedPages"]), productsSeen: numberFrom(p, ["productsSeen", "seenProducts"]), uniqueProducts: numberFrom(p, ["uniqueProducts", "membershipCount"]), sourceHashShort: shortHash(row.sourceHash), compiledHashShort: shortHash(row.compiledHash), safeFailureCode: safeCodes.has(String(row.errorCode)) ? row.errorCode! : null }; }
function summary(row: SafeCompilation | null | undefined, compiledAt?: Date | string | null): CompilationSummary | null { return row ? { id: row.id, version: row.version, status: row.status, membershipCount: row.membershipCount ?? 0, compiledAt, completedAt: row.completedAt, sourceHashShort: shortHash(row.sourceHash), compiledHashShort: shortHash(row.compiledHash) } : null; }
function attempt(row: SafeCompilation): LatestCompilationAttempt { const code = safeCodes.has(String(row.errorCode)) ? row.errorCode! : null; return { id: row.id, version: row.version, status: row.status, reason: row.reason, membershipCount: row.membershipCount ?? 0, requestedAt: row.requestedAt, startedAt: row.startedAt, completedAt: row.completedAt, safeErrorCode: code, safeErrorMessage: row.status === "FAILED" ? safeCompilationFailureMessage(code) : null, diagnostics: diagnostics(row) }; }
export function derivePromotionExecutionStatus(ruleStatus: PromotionRuleStatus, current: SafeCompilation | null, latest: SafeCompilation | null): PromotionAdminExecutionCode { if (latest?.status === "PENDING") return "PENDING"; if (latest?.status === "COMPILING") return "COMPILING"; if (current?.status === "READY") return latest?.status === "FAILED" && latest.version > current.version ? "READY_WITH_FAILED_RECOMPILE" : "READY"; if (latest?.status === "FAILED") return "FAILED"; if (ruleStatus === "ACTIVE" || ruleStatus === "PAUSED") return "PENDING"; return "NOT_COMPILED"; }
function secondary(code: PromotionAdminExecutionCode, current: CompilationSummary | null, latest: LatestCompilationAttempt | null) { if (code === "READY_WITH_FAILED_RECOMPILE") return `Version ${current?.version ?? "—"}. Latest retry failed.`; const base = current ? `Version ${current.version} · ${current.membershipCount} products` : latest ? `Attempt ${latest.version}` : undefined; return base; }
export async function getPromotionCompilationReadModel(shopId: string, promotionRuleId: string, options: { historyLimit?: number } = {}, database?: Db): Promise<PromotionExecutionReadModel> { const db = database ?? await defaultDb(); const rule = await db.promotionRule.findFirst({ where: { id: promotionRuleId, shopId }, include: { currentCompilation: { select: safeSelect } } }) as (PromotionRuleRecord & { currentCompilation?: SafeCompilation | null }) | null; if (!rule) throw new PromotionRuleNotFoundError(); const rows = await db.promotionCompilation.findMany({ where: { promotionRuleId }, orderBy: [{ version: "desc" }, { requestedAt: "desc" }], take: options.historyLimit ?? 10, select: safeSelect }); const latest = rows[0] ?? null; const current = rule.currentCompilation ?? rows.find((r) => r.id === rule.currentCompilationId) ?? null; const code = derivePromotionExecutionStatus(rule.status, current, latest); const currentSummary = summary(current, rule.compiledAt); const latestAttempt = latest ? attempt(latest) : null; return { code, label: compilationStatusLabels[code], tone: compilationStatusTones[code], secondaryText: secondary(code, currentSummary, latestAttempt), currentCompilation: currentSummary, latestAttempt, history: rows.map(attempt) }; }
export async function getPromotionListCompilationReadModels(shopId: string, ruleIds: string[], database?: Db) { const db = database ?? await defaultDb(); const rules = await Promise.all(ruleIds.map((id) => db.promotionRule.findFirst({ where: { id, shopId }, include: { currentCompilation: { select: safeSelect } } }))) as Array<(PromotionRuleRecord & { currentCompilation?: SafeCompilation | null }) | null>; const rows = await db.promotionCompilation.findMany({ where: { promotionRuleId: { in: ruleIds } }, orderBy: [{ version: "desc" }], select: safeSelect }); const latestByRule = new Map<string, SafeCompilation>(); for (const row of rows) if (!latestByRule.has(row.promotionRuleId)) latestByRule.set(row.promotionRuleId, row); return new Map(rules.filter(Boolean).map((rule) => { const latest = latestByRule.get(rule!.id) ?? null; const current = rule!.currentCompilation ?? null; const code = derivePromotionExecutionStatus(rule!.status, current, latest); return [rule!.id, { code, label: compilationStatusLabels[code], tone: compilationStatusTones[code], secondaryText: secondary(code, summary(current, rule!.compiledAt), latest ? attempt(latest) : null) }]; })); }
const safeSelect = { id: true, promotionRuleId: true, version: true, status: true, reason: true, sourceHash: true, compiledHash: true, membershipCount: true, requestedAt: true, startedAt: true, completedAt: true, errorCode: true, errorMessage: true, diagnosticPayload: true };
