import { prisma } from "../db/prisma.ts";
import type { PromotionRewardType, PromotionRuleStatus, PromotionTriggerMatchMode, PromotionTriggerReferenceInput, PromotionTriggerType } from "./domain.ts";
import { normalizeDate, normalizeNumericValue, normalizeOptionalText, normalizeProductType, normalizeRewardValue, normalizeShopifyCollectionGid, normalizeShopifyProductGid } from "./normalization.ts";
import { validatePromotionRule } from "./validation.ts";

export class PromotionRuleNotFoundError extends Error { constructor() { super("Promotion rule was not found."); this.name = "PromotionRuleNotFoundError"; } }
export class PromotionRuleValidationError extends Error { readonly errors: { field: string; message: string }[]; constructor(errors: { field: string; message: string }[]) { super("Promotion rule validation failed."); this.name = "PromotionRuleValidationError"; this.errors = errors; } }
export class PromotionRuleTransitionError extends Error { constructor(from: PromotionRuleStatus, to: PromotionRuleStatus) { super(`Invalid promotion rule status transition from ${from} to ${to}.`); this.name = "PromotionRuleTransitionError"; } }

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Actor = { actorType: string; actorId?: string | null };
type AuditAction = "PROMOTION_RULE_CREATED" | "PROMOTION_RULE_UPDATED" | "PROMOTION_RULE_STATUS_CHANGED" | "PROMOTION_RULE_ARCHIVED" | "PROMOTION_TRIGGER_REFERENCES_REPLACED";

export type PromotionTriggerReferenceRecord = PromotionTriggerReferenceInput & { id: string; promotionRuleId: string; position: number; displayTitle?: string | null; displayHandle?: string | null; displayImageUrl?: string | null; createdAt?: Date; updatedAt?: Date };
export type PromotionRuleRecord = {
  id: string; shopId: string; name: string; description?: string | null; status: PromotionRuleStatus; priority: number; triggerType: PromotionTriggerType; triggerMatchMode: PromotionTriggerMatchMode;
  minimumTriggerQuantity: number; minimumCartSubtotal?: unknown; offerProductGid: string; offerProductHandle?: string | null; offerProductTitle?: string | null; offerProductImageUrl?: string | null;
  rewardType: PromotionRewardType; rewardValue: unknown; maximumRewardQuantity: number; heading?: string | null; badgeText?: string | null; customerMessage?: string | null; ctaText?: string | null;
  combinesWithProductDiscounts?: boolean; combinesWithOrderDiscounts?: boolean; combinesWithShippingDiscounts?: boolean; startsAt?: Date | null; endsAt?: Date | null; currentCompilationId?: string | null; compiledAt?: Date | null;
  createdByType?: string | null; createdById?: string | null; updatedByType?: string | null; updatedById?: string | null; archivedAt?: Date | null; createdAt?: Date; updatedAt?: Date; triggerReferences?: PromotionTriggerReferenceRecord[];
};
export type PromotionCompilationRecord = { id: string; promotionRuleId: string; version: number; status: string; reason: string; sourceHash: string; compiledHash?: string | null; triggerType: PromotionTriggerType; membershipCount: number; createdAt?: Date; updatedAt?: Date };

type Delegate<T> = { findFirst(args: object): Promise<T | null>; findMany(args: object): Promise<T[]>; create(args: object): Promise<T>; update(args: object): Promise<T>; deleteMany?(args: object): Promise<{ count: number }>; createMany?(args: object): Promise<{ count: number }> };
type PromotionDb = { promotionRule: Delegate<PromotionRuleRecord>; promotionTriggerReference: Required<Pick<Delegate<PromotionTriggerReferenceRecord>, "deleteMany" | "createMany">>; promotionAuditLog: { create(args: object): Promise<unknown> }; promotionCompilation: Pick<Delegate<PromotionCompilationRecord>, "findMany">; $transaction<T>(fn: (tx: PromotionDb) => Promise<T>): Promise<T> };
const db = () => prisma as unknown as PromotionDb;

export type PromotionRuleWriteInput = Omit<Partial<PromotionRuleRecord>, "id" | "shopId" | "createdAt" | "updatedAt" | "archivedAt" | "triggerReferences"> & { shopId: string; name: string; triggerType: PromotionTriggerType; triggerReferences?: PromotionTriggerReferenceInput[]; offerProductGid: string; rewardType: PromotionRewardType; rewardValue: string | number; actor?: Actor };
export type PromotionRuleUpdateInput = Partial<Omit<PromotionRuleWriteInput, "shopId" | "actor">> & { actor?: Actor };

function validation(errors: { field: string; message: string }[]): never { throw new PromotionRuleValidationError(errors); }
function actor(a?: Actor): Required<Actor> { return { actorType: a?.actorType ?? "SYSTEM", actorId: a?.actorId ?? null }; }
function serialize(value: unknown): Json { if (value == null || ["string", "number", "boolean"].includes(typeof value)) return value as Json; if (value instanceof Date) return value.toISOString(); if (Array.isArray(value)) return value.map(serialize); if (typeof value === "object") return Object.fromEntries(Object.entries(value).filter(([k]) => !/token|secret|password|payload|response/i.test(k)).map(([k, v]) => [k, serialize(v)])) as Json; return String(value); }
function sanitize(row: unknown): Json { return serialize(row); }

function normalizeReference(ref: PromotionTriggerReferenceInput, position: number): PromotionTriggerReferenceInput & { position: number } {
  const sourceType = ref.sourceType;
  if (sourceType === "PRODUCT") return { sourceType, referenceGid: normalizeShopifyProductGid(ref.referenceGid), referenceValue: null, normalizedValue: null, position };
  if (sourceType === "COLLECTION") return { sourceType, referenceGid: normalizeShopifyCollectionGid(ref.referenceGid), referenceValue: null, normalizedValue: null, position };
  const normalizedValue = normalizeProductType(ref.normalizedValue ?? ref.referenceValue);
  return { sourceType, referenceGid: null, referenceValue: normalizeOptionalText(ref.referenceValue) ?? normalizedValue, normalizedValue, position };
}
function dedupe(refs: ReturnType<typeof normalizeReference>[]) { const seen = new Set<string>(); return refs.filter((r) => { const key = `${r.sourceType}:${r.referenceGid ?? r.normalizedValue}`; if (seen.has(key)) return false; seen.add(key); return true; }).map((r, position) => ({ ...r, position })); }
type NormalizableRule = Partial<Omit<PromotionRuleRecord, "rewardValue" | "triggerReferences">> & { name: string; triggerType: PromotionTriggerType; offerProductGid: string; rewardType: PromotionRewardType; rewardValue: string | number | unknown; triggerReferences?: PromotionTriggerReferenceInput[] };
type NormalizedRule = Partial<Omit<PromotionRuleRecord, "rewardValue" | "triggerReferences">> & { name: string; status: PromotionRuleStatus; priority: number; triggerType: PromotionTriggerType; triggerMatchMode: PromotionTriggerMatchMode; minimumTriggerQuantity: number; offerProductGid: string; rewardType: PromotionRewardType; rewardValue: number; maximumRewardQuantity: number; triggerReferences: ReturnType<typeof normalizeReference>[] };
function normalizeRule(input: NormalizableRule): NormalizedRule {
  const rewardValue = normalizeRewardValue(input.rewardValue); const minimumCartSubtotal = normalizeNumericValue(input.minimumCartSubtotal); const offerProductGid = normalizeShopifyProductGid(input.offerProductGid);
  const refs = dedupe((input.triggerReferences ?? []).map(normalizeReference));
  return { ...(input as PromotionRuleRecord), name: normalizeOptionalText(input.name) ?? "", description: normalizeOptionalText(input.description), priority: input.priority ?? 0, status: input.status ?? "DRAFT", triggerMatchMode: input.triggerMatchMode ?? "ANY", minimumTriggerQuantity: input.minimumTriggerQuantity ?? 1, minimumCartSubtotal, offerProductGid: offerProductGid ?? "", rewardValue: rewardValue ?? Number.NaN, maximumRewardQuantity: input.maximumRewardQuantity ?? 1, heading: normalizeOptionalText(input.heading), badgeText: normalizeOptionalText(input.badgeText), customerMessage: normalizeOptionalText(input.customerMessage), ctaText: normalizeOptionalText(input.ctaText), startsAt: normalizeDate(input.startsAt), endsAt: normalizeDate(input.endsAt), triggerReferences: refs };
}
function assertValid(rule: NormalizedRule) { const result = validatePromotionRule(rule as Parameters<typeof validatePromotionRule>[0]); if (!result.valid) validation(result.errors); }
function dataFor(rule: NormalizedRule, actorInfo: Required<Actor>, material = true) { return { name: rule.name, description: rule.description ?? null, status: rule.status, priority: rule.priority, triggerType: rule.triggerType, triggerMatchMode: rule.triggerMatchMode, minimumTriggerQuantity: rule.minimumTriggerQuantity, minimumCartSubtotal: rule.minimumCartSubtotal ?? null, offerProductGid: rule.offerProductGid, offerProductHandle: rule.offerProductHandle ?? null, offerProductTitle: rule.offerProductTitle ?? null, offerProductImageUrl: rule.offerProductImageUrl ?? null, rewardType: rule.rewardType, rewardValue: rule.rewardValue, maximumRewardQuantity: rule.maximumRewardQuantity, heading: rule.heading ?? null, badgeText: rule.badgeText ?? null, customerMessage: rule.customerMessage ?? null, ctaText: rule.ctaText ?? null, combinesWithProductDiscounts: rule.combinesWithProductDiscounts ?? false, combinesWithOrderDiscounts: rule.combinesWithOrderDiscounts ?? true, combinesWithShippingDiscounts: rule.combinesWithShippingDiscounts ?? true, startsAt: rule.startsAt ?? null, endsAt: rule.endsAt ?? null, updatedByType: actorInfo.actorType, updatedById: actorInfo.actorId, ...(material ? { currentCompilationId: null, compiledAt: null } : {}) }; }
async function audit(tx: PromotionDb, shopId: string, ruleId: string, action: AuditAction, a: Required<Actor>, previousState?: unknown, nextState?: unknown, metadata?: unknown) { await tx.promotionAuditLog.create({ data: { shopId, promotionRuleId: ruleId, action, actorType: a.actorType, actorId: a.actorId, previousState: sanitize(previousState), nextState: sanitize(nextState), metadata: sanitize(metadata) } }); }
async function own(tx: PromotionDb, shopId: string, id: string) { const rule = await tx.promotionRule.findFirst({ where: { id, shopId }, include: { triggerReferences: { orderBy: { position: "asc" } } } }); if (!rule) throw new PromotionRuleNotFoundError(); return rule; }

export async function createPromotionRule(input: PromotionRuleWriteInput, database: PromotionDb = db()) { const a = actor(input.actor); const normalized = normalizeRule(input); assertValid(normalized); return database.$transaction(async (tx) => { const created = await tx.promotionRule.create({ data: { shopId: input.shopId, ...dataFor(normalized, a), createdByType: a.actorType, createdById: a.actorId, triggerReferences: { createMany: { data: normalized.triggerReferences } } }, include: { triggerReferences: { orderBy: { position: "asc" } } } }); await audit(tx, input.shopId, created.id, "PROMOTION_RULE_CREATED", a, null, created); return created; }); }
export async function getPromotionRuleById(shopId: string, id: string, database: PromotionDb = db()) { return own(database, shopId, id); }
export async function listPromotionRules(shopId: string, options: { includeArchived?: boolean } = {}, database: PromotionDb = db()) { return database.promotionRule.findMany({ where: { shopId, ...(options.includeArchived ? {} : { archivedAt: null, status: { not: "ARCHIVED" } }) }, orderBy: [{ priority: "asc" }, { createdAt: "desc" }], include: { triggerReferences: { orderBy: { position: "asc" } } } }); }
export async function updatePromotionRule(shopId: string, id: string, input: PromotionRuleUpdateInput, database: PromotionDb = db()) { const a = actor(input.actor); return database.$transaction(async (tx) => { const existing = await own(tx, shopId, id); if (existing.status === "ARCHIVED") throw new PromotionRuleTransitionError("ARCHIVED", input.status ?? "ARCHIVED"); const normalized = normalizeRule({ ...existing, ...input, shopId, triggerReferences: input.triggerReferences ?? existing.triggerReferences ?? [] }); assertValid(normalized); const updated = await tx.promotionRule.update({ where: { id }, data: dataFor(normalized, a), include: { triggerReferences: { orderBy: { position: "asc" } } } }); if (input.triggerReferences) { await tx.promotionTriggerReference.deleteMany({ where: { promotionRuleId: id } }); await tx.promotionTriggerReference.createMany({ data: normalized.triggerReferences.map((r) => ({ ...r, promotionRuleId: id })) }); } await audit(tx, shopId, id, "PROMOTION_RULE_UPDATED", a, existing, updated); return updated; }); }
export async function replacePromotionTriggerReferences(shopId: string, id: string, references: PromotionTriggerReferenceInput[], input: { actor?: Actor } = {}, database: PromotionDb = db()) { const a = actor(input.actor); return database.$transaction(async (tx) => { const existing = await own(tx, shopId, id); const normalized = normalizeRule({ ...existing, triggerReferences: references }); assertValid(normalized); await tx.promotionTriggerReference.deleteMany({ where: { promotionRuleId: id } }); await tx.promotionTriggerReference.createMany({ data: normalized.triggerReferences.map((r) => ({ ...r, promotionRuleId: id })) }); const updated = await tx.promotionRule.update({ where: { id }, data: { currentCompilationId: null, compiledAt: null, updatedByType: a.actorType, updatedById: a.actorId }, include: { triggerReferences: { orderBy: { position: "asc" } } } }); await audit(tx, shopId, id, "PROMOTION_TRIGGER_REFERENCES_REPLACED", a, existing.triggerReferences, normalized.triggerReferences); return updated; }); }
const transitions: Record<PromotionRuleStatus, PromotionRuleStatus[]> = { DRAFT: ["ACTIVE", "ARCHIVED"], ACTIVE: ["PAUSED", "ARCHIVED"], PAUSED: ["ACTIVE", "ARCHIVED"], ARCHIVED: [] };
export async function changePromotionRuleStatus(shopId: string, id: string, status: PromotionRuleStatus, input: { actor?: Actor } = {}, database: PromotionDb = db()) { const a = actor(input.actor); return database.$transaction(async (tx) => { const existing = await own(tx, shopId, id); if (!transitions[existing.status].includes(status)) throw new PromotionRuleTransitionError(existing.status, status); if (status === "ACTIVE") assertValid(normalizeRule({ ...existing, status })); const updated = await tx.promotionRule.update({ where: { id }, data: { status, archivedAt: status === "ARCHIVED" ? new Date() : null, updatedByType: a.actorType, updatedById: a.actorId }, include: { triggerReferences: { orderBy: { position: "asc" } } } }); await audit(tx, shopId, id, status === "ARCHIVED" ? "PROMOTION_RULE_ARCHIVED" : "PROMOTION_RULE_STATUS_CHANGED", a, { status: existing.status }, { status }); return updated; }); }
export async function archivePromotionRule(shopId: string, id: string, input: { actor?: Actor } = {}, database: PromotionDb = db()) { return changePromotionRuleStatus(shopId, id, "ARCHIVED", input, database); }
export async function listPromotionCompilations(shopId: string, promotionRuleId: string, database: PromotionDb = db()) { await own(database, shopId, promotionRuleId); return database.promotionCompilation.findMany({ where: { promotionRuleId }, orderBy: [{ version: "desc" }, { createdAt: "desc" }] }); }
