import { randomUUID } from "crypto";
import type { PrismaClient } from "../../generated/prisma";
import { sha256Hex } from "./compiler-hash.ts";

const TITLE = "LoopDesk automatic promotions";
const NAMESPACE = "loopdesk_promotions";
const KEY = "runtime_configuration";
const FUNCTION_IDENTITY = process.env.LOOPDESK_DISCOUNT_FUNCTION_ID || "loopdesk-product-discount";
const APP_IDENTITY = process.env.SHOPIFY_API_KEY || "loopdesk";
const LEASE_MS = 5 * 60 * 1000;

type JsonValue = boolean | number | string | null | JsonValue[] | { [key: string]: JsonValue };
type InputJson = boolean | number | string | InputJson[] | { [key: string]: InputJson | null };
type RuntimeState = NonNullable<Awaited<ReturnType<PrismaClient["promotionRuntimeSyncState"]["findUnique"]>>>;
export type RuntimeSyncDb = Pick<PrismaClient, "$transaction" | "promotionRuntimeSyncState" | "promotionCompilation">;
export type RuntimeSyncAuth = { shopId: string; shopDomain: string; actorId: string; permissions: string[] };
type Gql = <T>(query: string, variables?: Record<string, unknown>, options?: { shopDomain?: string | null }) => Promise<T>;
export type RuntimeSyncDeps = { database?: RuntimeSyncDb; graphql?: Gql; now?: () => Date; uuid?: () => string };
async function defaultDb(): Promise<RuntimeSyncDb> { const mod = await import("../db/prisma.ts"); return mod.prisma as RuntimeSyncDb; }
async function defaultGraphql<T>(query: string, variables?: Record<string, unknown>, options?: { shopDomain?: string | null }) { const mod = await import("../shopify/admin.ts"); return mod.shopifyAdminGraphql<T>(query, variables, options); }
export type RuntimeSyncResult = { status: "SYNCED" | "UNCHANGED"; discountId: string; configurationVersion: number; configurationHash: string };

type DiscountNode = { id: string; title?: string | null; status?: string | null; app?: { id?: string | null; apiKey?: string | null; title?: string | null } | null; appDiscountType?: { appKey?: string | null; functionId?: string | null; functionHandle?: string | null } | null; discountClasses?: string[] | null; metafield?: { namespace: string; key: string; type: string; value: string } | null };
class RuntimeSyncError extends Error { readonly code: string; constructor(code: string, message: string) { super(message); this.name = "RuntimeSyncError"; this.code = code; } }
export { RuntimeSyncError };

function safe(value: unknown): JsonValue { if (value == null || ["string", "number", "boolean"].includes(typeof value)) return value as JsonValue; if (Array.isArray(value)) return value.map(safe) as JsonValue; if (typeof value === "object") return Object.fromEntries(Object.entries(value).filter(([k]) => !/token|authorization|header|secret|password/i.test(k)).map(([k,v]) => [k, safe(v)])) as JsonValue; return String(value); }
function inputJson(value: unknown): InputJson { return safe(value) as InputJson; }
function requirePermission(auth: RuntimeSyncAuth) { if (!auth.shopId || !auth.actorId) throw new RuntimeSyncError("UNAUTHENTICATED", "Authenticated embedded-admin session required."); if (!auth.permissions.includes("promotions.manage")) throw new RuntimeSyncError("UNAUTHORIZED", "Actor is not allowed to manage promotions."); }
function canonicalConfig(compilations: Array<{ id: string; version: number; promotionRuleId: string; functionPayload: unknown; compiledHash: string | null }>) { return { owner: "loopdesk", schemaVersion: 1, compilations: compilations.map((c) => ({ id: c.id, ruleId: c.promotionRuleId, version: c.version, hash: c.compiledHash, payload: c.functionPayload })).sort((a,b)=>a.ruleId.localeCompare(b.ruleId)) }; }
function parseConfig(node: DiscountNode) { const mf = node.metafield; if (!mf || mf.namespace !== NAMESPACE || mf.key !== KEY || mf.type !== "json") throw new RuntimeSyncError("METAFIELD_INVALID", "Discount metafield namespace, key, or type is invalid."); try { return JSON.parse(mf.value); } catch { throw new RuntimeSyncError("METAFIELD_MALFORMED", "Discount metafield JSON is malformed."); } }
function owns(node: DiscountNode, expectedHash?: string) { if (!node.id) return false; if (node.title !== TITLE) return false; if (!node.discountClasses?.includes("PRODUCT")) return false; const appBits = [node.app?.apiKey, node.app?.id, node.app?.title].filter(Boolean).join(" ").toLowerCase(); if (APP_IDENTITY && !appBits.includes(APP_IDENTITY.toLowerCase()) && !appBits.includes("loopdesk")) return false; const fnBits = [node.appDiscountType?.functionId, node.appDiscountType?.functionHandle, node.appDiscountType?.appKey].filter(Boolean).join(" ").toLowerCase(); if (FUNCTION_IDENTITY && !fnBits.includes(FUNCTION_IDENTITY.toLowerCase())) return false; if (expectedHash) { const cfg = parseConfig(node) as { configurationHash?: string }; if (cfg.configurationHash !== expectedHash) return false; } return true; }
async function readDiscount(graphql: Gql, shopDomain: string, id: string) { const data = await graphql<{ node: DiscountNode | null }>(`query LoopDeskDiscount($id: ID!) { node(id: $id) { ... on DiscountAutomaticApp { id title status discountClasses app { id title apiKey } appDiscountType { appKey functionId functionHandle } metafield(namespace: "${NAMESPACE}", key: "${KEY}") { namespace key type value } } } }`, { id }, { shopDomain }); return data.node; }
async function search(graphql: Gql, shopDomain: string) { const data = await graphql<{ discountNodes: { nodes: DiscountNode[] } }>(`query LoopDeskDiscountSearch($query: String!) { discountNodes(first: 20, query: $query) { nodes { id discount { ... on DiscountAutomaticApp { id title status discountClasses app { id title apiKey } appDiscountType { appKey functionId functionHandle } metafield(namespace: "${NAMESPACE}", key: "${KEY}") { namespace key type value } } } } } }`, { query: `title:'${TITLE}'` }, { shopDomain }); return (data.discountNodes?.nodes || []).map((n) => ("discount" in n ? (n as unknown as { discount: DiscountNode }).discount : n)); }
async function createOrUpdate(graphql: Gql, shopDomain: string, id: string | null, config: unknown) { const metafields = [{ namespace: NAMESPACE, key: KEY, type: "json", value: JSON.stringify(config) }]; const mutation = id ? `mutation Update($id: ID!, $metafields: [MetafieldsSetInput!]!) { metafieldsSet(metafields: $metafields) { userErrors { field message } } discountAutomaticAppUpdate(id: $id, automaticAppDiscount: {title: "${TITLE}", functionId: "${FUNCTION_IDENTITY}", startsAt: "2000-01-01T00:00:00Z", discountClasses: [PRODUCT]}) { automaticAppDiscount { discountId } userErrors { field message } } }` : `mutation Create($metafields: [MetafieldsSetInput!]!) { discountAutomaticAppCreate(automaticAppDiscount: {title: "${TITLE}", functionId: "${FUNCTION_IDENTITY}", startsAt: "2000-01-01T00:00:00Z", discountClasses: [PRODUCT]}) { automaticAppDiscount { discountId } userErrors { field message } } metafieldsSet(metafields: $metafields) { userErrors { field message } } }`;
  const data = await graphql<Record<string, { userErrors?: Array<{ message?: string }>; automaticAppDiscount?: { discountId?: string } }>>(mutation, { id, metafields }, { shopDomain });
  const errs = Object.values(data).flatMap((v) => v?.userErrors || []).filter((e) => e.message); if (errs.length) throw new RuntimeSyncError("SHOPIFY_USER_ERROR", errs.map((e)=>e.message).join(", "));
  return Object.values(data).map((v)=>v?.automaticAppDiscount?.discountId).find(Boolean) || id;
}
async function begin(db: RuntimeSyncDb, shopId: string, attemptId: string, now: Date) { return db.$transaction(async (tx) => { const current = await tx.promotionRuntimeSyncState.upsert({ where: { shopId }, create: { shopId }, update: {} }); if (current.activeAttemptId && current.leaseExpiresAt && current.leaseExpiresAt > now) throw new RuntimeSyncError("SYNC_IN_PROGRESS", "A promotion runtime synchronization is already active."); return tx.promotionRuntimeSyncState.update({ where: { shopId }, data: { activeAttemptId: attemptId, attemptStartedAt: now, leaseExpiresAt: new Date(now.getTime()+LEASE_MS), stateVersion: { increment: 1 } } }); }); }
type FinishData = { shopifyAutomaticDiscountId: string; lastSuccessfulConfigurationVersion: number; lastSuccessfulConfigurationHash: string; lastSuccessfulCompilationVersions: InputJson; lastSuccessfulRuleIds: InputJson };
async function finish(db: RuntimeSyncDb, shopId: string, attemptId: string, data: FinishData) { const res = await db.promotionRuntimeSyncState.updateMany({ where: { shopId, activeAttemptId: attemptId }, data: { ...data, activeAttemptId: null, attemptStartedAt: null, leaseExpiresAt: null, stateVersion: { increment: 1 } } }); if (res.count !== 1) throw new RuntimeSyncError("STALE_ATTEMPT", "Only the active synchronization attempt may finalize."); }
async function fail(db: RuntimeSyncDb, shopId: string, attemptId: string, error: unknown) { await db.promotionRuntimeSyncState.updateMany({ where: { shopId, activeAttemptId: attemptId }, data: { activeAttemptId: null, attemptStartedAt: null, leaseExpiresAt: null, stateVersion: { increment: 1 } } }); throw error; }
export async function syncPromotionRuntime(auth: RuntimeSyncAuth, deps: RuntimeSyncDeps = {}): Promise<RuntimeSyncResult> { requirePermission(auth); const db = deps.database ?? (await defaultDb()); const graphql = deps.graphql ?? defaultGraphql; const now = deps.now?.() ?? new Date(); const attemptId = deps.uuid?.() ?? randomUUID(); const state = await begin(db, auth.shopId, attemptId, now); try { const comps = await db.promotionCompilation.findMany({ where: { promotionRule: { shopId: auth.shopId }, status: "READY" }, orderBy: [{ promotionRuleId: "asc" }, { version: "desc" }], select: { id: true, version: true, promotionRuleId: true, functionPayload: true, compiledHash: true } }); const latest = [...new Map(comps.map((c) => [c.promotionRuleId, c])).values()]; const configBare = canonicalConfig(latest); const configurationHash = sha256Hex(configBare); const configurationVersion = (state.lastSuccessfulConfigurationHash === configurationHash ? state.lastSuccessfulConfigurationVersion : null) ?? ((state.lastSuccessfulConfigurationVersion ?? 0) + 1); const config = { ...configBare, configurationVersion, configurationHash };
    let candidate: DiscountNode | null = state.shopifyAutomaticDiscountId ? await readDiscount(graphql, auth.shopDomain, state.shopifyAutomaticDiscountId) : null; if (candidate && !owns(candidate)) throw new RuntimeSyncError("DISCOUNT_OWNERSHIP_INVALID", "Persisted discount belongs to another app or Function."); if (!candidate) { const matches = (await search(graphql, auth.shopDomain)).filter((n) => owns(n)); if (matches.length > 1) throw new RuntimeSyncError("AMBIGUOUS_DISCOUNT_MATCHES", "Multiple LoopDesk-owned automatic discounts match the canonical title."); candidate = matches[0] ?? null; }
    if (candidate && owns(candidate, configurationHash)) { await finish(db, auth.shopId, attemptId, { shopifyAutomaticDiscountId: candidate.id, lastSuccessfulConfigurationVersion: configurationVersion, lastSuccessfulConfigurationHash: configurationHash, lastSuccessfulCompilationVersions: inputJson(Object.fromEntries(latest.map((c)=>[c.promotionRuleId,c.version]))), lastSuccessfulRuleIds: inputJson(latest.map((c)=>c.promotionRuleId)) }); return { status: "UNCHANGED", discountId: candidate.id, configurationVersion, configurationHash }; }
    const id = await createOrUpdate(graphql, auth.shopDomain, candidate?.id ?? null, config); if (!id) throw new RuntimeSyncError("DISCOUNT_WRITE_FAILED", "Shopify did not return an automatic discount id."); const verified = await readDiscount(graphql, auth.shopDomain, id); if (!verified || !owns(verified)) throw new RuntimeSyncError("READBACK_OWNERSHIP_INVALID", "Read-back discount failed ownership verification."); const readConfig = parseConfig(verified); if (JSON.stringify(readConfig) !== JSON.stringify(config)) throw new RuntimeSyncError("READBACK_CONFIGURATION_MISMATCH", "Read-back configuration does not match canonical configuration."); await finish(db, auth.shopId, attemptId, { shopifyAutomaticDiscountId: id, lastSuccessfulConfigurationVersion: configurationVersion, lastSuccessfulConfigurationHash: configurationHash, lastSuccessfulCompilationVersions: inputJson(Object.fromEntries(latest.map((c)=>[c.promotionRuleId,c.version]))), lastSuccessfulRuleIds: inputJson(latest.map((c)=>c.promotionRuleId)) }); return { status: "SYNCED", discountId: id, configurationVersion, configurationHash }; } catch (error) { return fail(db, auth.shopId, attemptId, error) as never; } }
