import test from "node:test";
import assert from "node:assert/strict";
import { syncPromotionRuntime, RuntimeSyncError, type RuntimeSyncDb } from "./runtime-sync.server.ts";

type State = { id: string; shopId: string; shopifyAutomaticDiscountId: string | null; lastSuccessfulConfigurationVersion: number | null; lastSuccessfulConfigurationHash: string | null; lastSuccessfulCompilationVersions: unknown; lastSuccessfulRuleIds: unknown; activeAttemptId: string | null; attemptStartedAt: Date | null; leaseExpiresAt: Date | null; stateVersion: number; createdAt: Date; updatedAt: Date };
function db() { const now = new Date("2026-07-12T00:00:00Z"); const state = new Map<string, State>(); const compilations = [{ id: "c1", version: 7, promotionRuleId: "r1", functionPayload: { ruleId: "r1" }, compiledHash: "h1" }]; const api = { state, promotionRuntimeSyncState: { async upsert({ where, create }: { where: { shopId: string }, create: { shopId: string } }) { let row = state.get(where.shopId); if (!row) { row = { id: "s1", shopId: create.shopId, shopifyAutomaticDiscountId: null, lastSuccessfulConfigurationVersion: null, lastSuccessfulConfigurationHash: null, lastSuccessfulCompilationVersions: null, lastSuccessfulRuleIds: null, activeAttemptId: null, attemptStartedAt: null, leaseExpiresAt: null, stateVersion: 0, createdAt: now, updatedAt: now }; state.set(where.shopId, row); } return row; }, async update({ where, data }: { where: { shopId: string }, data: Partial<State> & { stateVersion?: { increment: number } } }) { const row = state.get(where.shopId)!; Object.assign(row, data, { stateVersion: row.stateVersion + (data.stateVersion?.increment ?? 0), updatedAt: now }); return row; }, async updateMany({ where, data }: { where: { shopId: string; activeAttemptId?: string }, data: Partial<State> & { stateVersion?: { increment: number } } }) { const row = state.get(where.shopId); if (!row || (where.activeAttemptId && row.activeAttemptId !== where.activeAttemptId)) return { count: 0 }; Object.assign(row, data, { stateVersion: row.stateVersion + (data.stateVersion?.increment ?? 0), updatedAt: now }); return { count: 1 }; }, async findUnique() { return null; } }, promotionCompilation: { async findMany() { return compilations; } }, async $transaction<T>(fn: (tx: RuntimeSyncDb) => Promise<T>) { return fn(api as unknown as RuntimeSyncDb); } }; return api as unknown as RuntimeSyncDb & { state: Map<string, State> }; }
function node(id="gid://shopify/DiscountAutomaticNode/1", value?: string) { return { id, title: "LoopDesk automatic promotions", status: "ACTIVE", discountClasses: ["PRODUCT"], app: { apiKey: "loopdesk", title: "LoopDesk" }, appDiscountType: { functionId: "loopdesk-product-discount" }, metafield: { namespace: "loopdesk_promotions", key: "runtime_configuration", type: "json", value: value || "{}" } }; }
const auth = { shopId: "shop1", shopDomain: "shop.myshopify.com", actorId: "actor1", permissions: ["promotions.manage"] };

test("rejects unauthenticated and unauthorized actors", async () => { await assert.rejects(() => syncPromotionRuntime({ ...auth, actorId: "" }, { database: db() }), /Authenticated/); await assert.rejects(() => syncPromotionRuntime({ ...auth, permissions: [] }, { database: db() }), /not allowed/); });
test("rejects ambiguous valid-looking title matches", async () => { const database = db(); const graphql = async () => ({ discountNodes: { nodes: [{ discount: node("d1") }, { discount: node("d2") }] } }); await assert.rejects(() => syncPromotionRuntime(auth, { database, graphql: graphql as never, uuid: () => "a1" }), (e) => e instanceof RuntimeSyncError && e.code === "AMBIGUOUS_DISCOUNT_MATCHES"); });
test("preserves last-known-good state when read-back fails", async () => { const database = db(); database.state.set("shop1", { id: "s1", shopId: "shop1", shopifyAutomaticDiscountId: "old", lastSuccessfulConfigurationVersion: 4, lastSuccessfulConfigurationHash: "good", lastSuccessfulCompilationVersions: {}, lastSuccessfulRuleIds: [], activeAttemptId: null, attemptStartedAt: null, leaseExpiresAt: null, stateVersion: 0, createdAt: new Date(), updatedAt: new Date() }); let reads = 0; const graphql = async (query: string) => query.includes("LoopDeskDiscountSearch") ? { discountNodes: { nodes: [] } } : query.includes("mutation") ? { discountAutomaticAppCreate: { automaticAppDiscount: { discountId: "new" }, userErrors: [] }, metafieldsSet: { userErrors: [] } } : (++reads, { node: reads === 1 ? null : { ...node("new"), metafield: { namespace: "bad", key: "runtime_configuration", type: "json", value: "{}" } } }); await assert.rejects(() => syncPromotionRuntime(auth, { database, graphql: graphql as never, uuid: () => "a1" }), /namespace/); assert.equal(database.state.get("shop1")?.shopifyAutomaticDiscountId, "old"); assert.equal(database.state.get("shop1")?.lastSuccessfulConfigurationHash, "good"); });
