"use client";

import { useCallback, useEffect, useState } from "react";
import type { MerchantBillingOverviewDto } from "../../services/billing/merchant-billing-overview";
import { formatBillingMoney, formatBillingQuantity } from "./billing-format";

type Api = { ok: true; overview: MerchantBillingOverviewDto } | { ok: false; error?: string; message?: string };
const statusLabels: Record<string, string> = { ACTIVE: "Active", PENDING_CONFIRMATION: "Pending Shopify approval", TRIALING: "Pending confirmation", PAST_DUE: "Payment issue", CANCELED: "Cancelled" };
const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value));
const label = (value: string) => statusLabels[value] ?? value.replaceAll("_", " ");

export default function BillingDashboard({ shopDomain }: { shopDomain: string }) {
  const [overview, setOverview] = useState<MerchantBillingOverviewDto | null>(null);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/billing/overview?shop=${encodeURIComponent(shopDomain)}`, { cache: "no-store" }); const data = await response.json() as Api; if (!data.ok) { setError(data.error === "COMMERCIAL_CATALOG_NOT_CONFIGURED" && data.message ? data.message : "We couldn't refresh your billing data. Please try again."); return; } if (!response.ok) { setError("We couldn't refresh your billing data. Please try again."); return; } setOverview(data.overview); } catch { setError("We couldn't refresh your billing data. Please try again."); } finally { setLoading(false); } }, [shopDomain]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !overview) return <main className="mk-page"><header className="mk-page-header"><div><h1 className="mk-page-title">Billing</h1><p className="mk-page-subtitle">Loading your subscription and current usage…</p></div></header></main>;
  if (!overview) return <main className="mk-page"><h1 className="mk-page-title">Billing</h1><section className="mk-card" role="alert"><p>{error}</p><button className="mk-btn mt-3" onClick={() => void load()}>Try again</button></section></main>;
  const { subscription, usage, totals, history } = overview;
  return <main className="mk-page mx-auto max-w-6xl"><header className="mk-page-header"><div><h1 className="mk-page-title">Billing</h1><p className="mk-page-subtitle">Review your LoopDesk subscription, current usage, and estimated amount payable.</p></div><button className="mk-btn mk-btn-primary" onClick={() => void load()} disabled={loading}>Refresh billing data</button></header>{error ? <p className="mb-4 text-sm text-red-700" role="alert">{error}</p> : null}
    <section className="mk-card"><h2 className="mk-section-title">LoopDesk Subscription</h2><dl className="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-gray-500">Status</dt><dd className="font-semibold">{label(subscription.status)}</dd></div><div><dt className="text-gray-500">Monthly subscription</dt><dd className="font-semibold">{formatBillingMoney(subscription.monthlyBasePrice)}</dd></div><div><dt className="text-gray-500">Billing period</dt><dd>{date(subscription.periodStart)} – {date(subscription.periodEnd)}</dd></div><div><dt className="text-gray-500">Next renewal</dt><dd>{date(subscription.nextRenewalAt)}</dd></div></dl>{subscription.confirmationRequired ? <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><p>Approve your subscription in Shopify to activate billing.</p>{subscription.confirmationUrl ? <a className="mk-btn mk-btn-primary mt-2 inline-block" href={subscription.confirmationUrl}>Approve subscription in Shopify</a> : null}</div> : null}</section>
    <section className="mk-card"><h2 className="mk-section-title">Current Usage</h2><p className="mk-section-subtitle">Usage charges are estimated from activity recorded in the current billing period.</p><div className="mk-table-wrap"><table className="mk-table"><thead><tr><th>Channel</th><th>Used</th><th>Included</th><th>Billable</th><th>Rate per unit</th><th>Estimated usage charge</th></tr></thead><tbody>{usage.map((feature) => <tr key={feature.featureCode}><td className="font-semibold">{feature.featureName}</td><td>{formatBillingQuantity(feature.usedQuantity)}</td><td>{formatBillingQuantity(feature.includedQuantity)}</td><td>{formatBillingQuantity(feature.billableQuantity)}</td><td>{formatBillingMoney(feature.unitRate)}</td><td>{formatBillingMoney(feature.estimatedCharge)}</td></tr>)}</tbody></table></div></section>
    <section className="mk-card"><h2 className="mk-section-title">Estimated Amount Payable</h2><dl className="max-w-md space-y-3"><div className="flex justify-between gap-3"><dt>Monthly subscription</dt><dd>{formatBillingMoney(totals.subscriptionAmount)}</dd></div><div className="flex justify-between gap-3"><dt>Usage charges</dt><dd>{formatBillingMoney(totals.usageAmount)}</dd></div><div className="flex justify-between gap-3 border-t pt-3 font-bold"><dt>Estimated total</dt><dd>{formatBillingMoney(totals.estimatedTotal)}</dd></div></dl></section>
    <section className="mk-card"><h2 className="mk-section-title">Billing History</h2>{!history.length ? <p className="mk-section-subtitle">Your first billing period is currently in progress.</p> : <div className="mk-table-wrap"><table className="mk-table"><thead><tr><th>Period</th><th>Subscription</th><th>Usage charges</th><th>Total</th><th>Status</th></tr></thead><tbody>{history.map((item) => <tr key={`${item.periodStart}-${item.periodEnd}`}><td>{date(item.periodStart)} – {date(item.periodEnd)}</td><td>{formatBillingMoney(item.subscriptionAmount)}</td><td>{formatBillingMoney(item.usageAmount)}</td><td>{formatBillingMoney(item.totalAmount)}</td><td>{label(item.status)}</td></tr>)}</tbody></table></div>}</section>
  </main>;
}
