/* Read-mostly billing UAT reconciliation. It never rerates, edits rated rows, or creates provider charges. */
import { Prisma } from "../../generated/prisma/index.js";
import { prisma as defaultPrisma } from "../db/prisma.ts";
import { getShopifyUsageRecord, type ShopifyUsageRecord } from "./adapters/shopify/shopify-billing-adapter.ts";

export type BillingReconciliationStatus = "NOT_SUBMITTED" | "PENDING" | "MATCHED" | "AMOUNT_MISMATCH" | "CURRENCY_MISMATCH" | "MISSING_PROVIDER_REFERENCE" | "DUPLICATE_PROVIDER_SUBMISSION" | "PROVIDER_NOT_FOUND" | "FAILED_RETRYABLE" | "FAILED_FINAL" | "SKIPPED_ZERO_AMOUNT";
export type BillingReconciliationResult = { shopId: string; billingPeriodId: string; merchantRatedUsageId: string; featureCode: string; internalAmount: { amount: string; currency: string }; providerAmount: { amount: string; currency: string } | null; providerSubmissionId: string | null; externalReference: string | null; status: BillingReconciliationStatus; checkedAt: string; errorCode: string | null; errorMessage: string | null };
export type BillingUsageVerificationFeature = { featureCode: string; rawQuantity: string; ratedQuantity: string | null; status: "MATCHED" | "RAW_USAGE_MISMATCH" | "RATED_USAGE_MISSING" | "UNMAPPED_USAGE_TYPE" };
export type BillingUatReport = { shopId: string; billingPeriodId: string; periodStatus: string; activePlanCode: string | null; rawUsageVerification: { status: "PASSED" | "FAILED"; features: BillingUsageVerificationFeature[] }; ratingVerification: { status: "PASSED" | "FAILED"; features: Array<{ featureCode: string; usedQuantity: string; includedQuantity: string; billableQuantity: string; amount: string; currency: string }> }; providerSubmissionVerification: { status: "PASSED" | "FAILED" | "NOT_RUN"; results: BillingReconciliationResult[] }; overallStatus: "PASSED" | "FAILED" | "PARTIAL" | "BLOCKED"; blockingReasons: string[]; generatedAt: string };

type Db = any; let db: Db = defaultPrisma as any;
export function __setBillingReconciliationPrismaForTests(client: Db) { db = client; }
export class BillingReconciliationError extends Error { constructor(public readonly code: string) { super(code); this.name = "BillingReconciliationError"; } }
const decimal = (value: unknown) => new Prisma.Decimal((value ?? 0) as Prisma.Decimal.Value);
const log = (event: string, fields: Record<string, unknown>) => console.info(event, fields);
async function periodFor(shopId: string, billingPeriodId: string) { const period = await db.merchantBillingPeriod.findFirst({ where: { id: billingPeriodId, shopId }, include: { subscription: { include: { pricingPlan: true } } } }); if (!period) throw new BillingReconciliationError("BILLING_PERIOD_NOT_FOUND"); return period; }
function result(row: any, submission: any, status: BillingReconciliationStatus, provider: ShopifyUsageRecord | null, errorCode: string | null = null, errorMessage: string | null = null): BillingReconciliationResult { return { shopId: row.shopId, billingPeriodId: row.billingPeriodId, merchantRatedUsageId: row.id, featureCode: row.featureCodeSnapshot, internalAmount: { amount: decimal(row.amount).toString(), currency: row.currency }, providerAmount: provider ? { amount: decimal(provider.amount).toString(), currency: provider.currency } : submission?.amount != null ? { amount: decimal(submission.amount).toString(), currency: submission.currency } : null, providerSubmissionId: submission?.id ?? null, externalReference: submission?.externalReference ?? null, status, checkedAt: new Date().toISOString(), errorCode, errorMessage }; }
async function persist(value: BillingReconciliationResult, provider: string) { if (!db.merchantBillingReconciliation?.create) return; await db.merchantBillingReconciliation.create({ data: { shopId: value.shopId, billingPeriodId: value.billingPeriodId, merchantRatedUsageId: value.merchantRatedUsageId, provider, status: value.status, internalAmount: value.internalAmount.amount, internalCurrency: value.internalAmount.currency, providerAmount: value.providerAmount?.amount ?? null, providerCurrency: value.providerAmount?.currency ?? null, providerSubmissionId: value.providerSubmissionId, externalReference: value.externalReference, errorCode: value.errorCode, errorMessage: value.errorMessage, checkedAt: new Date(value.checkedAt) } }); }

export async function reconcileRatedUsage(input: { shopId: string; billingPeriodId: string; merchantRatedUsageId: string; queryShopifyUsageRecord?: (arg: { shopId: string; externalUsageRecordId: string }) => Promise<ShopifyUsageRecord | null> }): Promise<BillingReconciliationResult> {
  const started = Date.now(); const period = await periodFor(input.shopId, input.billingPeriodId);
  const row = await db.merchantRatedUsage.findFirst({ where: { id: input.merchantRatedUsageId, shopId: input.shopId, billingPeriodId: period.id } }); if (!row) throw new BillingReconciliationError("RATED_USAGE_NOT_FOUND");
  const submissions = await db.merchantBillingProviderSubmission.findMany({ where: { shopId: input.shopId, merchantBillingPeriodId: period.id, merchantRatedUsageId: row.id, provider: period.subscription.billingProvider, operation: "CREATE_USAGE_RECORD" }, orderBy: { createdAt: "asc" } });
  log("billing_reconciliation_started", { shopId: input.shopId, billingPeriodId: period.id, merchantRatedUsageId: row.id, featureCode: row.featureCodeSnapshot });
  const successful = submissions.filter((item: any) => item.status === "SUCCEEDED"); let out: BillingReconciliationResult;
  if (decimal(row.amount).isZero()) out = successful.length ? result(row, successful[0], "AMOUNT_MISMATCH", null, "ZERO_AMOUNT_PROVIDER_CHARGE", "A zero-rated row has a provider charge.") : result(row, null, "SKIPPED_ZERO_AMOUNT", null);
  else if (successful.length > 1) out = result(row, successful[0], "DUPLICATE_PROVIDER_SUBMISSION", null, "DUPLICATE_PROVIDER_SUBMISSION", "More than one successful provider charge exists.");
  else { const submission = submissions[0] ?? null;
    if (!submission) out = result(row, null, "NOT_SUBMITTED", null, "PROVIDER_REFERENCE_MISSING", "No provider submission exists.");
    else if (submission.status === "PENDING" || submission.status === "PROCESSING") out = result(row, submission, "PENDING", null, "PROVIDER_SUBMISSION_PENDING", "Provider submission is pending.");
    else if (submission.status === "FAILED_RETRYABLE") out = result(row, submission, "FAILED_RETRYABLE", null, submission.errorCode, submission.errorMessage);
    else if (submission.status === "FAILED_FINAL") out = result(row, submission, "FAILED_FINAL", null, submission.errorCode, submission.errorMessage);
    else if (!submission.externalReference) out = result(row, submission, "MISSING_PROVIDER_REFERENCE", null, "PROVIDER_REFERENCE_MISSING", "Successful submission has no provider reference.");
    else { const provider = period.subscription.billingProvider === "SHOPIFY" ? await (input.queryShopifyUsageRecord ?? getShopifyUsageRecord)({ shopId: input.shopId, externalUsageRecordId: submission.externalReference }) : { id: submission.externalReference, amount: String(submission.amount), currency: submission.currency };
      if (!provider) out = result(row, submission, "PROVIDER_NOT_FOUND", null, "PROVIDER_NOT_FOUND", "Provider usage record was not found.");
      else if (row.currency !== provider.currency) out = result(row, submission, "CURRENCY_MISMATCH", provider, "CURRENCY_MISMATCH", "Provider currency differs from rated currency.");
      else if (!decimal(row.amount).equals(decimal(provider.amount))) out = result(row, submission, "AMOUNT_MISMATCH", provider, "AMOUNT_MISMATCH", "Provider amount differs from rated amount.");
      else out = result(row, submission, "MATCHED", provider);
    }
  }
  await persist(out, period.subscription.billingProvider); log(out.status === "MATCHED" ? "billing_reconciliation_matched" : "billing_reconciliation_mismatch", { shopId: input.shopId, billingPeriodId: period.id, merchantRatedUsageId: row.id, featureCode: row.featureCodeSnapshot, internalAmount: out.internalAmount.amount, reconciliationStatus: out.status, duration: Date.now() - started }); return out;
}
export async function reconcileBillingPeriod(input: { shopId: string; billingPeriodId: string; queryShopifyUsageRecord?: (arg: { shopId: string; externalUsageRecordId: string }) => Promise<ShopifyUsageRecord | null> }) { await periodFor(input.shopId, input.billingPeriodId); const rows = await db.merchantRatedUsage.findMany({ where: { shopId: input.shopId, billingPeriodId: input.billingPeriodId }, orderBy: { featureCodeSnapshot: "asc" } }); return Promise.all(rows.map((row: any) => reconcileRatedUsage({ ...input, merchantRatedUsageId: row.id }))); }
export async function listBillingReconciliationResults(input: { shopId: string; billingPeriodId: string }) { await periodFor(input.shopId, input.billingPeriodId); return db.merchantBillingReconciliation?.findMany ? db.merchantBillingReconciliation.findMany({ where: { shopId: input.shopId, billingPeriodId: input.billingPeriodId }, orderBy: { checkedAt: "desc" } }) : []; }
export async function getBillingReconciliationStatus(input: { shopId: string; billingPeriodId: string }) { const rows = await reconcileBillingPeriod(input); return { status: rows.every((row) => row.status === "MATCHED" || row.status === "SKIPPED_ZERO_AMOUNT") ? "MATCHED" : "UNRESOLVED", results: rows }; }
export async function verifyBillingPeriodUsage(input: { shopId: string; billingPeriodId: string }) { const period = await periodFor(input.shopId, input.billingPeriodId); const events = await db.merchantUsageEvent.findMany({ where: { shopId: input.shopId, status: "RECORDED", occurredAt: { gte: period.periodStart, lt: period.periodEnd } }, select: { usageType: true, quantity: true } }); const rows = await db.merchantRatedUsage.findMany({ where: { shopId: input.shopId, billingPeriodId: period.id } }); const map: Record<string, string> = { OTP: "OTP", EMAIL: "EMAIL" }; const totals = new Map<string, Prisma.Decimal>(); const features: BillingUsageVerificationFeature[] = []; for (const event of events) { const code = map[event.usageType]; if (!code) { features.push({ featureCode: event.usageType, rawQuantity: decimal(event.quantity).toString(), ratedQuantity: null, status: "UNMAPPED_USAGE_TYPE" }); continue; } totals.set(code, (totals.get(code) ?? decimal(0)).plus(decimal(event.quantity))); } for (const [code, raw] of totals) { const rated = rows.find((row: any) => row.featureCodeSnapshot === code); features.push({ featureCode: code, rawQuantity: raw.toString(), ratedQuantity: rated ? decimal(rated.usedQuantity).toString() : null, status: !rated ? "RATED_USAGE_MISSING" : raw.equals(decimal(rated.usedQuantity)) ? "MATCHED" : "RAW_USAGE_MISMATCH" }); } return { status: features.every((feature) => feature.status === "MATCHED") ? "PASSED" as const : "FAILED" as const, features }; }
export async function runBillingUatScenario(input: { shopId: string; billingPeriodId: string; submitProviderUsage?: boolean; reconcileProvider?: boolean }) { const period = await periodFor(input.shopId, input.billingPeriodId); if (input.submitProviderUsage && (process.env.NODE_ENV === "production" || process.env.BILLING_UAT_SHOPIFY_TEST_MODE !== "true")) throw new BillingReconciliationError("LIVE_BILLING_NOT_ALLOWED_FROM_UAT"); const raw = await verifyBillingPeriodUsage(input); const rated = await db.merchantRatedUsage.findMany({ where: { shopId: input.shopId, billingPeriodId: period.id }, orderBy: { featureCodeSnapshot: "asc" } }); const blockers: string[] = []; if (period.status !== "RATED" && period.status !== "CLOSED") blockers.push("BILLING_PERIOD_NOT_RATED"); if (!rated.length) blockers.push("RATED_USAGE_MISSING"); if (period.subscription.status !== "ACTIVE" && period.subscription.billingProvider === "SHOPIFY") blockers.push("PROVIDER_SUBSCRIPTION_NOT_ACTIVE"); let results: BillingReconciliationResult[] = []; if (input.reconcileProvider && !blockers.length) results = await reconcileBillingPeriod(input); const providerStatus = !input.reconcileProvider ? "NOT_RUN" as const : results.every((row) => row.status === "MATCHED" || row.status === "SKIPPED_ZERO_AMOUNT") ? "PASSED" as const : "FAILED" as const; const ratingFeatures = rated.map((row: any) => ({ featureCode: row.featureCodeSnapshot, usedQuantity: decimal(row.usedQuantity).toString(), includedQuantity: decimal(row.includedQuantity).toString(), billableQuantity: decimal(row.billableQuantity).toString(), amount: decimal(row.amount).toString(), currency: row.currency })); const overallStatus = blockers.length ? "BLOCKED" as const : raw.status === "PASSED" && providerStatus !== "FAILED" ? "PASSED" as const : "FAILED" as const; return { shopId: input.shopId, billingPeriodId: period.id, periodStatus: period.status, activePlanCode: process.env.BILLING_UAT_PLAN_CODE ?? period.subscription.pricingPlan?.code ?? null, rawUsageVerification: raw, ratingVerification: { status: rated.length ? "PASSED" as const : "FAILED" as const, features: ratingFeatures }, providerSubmissionVerification: { status: providerStatus, results }, overallStatus, blockingReasons: blockers, generatedAt: new Date().toISOString() } satisfies BillingUatReport; }
