import test, { beforeEach } from "node:test";
import assert from "node:assert/strict";
import { __setBillingReconciliationPrismaForTests, reconcileRatedUsage, verifyBillingPeriodUsage } from "./reconciliation.ts";
const at = (s: string) => new Date(s);
function fixture() { const period: any = { id: "p1", shopId: "shop-a", status: "RATED", periodStart: at("2026-07-01T00:00:00Z"), periodEnd: at("2026-08-01T00:00:00Z"), subscription: { billingProvider: "SHOPIFY", status: "ACTIVE", pricingPlan: { code: "UAT" } } }; const rows: any[] = [{ id: "otp", shopId: "shop-a", billingPeriodId: "p1", featureCodeSnapshot: "OTP", usedQuantity: "2.000000", includedQuantity: "1", billableQuantity: "1", amount: "0.100000", currency: "INR" }]; const submissions: any[] = [{ id: "s1", shopId: "shop-a", merchantBillingPeriodId: "p1", merchantRatedUsageId: "otp", provider: "SHOPIFY", operation: "CREATE_USAGE_RECORD", status: "SUCCEEDED", amount: "0.1", currency: "INR", externalReference: "gid://usage/1", createdAt: at("2026-08-02T00:00:00Z") }]; const events = [{ shopId: "shop-a", usageType: "OTP", status: "RECORDED", quantity: "2", occurredAt: at("2026-07-01T00:00:00Z") }, { shopId: "shop-a", usageType: "OTP", status: "RECORDED", quantity: "9", occurredAt: at("2026-08-01T00:00:00Z") }]; const db: any = { merchantBillingPeriod: { async findFirst({ where }: any) { return where.shopId === "shop-a" && where.id === "p1" ? period : null; } }, merchantRatedUsage: { async findFirst({ where }: any) { return rows.find((r) => r.id === where.id && r.shopId === where.shopId && r.billingPeriodId === where.billingPeriodId) ?? null; }, async findMany({ where }: any) { return rows.filter((r) => r.shopId === where.shopId && r.billingPeriodId === where.billingPeriodId); } }, merchantBillingProviderSubmission: { async findMany({ where }: any) { return submissions.filter((s) => s.shopId === where.shopId && s.merchantRatedUsageId === where.merchantRatedUsageId); } }, merchantUsageEvent: { async findMany({ where }: any) { return events.filter((e) => e.shopId === where.shopId && e.status === where.status && e.occurredAt >= where.occurredAt.gte && e.occurredAt < where.occurredAt.lt); } }, merchantBillingReconciliation: { async create() {} } }; __setBillingReconciliationPrismaForTests(db); return { rows, submissions }; }
beforeEach(fixture);
test("reconciles decimal-safe Shopify amounts and preserves ownership", async () => { const matched = await reconcileRatedUsage({ shopId: "shop-a", billingPeriodId: "p1", merchantRatedUsageId: "otp", queryShopifyUsageRecord: async () => ({ id: "gid://usage/1", amount: "0.100000", currency: "INR" }) }); assert.equal(matched.status, "MATCHED"); await assert.rejects(() => reconcileRatedUsage({ shopId: "shop-b", billingPeriodId: "p1", merchantRatedUsageId: "otp" }), /BILLING_PERIOD_NOT_FOUND/); });
test("flags duplicate successful records and zero-rated provider charges", async () => { const { submissions, rows } = fixture(); submissions.push({ ...submissions[0], id: "s2", externalReference: "gid://usage/2" }); assert.equal((await reconcileRatedUsage({ shopId: "shop-a", billingPeriodId: "p1", merchantRatedUsageId: "otp" })).status, "DUPLICATE_PROVIDER_SUBMISSION"); submissions.splice(1); rows[0].amount = "0"; assert.equal((await reconcileRatedUsage({ shopId: "shop-a", billingPeriodId: "p1", merchantRatedUsageId: "otp" })).status, "AMOUNT_MISMATCH"); });
test("uses half-open raw usage bounds without mutating events", async () => { const report = await verifyBillingPeriodUsage({ shopId: "shop-a", billingPeriodId: "p1" }); assert.equal(report.status, "PASSED"); assert.deepEqual(report.features[0], { featureCode: "OTP", rawQuantity: "2", ratedQuantity: "2", status: "MATCHED" }); });
