api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "gst-invoice-print"
uid = "23f5aaa8-8187-485d-9fee-47433f76f072"
type = "ui_extension"

# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
target = "admin.order-details.print-action.render"
