import { prisma } from "../../db/prisma.ts";
import { ShopifyBillingAdapter } from "../adapters/shopify/shopify-billing-adapter.ts";

export class PlanLifecycleError extends Error { constructor(public readonly code: string) { super(code); this.name = "PlanLifecycleError"; } }
const unresolved = ["PENDING", "PENDING_PROVIDER_CONFIRMATION", "SCHEDULED", "PROCESSING"] as const;
type Timing = "IMMEDIATE" | "PERIOD_END";
export type PlanChangeResult = { planChangeId: string; status: string; timing: Timing; effectiveAt: string | null; confirmationUrl: string | null };
function result(change: { id: string; status: string; timing: Timing; effectiveAt: Date | null; externalReference: string | null }): PlanChangeResult { return { planChangeId: change.id, status: change.status, timing: change.timing, effectiveAt: change.effectiveAt?.toISOString() ?? null, confirmationUrl: change.externalReference } }
async function plan(code: string) { const row = await prisma.pricingPlan.findUnique({ where: { code: code.trim() } }); if (!row) throw new PlanLifecycleError("PLAN_NOT_FOUND"); if (!row.active) throw new PlanLifecycleError("PLAN_INACTIVE"); return row; }
async function subscription(shopId: string, id?: string) { const row = await prisma.merchantSubscription.findFirst({ where: { shopId, ...(id ? { id } : {}) }, include: { pricingPlan: true } }); if (!row) throw new PlanLifecycleError("SUBSCRIPTION_NOT_ACTIVE"); if (row.status === "CANCELED") throw new PlanLifecycleError("SUBSCRIPTION_ALREADY_CANCELED"); return row; }
async function pending(shopId: string, merchantSubscriptionId: string) { return prisma.merchantPlanChange.findFirst({ where: { shopId, merchantSubscriptionId, status: { in: [...unresolved] } }, orderBy: { requestedAt: "desc" } }); }
function returnUrl(changeId: string) { const base = process.env.SHOPIFY_APP_URL ?? process.env.NEXT_PUBLIC_APP_URL; if (!base) throw new PlanLifecycleError("BILLING_RETURN_URL_NOT_CONFIGURED"); return `${base.replace(/\/$/, "")}/api/admin/billing/plan/confirm?planChangeId=${encodeURIComponent(changeId)}`; }
async function createProviderConfirmation(changeId: string, shopId: string, sub: { id: string }, target: Awaited<ReturnType<typeof plan>>) {
  const provider = new ShopifyBillingAdapter(); const created = await provider.createSubscription({ shopId, merchantSubscriptionId: sub.id, planName: target.name, currency: target.currency, monthlyBasePrice: target.monthlyBasePrice.toString(), returnUrl: returnUrl(changeId), idempotencyKey: `shopify:${changeId}` });
  return prisma.merchantPlanChange.update({ where: { id: changeId }, data: { status: "PENDING_PROVIDER_CONFIRMATION", provider: "SHOPIFY", externalReference: created.confirmationUrl, providerSubmissionId: created.externalSubscriptionId } });
}
export async function requestInitialSubscription(input: { shopId: string; pricingPlanCode: string }): Promise<PlanChangeResult> {
  const target = await plan(input.pricingPlanCode); const existing = await prisma.merchantSubscription.findUnique({ where: { shopId: input.shopId } });
  if (existing && ["ACTIVE", "TRIALING", "PAST_DUE", "PAUSED"].includes(existing.status)) throw new PlanLifecycleError("PLAN_ALREADY_ACTIVE");
  const sub = existing ?? await prisma.merchantSubscription.create({ data: { shopId: input.shopId, pricingPlanId: target.id, status: "TRIALING", billingProvider: "SHOPIFY", renewsAutomatically: true } });
  const key = `plan-change:initial:${input.shopId}:${target.id}`; let change = await prisma.merchantPlanChange.findUnique({ where: { idempotencyKey: key } });
  if (!change) change = await prisma.merchantPlanChange.create({ data: { shopId: input.shopId, merchantSubscriptionId: sub.id, toPricingPlanId: target.id, changeType: "INITIAL_SUBSCRIPTION", timing: "IMMEDIATE", status: "PENDING", idempotencyKey: key, provider: "SHOPIFY" } });
  if (change.status === "PENDING") change = await createProviderConfirmation(change.id, input.shopId, sub, target);
  console.info("plan_selection_requested", { shopId: input.shopId, subscriptionId: sub.id, planChangeId: change.id, toPlanCode: target.code, status: change.status }); return result(change);
}
export async function requestPlanChange(input: { shopId: string; merchantSubscriptionId: string; targetPlanCode: string; requestedTiming?: Timing }): Promise<PlanChangeResult> {
  const sub = await subscription(input.shopId, input.merchantSubscriptionId); const target = await plan(input.targetPlanCode); if (target.id === sub.pricingPlanId) throw new PlanLifecycleError("PLAN_ALREADY_ACTIVE");
  const active = await pending(input.shopId, sub.id); if (active) throw new PlanLifecycleError("PLAN_CHANGE_ALREADY_PENDING"); const upgrade = target.tierRank > sub.pricingPlan.tierRank; const timing: Timing = upgrade ? "IMMEDIATE" : "PERIOD_END";
  const effectiveAt = timing === "PERIOD_END" ? sub.currentPeriodEnd : null; if (timing === "PERIOD_END" && !effectiveAt) throw new PlanLifecycleError("CURRENT_PERIOD_NOT_FINALIZED");
  const key = `plan-change:${upgrade ? "upgrade" : "downgrade"}:${sub.id}:${target.id}:${effectiveAt?.toISOString() ?? "immediate"}`;
  let change = await prisma.merchantPlanChange.create({ data: { shopId: input.shopId, merchantSubscriptionId: sub.id, fromPricingPlanId: sub.pricingPlanId, toPricingPlanId: target.id, changeType: upgrade ? "UPGRADE" : "DOWNGRADE", timing, status: timing === "PERIOD_END" ? "SCHEDULED" : "PENDING", effectiveAt, idempotencyKey: key, provider: sub.billingProvider } });
  if (timing === "IMMEDIATE") change = await createProviderConfirmation(change.id, input.shopId, sub, target); console.info("plan_change_requested", { shopId: input.shopId, subscriptionId: sub.id, planChangeId: change.id, fromPlanCode: sub.pricingPlan.code, toPlanCode: target.code, timing, status: change.status }); return result(change);
}
export async function confirmPlanChange(input: { shopId: string; planChangeId: string }) { const change = await prisma.merchantPlanChange.findFirst({ where: { id: input.planChangeId, shopId: input.shopId }, include: { toPricingPlan: true } }); if (!change) throw new PlanLifecycleError("PLAN_NOT_FOUND"); if (change.status === "APPLIED") return result(change); if (change.status !== "PENDING_PROVIDER_CONFIRMATION") throw new PlanLifecycleError("PROVIDER_CONFIRMATION_REQUIRED"); if (!change.providerSubmissionId || change.provider !== "SHOPIFY") throw new PlanLifecycleError("PROVIDER_SUBSCRIPTION_MISMATCH"); const providerStatus = await new ShopifyBillingAdapter().getAppSubscriptionStatus({ shopId: input.shopId, externalSubscriptionId: change.providerSubmissionId }); if (!providerStatus || providerStatus.id !== change.providerSubmissionId || providerStatus.status !== "ACTIVE") throw new PlanLifecycleError("PROVIDER_CONFIRMATION_REQUIRED"); await prisma.merchantSubscription.update({ where: { id: change.merchantSubscriptionId }, data: { pricingPlanId: change.toPricingPlanId!, status: "ACTIVE", billingProvider: "SHOPIFY", externalSubscriptionReference: change.providerSubmissionId, providerStatus: "ACTIVE", confirmationUrl: null, providerActivatedAt: new Date() } }); const applied = await prisma.merchantPlanChange.update({ where: { id: change.id }, data: { status: "APPLIED", confirmedAt: new Date(), appliedAt: new Date(), effectiveAt: new Date() } }); console.info("plan_change_provider_confirmation_completed", { shopId: input.shopId, planChangeId: change.id }); return result(applied); }
export async function requestSubscriptionCancellation(input: { shopId: string; merchantSubscriptionId: string }) { const sub = await subscription(input.shopId, input.merchantSubscriptionId); if (!sub.currentPeriodEnd) throw new PlanLifecycleError("CURRENT_PERIOD_NOT_FINALIZED"); const existing = await pending(input.shopId, sub.id); if (existing) throw new PlanLifecycleError(existing.changeType === "CANCEL" ? "CANCELLATION_ALREADY_SCHEDULED" : "PLAN_CHANGE_ALREADY_PENDING"); const key = `plan-change:cancel:${sub.id}:${sub.currentPeriodEnd.toISOString()}`; const change = await prisma.merchantPlanChange.create({ data: { shopId: input.shopId, merchantSubscriptionId: sub.id, fromPricingPlanId: sub.pricingPlanId, changeType: "CANCEL", timing: "PERIOD_END", status: "SCHEDULED", effectiveAt: sub.currentPeriodEnd, idempotencyKey: key, provider: sub.billingProvider } }); await prisma.merchantSubscription.update({ where: { id: sub.id }, data: { renewsAutomatically: false, cancellationEffectiveAt: sub.currentPeriodEnd } }); return result(change); }
export async function reactivateSubscription(input: { shopId: string; merchantSubscriptionId: string }) { const sub = await subscription(input.shopId, input.merchantSubscriptionId); const change = await prisma.merchantPlanChange.findFirst({ where: { shopId: input.shopId, merchantSubscriptionId: sub.id, changeType: "CANCEL", status: "SCHEDULED" } }); if (!change || !sub.cancellationEffectiveAt || sub.cancellationEffectiveAt <= new Date()) throw new PlanLifecycleError("REACTIVATION_NOT_ALLOWED"); await prisma.$transaction([prisma.merchantPlanChange.update({ where: { id: change.id }, data: { status: "CANCELED", canceledAt: new Date() } }), prisma.merchantSubscription.update({ where: { id: sub.id }, data: { renewsAutomatically: true, cancellationEffectiveAt: null } })]); console.info("subscription_reactivated", { shopId: input.shopId, subscriptionId: sub.id, planChangeId: change.id }); return { planChangeId: change.id, status: "CANCELED" }; }
export async function cancelScheduledPlanChange(input: { shopId: string; planChangeId: string }) { const change = await prisma.merchantPlanChange.findFirst({ where: { id: input.planChangeId, shopId: input.shopId, status: "SCHEDULED" } }); if (!change) throw new PlanLifecycleError("PLAN_CHANGE_NOT_EFFECTIVE_YET"); return prisma.merchantPlanChange.update({ where: { id: change.id }, data: { status: "CANCELED", canceledAt: new Date() } }); }
export async function getCurrentPlanLifecycleStatus(input: { shopId: string }) { return prisma.merchantPlanChange.findFirst({ where: { shopId: input.shopId, status: { in: [...unresolved] } }, orderBy: { requestedAt: "desc" }, include: { fromPricingPlan: true, toPricingPlan: true } }); }
export async function applyScheduledPlanChanges(input: { now?: Date; limit?: number } = {}) { const now = input.now ?? new Date(); const changes = await prisma.merchantPlanChange.findMany({ where: { status: "SCHEDULED", effectiveAt: { lte: now } }, orderBy: [{ effectiveAt: "asc" }, { id: "asc" }], take: Math.min(Math.max(input.limit ?? 50, 1), 100), include: { merchantSubscription: { include: { billingPeriods: { where: { status: { not: "CLOSED" } }, orderBy: { periodEnd: "desc" }, take: 1 } } } } }); const results=[] as Array<{id:string;status:string}>; for (const change of changes) { try { if (change.merchantSubscription.billingPeriods.length) throw new PlanLifecycleError("CURRENT_PERIOD_NOT_FINALIZED"); if (change.changeType === "CANCEL") await prisma.merchantSubscription.update({ where: { id: change.merchantSubscriptionId }, data: { status: "CANCELED", canceledAt: now, renewsAutomatically: false } }); else await prisma.merchantSubscription.update({ where: { id: change.merchantSubscriptionId }, data: { pricingPlanId: change.toPricingPlanId! } }); await prisma.merchantPlanChange.update({ where: { id: change.id }, data: { status: "APPLIED", appliedAt: now } }); results.push({id:change.id,status:"APPLIED"}); } catch { results.push({id:change.id,status:"DEFERRED"}); } } return { processed: results.length, results }; }
