"use client";
import { useActionState, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import { compilePromotionRuleAction, type PromotionCompileActionState } from "../../../services/promotions/compiler-admin-actions.server";
import type { PromotionEmbeddedContext } from "../../../services/promotions/admin-context";
import type { PromotionExecutionReadModel } from "../../../services/promotions/compiler-admin-read-model.server";
import type { PromotionRuleStatus } from "../../../services/promotions/domain";
import PromotionConfirmationDialog from "./PromotionConfirmationDialog";
const initial: PromotionCompileActionState = { ok: true };
function EmbeddedInputs({ shopId, context }: { shopId: string; context: PromotionEmbeddedContext }) { return <><input type="hidden" name="shopId" value={shopId} /><input type="hidden" name="shop" value={String(context.shop || "")} /><input type="hidden" name="shopify_shop" value={String(context.shopify_shop || "")} /><input type="hidden" name="host" value={String(context.host || "")} /><input type="hidden" name="embedded" value={String(context.embedded || "")} /></>; }
function SubmitButton({ label, disabled }: { label: string; disabled?: boolean }) { const { pending } = useFormStatus(); return <button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-gray-300" disabled={disabled || pending} type="submit">{pending ? "Compiling…" : label}</button>; }
export default function PromotionCompilationControls({ shopId, embeddedContext, promotionRuleId, status, execution, dirty = false }: { shopId: string; embeddedContext: PromotionEmbeddedContext; promotionRuleId: string; status: PromotionRuleStatus; execution: PromotionExecutionReadModel; dirty?: boolean }) {
  const [state, action] = useActionState(compilePromotionRuleAction, initial); const [confirm, setConfirm] = useState(false); const submit = useRef<HTMLButtonElement>(null); const confirmed = useRef(false);
  if (status === "DRAFT") return <p className="rounded-lg bg-gray-50 p-3 text-sm text-gray-700">Activate this rule before compiling it.</p>;
  if (status === "ARCHIVED") return <p className="rounded-lg bg-gray-50 p-3 text-sm text-gray-700">Archived promotions cannot be compiled.</p>;
  const hasCurrent = Boolean(execution.currentCompilation); const label = hasCurrent || status === "PAUSED" ? "Recompile" : "Compile now";
  const message = status === "PAUSED" ? "Recompile this paused promotion? Its execution data may change, but the rule will remain paused." : hasCurrent ? "Recompile this promotion? A successful result will replace the current compilation. If it fails, the existing working compilation will be preserved." : "Compile this promotion? LoopDesk will resolve qualifying products and generate versioned execution data. This does not publish a Shopify discount.";
  return <div className="space-y-2"><p className="text-sm text-gray-500">Compilation runs now and may take longer for collection or product-type triggers. This does not publish a Shopify discount.</p>{status === "PAUSED" ? <p className="text-sm text-amber-700">This rule remains paused after recompilation.</p> : null}{dirty ? <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Save your changes before compiling.</p> : null}{!state.ok && state.message ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.message}</p> : null}<form action={action} onSubmit={(e) => { if (confirmed.current) { confirmed.current = false; return; } e.preventDefault(); if (!dirty) setConfirm(true); }}><EmbeddedInputs shopId={shopId} context={embeddedContext} /><input type="hidden" name="promotionRuleId" value={promotionRuleId} /><SubmitButton label={label} disabled={dirty} /><button hidden ref={submit} formAction={action} type="submit">confirm</button></form><PromotionConfirmationDialog open={confirm} title={`${label} promotion?`} message={message} confirmLabel={label} onCancel={() => setConfirm(false)} onConfirm={() => { confirmed.current = true; setConfirm(false); submit.current?.click(); }} /></div>;
}
