-- Row-Level Security for ClinicDesk.
--
-- Defence in depth behind `clinicScope()`. Generated by iterating every table
-- that has a `clinicId` column, so a newly added tenant-scoped model is covered
-- the next time this runs rather than being silently left open.
--
-- Idempotent: safe to re-run.

DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_name = c.table_name AND t.table_schema = c.table_schema
    WHERE c.table_schema = 'public'
      AND c.column_name = 'clinicId'
      AND t.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target.table_name);

    -- FORCE also applies the policy to the table's owner. Without it, the
    -- migration role silently bypasses every policy below.
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target.table_name);

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', target.table_name);

    -- current_setting(..., true) returns NULL when unset, so an unscoped
    -- connection sees nothing rather than everything.
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING ("clinicId" = current_setting('app.clinic_id', true))
        WITH CHECK ("clinicId" = current_setting('app.clinic_id', true))
    $f$, target.table_name);

    RAISE NOTICE 'RLS enabled on %', target.table_name;
  END LOOP;
END $$;

-- The application role. It must NOT be a superuser and must not own the tables,
-- or RLS is bypassed regardless of the policies above.
--
--   CREATE ROLE clinicdesk_app LOGIN PASSWORD '...';
--   GRANT USAGE ON SCHEMA public TO clinicdesk_app;
--   GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO clinicdesk_app;
--   ALTER DEFAULT PRIVILEGES IN SCHEMA public
--     GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO clinicdesk_app;
