ALTER TABLE "ReviewSettings"
  ADD COLUMN "reviewSectionHeading" TEXT NOT NULL DEFAULT 'Customer reviews',
  ADD COLUMN "reviewEmptyStateText" TEXT NOT NULL DEFAULT 'No reviews yet.',
  ADD COLUMN "reviewVerifiedPurchaseText" TEXT NOT NULL DEFAULT 'Verified purchase',
  ADD COLUMN "reviewLoadMoreText" TEXT NOT NULL DEFAULT 'Load more reviews',
  ADD COLUMN "reviewWriteReviewText" TEXT NOT NULL DEFAULT 'Write a review',
  ADD COLUMN "reviewCountTextTemplate" TEXT NOT NULL DEFAULT '{count} reviews',
  ADD COLUMN "reviewAccentColor" TEXT NOT NULL DEFAULT '#111111',
  ADD COLUMN "reviewStarColor" TEXT NOT NULL DEFAULT '#F5A623',
  ADD COLUMN "reviewHeadingColor" TEXT NOT NULL DEFAULT '#111111',
  ADD COLUMN "reviewTextColor" TEXT NOT NULL DEFAULT '#333333',
  ADD COLUMN "reviewMutedTextColor" TEXT NOT NULL DEFAULT '#6B6B6B',
  ADD COLUMN "reviewBorderColor" TEXT NOT NULL DEFAULT '#E5E5E5',
  ADD COLUMN "reviewBackgroundColor" TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN "reviewButtonBackgroundColor" TEXT NOT NULL DEFAULT '#111111',
  ADD COLUMN "reviewButtonTextColor" TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN "reviewAlignment" TEXT NOT NULL DEFAULT 'left',
  ADD COLUMN "reviewCardStyle" TEXT NOT NULL DEFAULT 'minimal',
  ADD COLUMN "reviewCornerRadius" INTEGER NOT NULL DEFAULT 8,
  ADD COLUMN "reviewSectionSpacing" TEXT NOT NULL DEFAULT 'normal',
  ADD COLUMN "showReviewSectionHeading" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "showWriteReviewButton" BOOLEAN NOT NULL DEFAULT true;
