schema {
  query: Input
}

scalar Decimal
scalar ID

type Input {
  discount: Discount!
  cart: Cart!
}

type Discount {
  metafield(namespace: String, key: String!): Metafield
  discountClasses: [DiscountClass!]!
}

enum DiscountClass {
  PRODUCT
  ORDER
  SHIPPING
}

type Metafield {
  value: String!
}

type Cart {
  lines: [CartLine!]!
}

type CartLine {
  id: ID!
  quantity: Int!
  cost: CartLineCost!
  merchandise: Merchandise!
}

type CartLineCost {
  subtotalAmount: MoneyV2!
}

type MoneyV2 {
  amount: Decimal!
  currencyCode: String!
}

interface Merchandise {
  id: ID!
}

type ProductVariant implements Merchandise {
  id: ID!
}

type CartLinesDiscountsGenerateRunResult {
  operations: [CartOperation!]!
}

union CartOperation = ProductDiscountsAddOperation

type ProductDiscountsAddOperation {
  candidates: [ProductDiscountCandidate!]!
  selectionStrategy: ProductDiscountSelectionStrategy!
}

enum ProductDiscountSelectionStrategy {
  FIRST
  MAXIMUM
  ALL
}

type ProductDiscountCandidate {
  message: String
  targets: [ProductDiscountCandidateTarget!]!
  value: ProductDiscountCandidateValue!
  associatedDiscountCode: AssociatedDiscountCode
}

union ProductDiscountCandidateTarget = ProductVariantTarget

type ProductVariantTarget {
  id: ID!
  quantity: Int
}

union ProductDiscountCandidateValue = Percentage | FixedAmount

type Percentage {
  value: Decimal!
}

type FixedAmount {
  amount: Decimal!
  appliesToEachItem: Boolean
}

type AssociatedDiscountCode {
  code: String!
}
