api_version = "2026-04"
uid = "fd7ac504-a401-ea17-d1d5-c493c138d06638c25881"

[[extensions]]
name = "LoopD2C Promotions"
type = "function"
handle = "loopdesk-discount-function"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/loopdesk_discount_function.wasm"
  watch = ["src/**/*.rs"]
